### ISSUE TITLE
Reject document `type` changes wholesale

### ISSUE THREAD

**Issue by FloRad** [foundryvtt/foundryvtt#10035]
### User Experience

I occasionally see recommendations floating around to change the `type` property of an Actor or Item document to solve some sort of issue. Foundry should wholesale reject updates to a document's type to prevent potential foot-gun scenarios

**Comment by aaclayton** [comment]
There are use cases where we need to allow this, especially now that Foundry VTT supports module-defined custom types. I agree it can be dangerous to make this change, but we have code in place that cleans the `system` object when the `type` changes in order to ensure the document remains *functional* even if some prior data was lost.

I don't anticipate that we would ever expose a UI to make this change (or encourage game systems to do so either) - but I don't think it's something we can forbid via the API. @Fyorl may have more thoughts since he did much of the work on custom module subtypes.

**Comment by Fyorl** [comment]
If a module that provides a custom sub-type is disabled, there needs to be a way to migrate Documents using that sub-type. It might be the module itself that offers this migration path (before it's disabled, of course), or some newer generation of the module taking over from an older one. So I think there probably needs to be a way to change the `type` via the API.

**Comment by FloRad** [comment]
I see, thanks for the clarification!

**Comment by aaclayton** [comment]
Closing as wontfix given the requirements for this.
