### ISSUE TITLE
Editing Text via doubleclick

### ISSUE THREAD

**Issue by zarazandra** [foundryvtt/foundryvtt#10094]
### User Experience

Hello once again, 

I really don't know if it is already possible to change a setting to do so, but I didn't find anything so sorry, if this is invalid. 

But, when I want to change text via the drawingtool-feature to the canvas, I always have to go to the properties first and into the text-tab to edit the text. I would love the opportunity, to just edit the text by doubleclicking it. A smart way to head to the properties would be via right-click-selection. 

Would that be possible? 

Thanks in advance

**Comment by unsoluble** [comment]
In current/recent versions of v11, you should be able to directly edit drawing text after selecting the object (per #8615).

**Comment by unsoluble** [comment]
Hah, fired up a v11 host to verify this just in case, and it turns out this _doesn't_ actually work as expected in 11.313 — now I'm not exactly sure what was fixed in #8615.

(To be clear, the expected behaviour is that after selecting a text drawing object with the drawing selection tool, all keyboard input would be directed to the text label — new characters added and deletions removed. Currently, typing new characters does nothing, and delete deletes the entire object.)

**Comment by zarazandra** [comment]
Just to clarify: when saying that text should be altered just by typing, does that mean, that it'll always add text to the existing one or does it completely replace existing text? 
In case of the second scenario, I would really love to get a doubleclick-feature for entereing the text - just like a textbox in e.g. microsoft word - so you can alter what's inside easily without having to go through the properties or lose text already written.

**Comment by unsoluble** [comment]
In the pre-v10 era, when you selected a text drawing and just started typing, it would append that new text to the drawing (or delete individual characters on Delete). Pretty sure it was an unintentional regression when this changed, and was purportedly addressed in #8615 as I mentioned above, but I haven't seen a return to that behaviour yet in any v11 build.
