### ISSUE TITLE
Validate required system version for modules before installing update

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10096]
### User Experience

As a user, I would like Foundry to inform me if an update to a module would break compatibility with a currently installed system version before updating.

As a developer, I would like to be able to release updates for a module ahead of a system update without causing issues for users before that system update happens.

---

Foundry's handling of system compatibility is pretty bare bones. Right now, mature systems often offer preview versions/release candidates prior to the actual release, often with changes that are not backwards compatible. Furthermore, users do not always update to new system versions in a timely fashion, especially if there's major breaking changes that would disrupt an ongoing campaign. Right now, as a developer, I have to wait for a system update to go live before I can release an update, and if a user has an incompatible system version they will have to manually handle the versioning of my module. The UX on all ends here would be improved if module updates where the manifest lists minimum compatible system versions were automatically checked.

Edge case to consider: Modules that list *multiple* compatible systems, or where a system isn't strictly required but simply listed for some feature functionality. I don't have a good clean answer for what that UX should be.

**Comment by aaclayton** [comment]
@Fyorl this issue may be closely related to or even duplicative of our work on pre-flight compatibility check. Take a look and see what of this we are addressing in V11 and what might need to be rescoped for V12 or later.

**Comment by Fyorl** [comment]
> Edge case to consider: Modules that list multiple compatible systems, or where a system isn't strictly required but simply listed for some feature functionality. I don't have a good clean answer for what that UX should be.

This is not really an edge case, it's more like the entire problem. The `relationships.systems` field is very loosely defined as 'the set of systems that this package supports'. There is no way to indicate a stronger relationship than that.

Consider a module that is broadly compatible with most systems, but has defined a `relationships.systems` in order to set some minimum compatibility requirements for systems where there are known issues in prior versions:

```json
"relationships": {
  "systems": [{
    "id": "dnd5e",
    "compatibility": {
      "minimum": "2.1.0"
    }
  }, {
    "id": "pf2e",
    "compatibility": {
      "minimum": "5.6.0"
    }
  }]
}
```

A user is using this module without any issues on a system that is not in this list. How should this case be handled?

Without any additional manifest metadata I think at best we can report a compatibility warning because, technically, the module is not listed as 'supporting' the system in use. For a module to be free of such compatibility warnings though, the author must exhaustively list every system that the module is known compatible with. Maybe that's acceptable, but it doesn't feel ideal to me.

To reach a point where we can unambiguously mark a module as having a compatibility error due to a lack of a compatible system, I think we will require additional manifest metadata. Either some way to indicate the type of relationship in `relationships.systems`, or add support for systems to be listed under `relationships.requires` (though this would only be feasible for modules that require only 1 system.)

**Comment by JPMeehan** [comment]
I think a warning then would be useful, to use your example. A package update shows that the new minimum version for dnd5e is say D&D 2.4, but I've only got 2.3.1 installed. I would like a warning to that effect.

I *don't* think you need new data. I would

- Loop through relationships.systems to see which, if any, systems I have installed
- Compare the installed version of those systems to any incoming minimums
- Throw a warning (ideally batched together in one dialogue) for each system which will no longer meet minimum requirements.

**Comment by Fyorl** [comment]
We only need additional metadata if we want to report a compatibility error. But maybe I misunderstood what was being asked for. Reporting a warning is achievable with what we have already.

**Comment by JPMeehan** [comment]
To me the primary focus would be just looking at systems referenced in the module that the user has installed — I would want to know that if I update a module to the next version it will no longer be compatible with a system I have.

**Comment by Fyorl** [comment]
This has been implemented for the case of previewing compatibility with the next core software version. The more general implementation will have to wait for v12.

**Comment by JPMeehan** [comment]
Yeah, the core software version detection is what inspired the original request here.

**Comment by JPMeehan** [comment]
I think the recent update to dnd5e version 3.0 has highlighted the need for the inverse of this as well — even if I *do* put out a "max version" to prevent people from loading their world with an incompatible module (the surprise nature of 3.0 made that more difficult than normal), users may still update their system and lose access to modules they value using in worlds they care about. 

The v11.5 backups system does help this by making rollbacks easier, but more warnings around the consequences of a major version update would help this process and reduce user frustration.
