### ISSUE TITLE
Camera frame CSS can erroneously add buffer space if for non-16:9 resolutions

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#10118]
I feel like we had already resolved this, but I'm not able to locate any sign of a PR or issue for it previously so perhaps it just never got noted.

Example screenshot: 
![image](https://github.com/foundryvtt/foundryvtt/assets/26660743/bc26cf0b-ff21-4d6f-a749-8de69dbea469)

When a user's webcam is a resolution other than 16:9 the current CSS leaves a large buffer space around the camera. Setting the frame to `object-fit: cover;` resolves this.

Janky nath-css fix:
```
div#camera-views .video-container img.user-avatar, div#camera-views .video-container video.user-camera {
object-fit: cover;
}
```

**Comment by Fyorl** [comment]
Note that in my testing this appeared to only be an issue in Firefox, and it was particularly strange behaviour at that: It seemed to be assuming that the camera was vertically orientated. In Chrome it seemed to behave as though having `object-fit: cover` already (despite the user agent styling indicating otherwise). Regardless, explicitly supplying `object-fit: cover` seems to have unified the display across both browsers.
