### ISSUE TITLE
Pass update data to `Document._onUpdateDocuments`

### ISSUE THREAD

**Issue by Ethaks** [foundryvtt/foundryvtt#10235]
### User Experience

The current `Document._onUpdateDocuments` only has access to a) the updated `Document` instances, and b) the `context` (including e.g. the pack/parent), but neither the requested `updates` nor the `result` from the update response.
Having some kind of access to ideally the `result`, or in lieu of that at least the initially requested `updates` would be useful to inform the side effect handling of what changed so that it can react to that.

**Comment by aaclayton** [comment]
Closing this issue as "wontfix" because we have deprecated `Document._onUpdateDocuments` in favor of `Document._onUpdateOperation` which accepts arguments of `documents`, `operation`, and `user`. The `operation` parameter is of type `DatabaseUpdateOperation` and the differential data objects in the update are available as `operation.
