### ISSUE TITLE
If a document sheet is in middle of rendering, it will not close if the document is deleted.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10282]
### What happened?

Reported here: https://discord.com/channels/170995199584108546/1065764070680186930/1181668434333937695

If a document sheet is in middle of rendering, it will not close if the document is deleted.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

```js
const item = game.items.getName("test item");
await item.sheet._render(true);
item.sheet._state = Application.RENDER_STATES.RENDERING; // artificial mid render
item.delete();
```

Caused by `_onDelete()` not passing `force:true` to the `close()` call.

### What core version are you reporting this for?

Version 11

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This issue is resolved by the design of `ApplicationV2` which uses a Semaphore to enqueue render and close operations. An `Application#close` call which happens while the sheet is rendering will be processed after the render completes. Closing this issue as `wontfix` since it is addressed in App v2.
