### ISSUE TITLE
Improve documentation of Actor#getRollData and Item#getRollData to caution downstream implementations to be cautious about mutation.

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10392]
### User Experience

Currently, both Actor and Item return a direct reference to the system property in getRollData (it's conveniently a similar method for both).

```js
  /**
   * Prepare a data object which defines the data schema used by dice roll commands against this Actor
   * @returns {object}
   */
  getRollData() {
    return this.system;
  }
```

This is unsafe because if you call `super.getRollData`, then edit it - similar to how `context` gets manipulated in a sheet's `getData` - you would be directly modifying that document's `system` object. A safer way with few breakages would be to pass the destructured object, `{ ...this.system }`, instead - although I suspect there might ALSO be a bug here in the case that `system` is a class rather than an object, as is the case with a SystemDataModel.

**Comment by aaclayton** [comment]
cloning the system data model is not a free operation. The rationale for passing by reference here is that in most/many cases all you need to do with roll data is read values from it, you don't need to mutate in any way. If your use case for roll data requires mutation of that object, the caller of this method should assume responsibility for cloning it in order to be safely editable. 

Can you understand that rationale? We don't want to incur a costly cloning operation on every usage of `getRollData` when most usages do not require a copy. 

Certainly the documentation of this method should be updated both with regards to the typedef as well as with more clear instructions to API users that the returned data is not a copy and that it is their responsibility to clone it if you want to safely make modifications.

**Comment by JPMeehan** [comment]
Yeah I think improved documentation that if you override you shouldn't  call `super` would be a reasonable intermediate choice — although I'm wondering how costly the operation really is given that `actorSheet.getData` already clones things and that's called far more frequently than getRollData
