### ISSUE TITLE
Preserving secret condition for text

### ISSUE THREAD

**Issue by seb9393** [foundryvtt/foundryvtt#10450]
### User Experience

The 'secret condition' in the text of journals and item descriptions should remain 'secret' regardless of ownership untill the "reveal" button is pushed by the GM.

**Comment by aaclayton** [comment]
Unfortunately this is not easily possible. Once a player has ownership of a block of HTML, they have full ownership of that block. The editing experience is infeasible to support otherwise. If the desire is to have some sections of information which remain hidden even from the document owner, those need to be handled with a custom data model that implements that handling accordingly.
