### ISSUE TITLE
Improve clarity of walls layer toolclip text.

### ISSUE THREAD

**Issue by n0sec** [foundryvtt/foundryvtt#10467]
### What happened?

The tooltip displayed should say `Drag` on a wall point 

![image](https://github.com/foundryvtt/foundryvtt/assets/9609041/29def9f8-db43-4a6e-9f2c-60a10ba0d343)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1. Select the Wall Controls
2. Select and hover over the Rectangular Select Walls control
3. Tooltip displayed for _Move_ has instructions of "Drag"

### What core version are you reporting this for?

Version 11 (build 315)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'm afraid I'm not fully following. Could you share specifically what you feel the tooltip *should say*?

**Comment by n0sec** [comment]
Yeah sure this is based of a conversation in Discord with unsoluable

![Screenshot_20240302-080539.png](https://github.com/foundryvtt/foundryvtt/assets/9609041/930a2bf7-a0a3-4289-8e47-8adf33ac5507)

What he said was the reason for an issue. Does this help?

**Comment by krbz999** [comment]
"Move: Drag" -> "Move: Drag on a Wall point"

**Comment by unsoluble** [comment]
Wellll to muddy the waters a bit here (sorry), when I said that I was assuming that dragging on a point was _required_ in order to move the wall — it is not. On further experimentation with the tools, I think the only tooltip text that should be changed is the `Edit:` one (per Zhell above).

What could probably be ticketed separately is the drag-move behaviour for single segments: When you drag on the interior line of a single segment, it's currently treated as a drag from whichever endpoint you're closest to (and does a rotation), rather than what I think the UX expects, which would be to move the whole segment without rotation.

**Comment by Norc** [comment]
Made the change to the Rectangular Select Walls tooltip to read "EDIT: Double-click" instead of "EDIT: Double-click on a wall point" as suggested. This brings this tool's toolclip text in line with all the others in this group also.
