### ISSUE TITLE
Add movement cost measurements to Ruler

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10525]
- Added `Ruler#totalCost`.
- Added `RulerMeasurementSegment#cost`
- Added `RulerMeasurementSegment#cumulativeCost`.
- Added protected `_getCostFunction(): GridMeasurePathCostFunction | void`, which returns the cost function to be used for measurements.
- The `totalDistance` parameter of the `_getSegmentLabel` function has been deprecated. Use `this.totalDistance` instead.

**Comment by FloRad** [comment]
Would this work with systems where movement is based on dice rolls?

**Comment by FloRad** [comment]
Yes. One practical example, and probably the only (because it is a bit wierd) is SWADE. You can use your normal movement as expected but if you want to move extra distance you have to spend an action to run. To run you roll a die and add the result to your base movement speed.
IIRC Warhammer 40k does something similar when units charge into melee.

**Comment by dev7355608** [comment]
I see, so the movement cost isn't random: only the extra movement speed gain by the Run action is, right? I think this wouldn't be handled any different from a system like dnd5e: the Ruler would show the movement cost (which is independent of the movement speed of the token) and ideally color the path such that the users sees at which point along the path an action to dash/run would be necessary because the base movement would be exceeded.
