### ISSUE TITLE
Create a seperate user foundryvtt on linux systems

### ISSUE THREAD

**Issue by ChaoticEvilDM** [foundryvtt/foundryvtt#10575]
### Where did you find it, or where does it belong for requests?

Knowledge Base (https://foundryvtt.com/kb/)

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### What is wrong, in your opinion?

Issue: This will prevent people from attempting to place files into directories that might belong to other users and/or are not considered safe.

Solution:
```
useradd -m -s /bin/false foundryvtt
# For all further actions use this command to get into the user
sudo -u foundryvtt /bin/bash 
```

**Comment by aaclayton** [comment]
Recommending people to manage users in a particular way is well outside the scope of what we should be instructing users to do. I think we can trust that Linux users are competent enough to choose what user they want to run an application as and to configure permissions accordingly.

**Comment by alexdiste** [comment]
Could at least be add to FAQ or in documentation at same point because is actually a good practice and it make sense. Maybe as generic reccomendation

**Comment by ChrLau** [comment]
Here you write "Recommending people to manage users in a particular way is well outside the scope of what we should be instructing users to do." but in another issue you recommend installing PM2 instead of just using the distributions standard process manager (like Systemd).

Could please streamline your decisions on what you do/want do? Currently it looks pretty random.
Despite a service, which is reachable over network, creating it's own user is pretty much standard since ever.
