### ISSUE TITLE
Align {{selectOptions}} functionality with options preparation from createSelectInput and HTMLMultiSelectElement.

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#10616]
### User Experience

It would be very useful for the new `<multi-select>` element if the `select` handlebars helper could be used with an array or set as its selection. That would allow for this use case:
```javascript
<multi-select>
  {{#select selections}}
  <optgroup>
    <option>
    <option>
    <option>
  </optgroup>
  {{/select}}
</multi-select>
```
And have more than one of the options selected. This would even improve core templates such as the active effects template which currently has to manually select each option in a `{{#each}}` loop.

**Comment by JPMeehan** [comment]
Can't you just use selectOptions here?

**Comment by arbron** [comment]
> Can't you just use selectOptions here?

selectOptions doesn’t support more advanced organization like `<optgroup>`s or `<hr>`s, so if you want to use those you need select instead.

**Comment by JPMeehan** [comment]
I guess it depends on your structure — in SWADE we used an outer loop of an #each for the groups and then the #selectOptions representing the options within the group.

**Comment by aaclayton** [comment]
The path forward for this will be to improve `{{selectOptions}}` because the `{{select}}` helper is getting marked as deprecated. There are a bunch of new pathways towards creating this type of element in v12 like using automatic `{{formField}}` generation, or using the `HTMLMultiSelectElement.create()` method to build the HTML element. The latter of which can support optgroups.
