### ISSUE TITLE
bringToFront vs bringToTop

### ISSUE THREAD

**Issue by mouse0270** [foundryvtt/foundryvtt#10656]
### User Experience

I understand that things are expected to break between Application V1 and V2. However, I am not sure I fully understand why this function is a breaking change between the two application versions. I can't see how the function being named `bringToFront` provides anything additional over `bringToTop` as the functions essentially do the same thing. 

Its not really a bug, as modules can work around this in various ways such as `(sheet?.bringToTop ?? sheet.bringToFront)` but this seems like an odd thing to break. I am more curious as to why the function was renamed then to finding a solution as I already sort of have found one.

**Comment by aaclayton** [comment]
"Top" is a misnomer, since `top` in the application positioning context (CSS position units) means vertical position from the top of the screen, so "bring to top" suggests moving the application vertically. 

"Bring to Front" is a more accurate name for the behavior since the window is moved to the front of the rendered stack via its z-index.

**Comment by mouse0270** [comment]
At least there is a reason for the change.
