### ISSUE TITLE
Ensure that settings can be registered without an explicit `default` value, causing their default value to fallback to `null`.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt#10682]
Currently in v11, a setting registered as:
```js
game.settings.register(MODULE_ID, 'defaultless', {
  config: false,
  type: String,
  scope: "world",
});
```
would go through no problem, and return `undefined` when retrieved without being set. In v12, that same registration throws an error: 
![](https://i.imgur.com/QdQ3khT.png)
One of my modules checks against the presence of a `default` key in the setting registration data to know whether to include it in a 'reset all to default' operation. There are workarounds I could implement, but it would be convenient if we could continue to forgo explicit `deafult`s in settings.

**Comment by aaclayton** [comment]
Assigning to myself to have a discussion with the team and make a decision about what policy we want to enforce here.

**Comment by aaclayton** [comment]
@esheyw okay, so the verdict here is "sort of". 

I made some improvement which allows for settings to be registered without an explicit `default`, but in such cases the default is interpreted as `null` rather than `undefined`. The reason for this is because the `value` field of the `BaseSetting` document is declared as a JSON field which is required (does not allow `undefined`) and nullable (does allow `null`).

This means that:

1. Your example code will work without throwing an error BUT
2. The returned value from `game.settings.get` will be `null` rather than `undefined` in such cases

**Comment by esheyw** [comment]
Thats perfectly fine - as long as I can still do `if ('default' in game.settings.settings.get('etc')) { //... `, I'm happy. Thanks!
