### ISSUE TITLE
Scene loading stuck at 98%

### ISSUE THREAD

**Issue by VerduraDura** [foundryvtt/foundryvtt#10687]
### What happened?

When I open any world, even with all modules disabled and a simple scene, my loading bar gets stuck at 98%

![image](https://github.com/foundryvtt/foundryvtt/assets/43152933/be81f470-37c7-42f6-ab2e-aa81a57d13ca)

I have tried reinstalling the FoundryVTT app, and also disabling all modules and doing it in a test world. I have opened the DevTools and don't see any error messages in the console

Everything works as expected when I log in via Chrome/Firefox on the same PC (and connecting via internet) so I can work around the issue but it's very annoying not being able to use the Foundry app itself.

The last thing I did before this issue popped up was installing the module https://foundryvtt.com/packages/tokenmagic/. I have no idea if this caused the issue or not, but the timing was perfect. Right after installation (before enabling it) the issue started happening. I have uninstalled it but that didn't fix the isssue. I haven't recently updated any other modules/systems/foundry itself

If you need any other details I'll be happy to provide them. Thanks for the help!

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I haven't been able to reproduce the error on other PCs but it might be related to the module I mentioned

### What core version are you reporting this for?

Version 11 Build 315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
Sorry to hear that you are having this issue! I have a few suggestions for you.

In case anyone else comes across this issue, typically when a scene fails to load at 98%, the user is attempting to connect via Firefox and there is an invalid SVG file somewhere in the scene. Alternatively, this can happen when the network is experiencing severe problems. Neither of these appear to be your situation, however.

The first thing I would suggest is to make sure that you have plenty of spare hard drive space on your system drive, at least 5GB+. It may sound silly, by try restarting your computer also. 

Secondly, try deleting your Electron cache, which can be found here in Windows: `AppData\Roaming\Foundry Virtual Tabletop`. 

I don't believe that this is an issue with Foundry itself because we haven't received any other reports of this issue, so I suspect that this is something with your individual Foundry configuration, so I'm closing this issue. If you are still having difficulties after taking these steps, please reach out to us at `support@foundryvtt.com` and we would be happy to investigate further. 

Hope this helps!
