### ISSUE TITLE
Token placed with their center point on (or very close to) the boundary of a darkness source can sometimes see inside the darkness

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10839]
Originally reported by zhell9201: https://discord.com/channels/170995199584108546/1184176415139184731/1236234743478091776 https://discord.com/channels/170995199584108546/1184176415139184731/1236341918670258216

**Short Description of bug**: Rotating, short-burst movements along darkness source edges can in some instances reveal areas within the darkness.
**Simple steps to reproduce the bug**: Move a configured token along the edges of a darkness source, back and forth in short segments.
**Screenshots and/or console errors**:
(Attached recording has a pacman-shaped darkness source. The token rotates when moved and has a 180 degree vision angle.)

Addendum: There's a pixel perfect location on the border where the token is blinded, unable to see the *outside* but can clearly see the inside of the darkness.
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/86f3ba90-7d83-47fa-8bfa-29eb8b2aeb48)

**Comment by aaclayton** [comment]
I'm not sure whether we can reasonably do anything about this - at least at the moment. It is the same situation as what happens when the sight origin is exactly on a wall segment - you see both sides of the wall since that wall is excluded from the computation. 

We can continue to keep this as a known issue that might be somehow made better in the future but I don't see a direct path towards doing so right now.
