### ISSUE TITLE
Another player's cursor exceeding the bounds of the padding area causes the darkness to expand

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10930]
1. Create a new World
2. Add another Player user to the World
1. Create a 1000 x 1000 scene with 25% padding
2. Create a new PC and place it on the Scene
3. Select the newly-placed Token
4. Have the other player move their cursor around past the bounds of the Scene

https://github.com/foundryvtt/foundryvtt/assets/207433/b1e85b9b-c15a-4451-a61a-4c412d903279

**Comment by Norc** [comment]
I saw similar behavior in Testing 4 with measured templates. When a player (specifically) expands a measured template so that it extends into the padding, the same visual expansion of the padding area occurs. Not sure if this will be resolved with the same fix, or if I should log a spearate bug for it


https://github.com/foundryvtt/foundryvtt/assets/64667579/db5fdbe5-cb0c-4160-aa98-da2fca28474c
