### ISSUE TITLE
Full Text Search does not work: `DocumentCollection.getSearchableFields` returns incorrect field paths

### ISSUE THREAD

**Issue by admiralnlson** [foundryvtt/foundryvtt#10948]
### What happened?

Am using an actor data model containing `HTMLField`s with `textSearch: true`,
A Full Text Search in the Actors tab produces a console error, resulting in no Actors being filtered out.

This worked fine in v11, but does not appear to in v12(.323).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Use a system with an actor data model which contains `HTMLField`s with `textSearch: true`
  (castle-falkenstein system would be an example)
- Perform a Full Text Search on Actors which should filter some Actors out
=> no Actors are filtered out
=> a error console log is produced instead.

It seems to be because the `cleanQuery` function assumes the query is a string, when in practice it is also fed (DataModel) objects.
![image](https://github.com/foundryvtt/foundryvtt/assets/4472669/132ee672-1d45-40f9-b2bb-ff4c04b9b3e0)

### What core version are you reporting this for?

12.323

### Relevant log output

```shell
foundry.js:70621 Uncaught TypeError: query.trim is not a function
    at SearchFilter.cleanQuery (foundry.js:70621:18)
    at Actors.search (foundry.js:12211:49)
    at ActorDirectory._matchSearchEntries (foundry.js:72096:39)
    at ActorDirectory._onSearchFilter (foundry.js:72027:14)
    at foundry-esm.js:2685:18
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by admiralnlson** [comment]
In previous Core versions, for the castle-falkenstein system, the value of `textSearchFields` in `search({query= "", filters=[], exclude=[]})` was
```
Set(4)
0: "name"
1: "system.description"
2: "system.diary"
3: "system.hostNotes"
```
which is accurate.

But in 12.232, it appears to be:
```
Set(2)
0: "name"
1: "system"
```

I will stop the investigation here. I imagine this is all the information you need.

**Comment by Qaw** [comment]
I have exactly the same error with my system Cthulhu Hack.

**Comment by Khaali-dev** [comment]
For your schema, try to extend the foundry.abstract.TypeDataModel class instead of the foundry.abstract.DataModel.
That seem to solve the problem

**Comment by dev7355608** [comment]
*Originally reported by @farling42.*

### What happened?

In Foundry 12.324, foundry.js:12191  (DocumentCollection#getSearchableFields)

I have a StringField defined with "textSearch: true", but the field is never set up properly for searching. A search always find every single document in that particular collection.

The following line is removing the first element from the path, thus the path is never valid, and so the function uses "system" as the searchPath. This actually results in ALL the documents matching the pattern (an error is reported at a lower level, presumably because "system" isn't a string).
```
const [, ...path] = this.fieldPath.split(".");
```

Not stripping the first element from fieldPath works properly (since fieldPath doesn't include "system").
```
const path = this.fieldPath.split(".");
```

This is working correctly in Foundry 11.325.

In Foundry 11.325 it seems that `fieldPath` is now returning the path including the leading "system." which wasn't occurring in 11.324.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Set an HTMLField to have "textSearch: true".
Use "Full Text Search" to search for a document with specific text in that field.
Observe that ALL the documents are marked as matching

### What core version are you reporting this for?

12.324

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
Originally reported by celestian: https://discord.com/channels/170995199584108546/1184176415139184731/1249063200721469621

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable)**: windows native/electron
**Short Description of bug**: DocumentCollection.getSearchableFields does not return the correct fields for full search of 'text.content' instead it returns 'content'.
*Note: I also noticed that the doc data for compendiums do not contain text.content. It would be extremely nice to also include it for compendiums and adjust getSearchableFields to also add it as a field. Currently compendiums only get a name field.*
**Simple steps to reproduce the bug**: Toggle full search,  enter value in search field of text in page. Will not find it.
**Screenshots and/or console errors**:
