### ISSUE TITLE
Avoid double-counting of package warnings for deprecated fields

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/foundryvtt#10989]
### User Experience

Currently, when the foundry setup screen opens, a lot of package warnings appear - and many of them are warnings like these:

> The "pf2E Extempore Effects" module's manifest contained the following unknown keys: "manifestPlusVersion"

> The "PF2e Animation Macros" module's manifest contained the following unknown keys: "manifestPlusVersion"

> The "Sequencer" module's manifest contained the following unknown keys: "manifestPlusVersion"

A lot of modules contain this specific field, `manifestPlusVersion`, and for a good reason - it's an unofficial community-developed specification, defined here - https://foundryvtt.wiki/en/development/manifest-plus - and it's not a field that anyone is planning to remove, so the warnings aren't being helpful.

Even though it's unofficial, I think it's popular enough that it should be ignored and treated as an acceptable field.  In my own installation, these account for 45% of the package warnings I see.  (the rest of the warnings are almost all about deprecated fields)

**Comment by Fyorl** [comment]
Supplemental manifest fields should go under `flags`.

**Comment by shemetz** [comment]
Yeah, changing Manifest+ to work like that would be a good solution too.  I'll bring it up in [its discord channel](https://discord.com/channels/732325252788387980/755620260895391754).

**Comment by Fyorl** [comment]
I'm repurposing this issue to relate to the double-counting of manifest warnings in some cases. For the specific case of the `manifestPlusVersion` field we would rather not maintain a list of 'blessed-but-non-standard' manifest keys. The appropriate place for these fields is under `flags`, where they will not generate any warnings. We will also implement #11066 which will suppress warnings for users that do not opt-into it, so that developers can see and address warnings in their own packages but not cause any confusion for end users.
