### ISSUE TITLE
Requests to download packages hosted on gitlab can fail with a 406 Not Acceptable

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11000]
Originally reported by freeze2689 https://discord.com/channels/170995199584108546/1184176415139184731/1243160678441684992

**ALL MODULES DISABLED?** (N/A)
**OS, Hosting, Browser (if applicable)**: NodeJS
**Short Description of bug**: When trying to install a module from a gitlab repo it errors  on downloading. Door-Sounds is confirmed to install properly in v11 from the same manifest.
**Simple steps to reproduce the bug**:  try installing: `https://gitlab.com/henry4k/foundryvtt-lang-de/-/raw/master/module.json` or `https://gitlab.com/Freeze020/door-sounds/-/raw/main/module.json`
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/b57ebb73-3df5-41dc-887d-2d0e66f6db20)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/28d0279e-7762-445f-b375-a143f2b09d43)

**Comment by Fyorl** [comment]
Must be related to the change to using native `fetch` rather than the `node-fetch` package. I don't know why the native `fetch` would add strange `Accept` headers that gitlab's server can't fulfil. I suppose it's possible that gitlab is being badly-behaved.

**Comment by Freeze023** [comment]
There are modules that also use gitlab but dont have issues. 
Such as: https://gitlab.com/tposney/midi-qol

Their method of building the release completely different (and completely beyond my understanding), maybe that is what is preventing some issue that the failing modules dont prevent?

**Comment by sakulstra** [comment]
just bought foundry and trying to follow a tutorial, facing this issue on quite a huge amount of the recommended modules as well.

**Comment by aaclayton** [comment]
@Fyorl if these `Accept` headers are not necessary, maybe we can explicitly configure the headers of our `fetch` request to omit them?

**Comment by davesturtevant** [comment]
I think I'm having this same issue with installing https://gitlab.com/asacolips-projects/foundry-mods/simple-worldbuilding-plus/raw/master/module.json .

**Comment by drewg13** [comment]
I have to assume someone else has found this, but I'll put down what I figured out trying to install DSN on my Oracle dev server under V12.

I tried the usual install method and experienced the same error referenced in the original issue.  Since my server is headless Ubuntu, I just resolved to do it the command-line way.

Trying to grab just the latest build zip, I went to the latest `module.json` and grabbed the download URL:
`https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/jobs/artifacts/4.6.10/raw/dist/dice-so-nice.zip?job=build`

If you plug that URL into a regular browser, you get a ~6MB zip file, as expected, but I can't do that on my headless server.

If you do a simple `curl -o dsn.zip https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/jobs/artifacts/4.6.10/raw/dist/dice-so-nice.zip?job=build`, you get a a 170b "zip" file which is actually an HTML file:
```html
<html><body>You are being <a href="https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/jobs/6144026161/artifacts/raw/dist/dice-so-nice.zip">redirecte
d</a>.</body></html>
```
It seems like this HTML is likely causing the parser to barf because it isn't the expected zip MIME type.

If you run `curl -i https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/jobs/artifacts/4.6.10/raw/dist/dice-so-nice.zip?job=build`, it pops a `302 Found` result with that redirected URL as the `location`.

If you redo your `curl` command, but using the URL returned in the HTML file instead, you get the expected ~6MB zip file and everything works fine from there.

Perhaps, like `curl`, the native `fetch` method does not properly handle the `302 Found`, while the old `node-fetch` did.  In contrast, the working MIDIQoL gitlab repo gives a `200 OK` response to the download URL in the latest `module.json`, which seems to be properly handled by both fetch methods.

**Comment by drewg13** [comment]
Never mind, I should have checked the module from the original issue, none of this applies to that module, but it still errors.

**Comment by Qaw** [comment]
Same issue for anarchy system ([anarchy](https://gitlab.com/vincent.vandeme/anarchy))

**Comment by VincentVk9373** [comment]
> Same issue for anarchy system ([anarchy](https://gitlab.com/vincent.vandeme/anarchy))

I use the simple Release feature from gitlab, it is just a zip of the repository, no transformation.
Looking forward to the next release where it is fixed
