### ISSUE TITLE
[Epic] Allow folder organization inside of Compendium packs

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#1109]
# High Level
Add support for organizing content inside of Compendium Packs via Folders

## Requirements
* Should operate like other Foundry folders (3 deep nesting, expand / collapse, subfolder searching)
* Should import and export in the same Folder structure
* Should be reflected in the Index

## Related Issues
* https://github.com/foundryvtt/foundryvtt/issues/8785
* https://github.com/foundryvtt/foundryvtt/issues/8786
* https://github.com/foundryvtt/foundryvtt/issues/8787
* https://github.com/foundryvtt/foundryvtt/issues/8788
* https://github.com/foundryvtt/foundryvtt/issues/8789
* https://github.com/foundryvtt/foundryvtt/issues/8902
* https://github.com/foundryvtt/foundryvtt/issues/8903
* https://github.com/foundryvtt/foundryvtt/issues/8918
* https://github.com/foundryvtt/foundryvtt/issues/8938
* https://github.com/foundryvtt/foundryvtt/issues/8790

**Comment by anathemamask** [comment]
Investigation of this change turned out that it would benefit most from an approach after examining a database framework overhaul. This is a change that, to do properly, should be done at that point and not before. 

It will be disappointing for some that folders inside compendiums is not a viable candidate to pursue in v10, but in the end I think that it would be more appreciated if we do this as a good, solid ground-up implementation rather than something we have to use hammers and anvils to fit into the old framework.
