### ISSUE TITLE
The cause of an error is not displayed in the console in the Electron client

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11176]
Originally reported by zhell9201: https://discord.com/channels/170995199584108546/1184176415139184731/1249322869301972993

**OS, Hosting, Browser (if applicable):** Electron 
**Short Description of bug**: Error handling in v12 obscures the location of the error in some cases.
**Simple steps to reproduce the bug**: Toss in a `throw new Error("TEST")` in a system implementation of `Combat#setupTurns`.
**Screenshots and/or console errors**: v11 (pf1) and v12 for comparison.

V11:
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/954e8cc5-a432-4f11-871c-28f48bfcfd1e)

V12:
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/88e63868-f3e1-4b6e-9b86-116c139b361f)

![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/f6ecb192-8d16-4970-ae3a-5506933843fa)

**Comment by Fyorl** [comment]
Nothing we can do here without an electron version bump. Electron 29 corresponds to Chrome 122 and `cause` is only included in stack traces as of [Chrome 125](https://developer.chrome.com/blog/new-in-devtools-125#error-cause) (and Firefox 91).

**Comment by Fyorl** [comment]
We don't want to risk regressing the areas that our use of `cause` was intended to fix, and we cannot update the electron dependency during stable, but this issue will fix itself in v13. In the meantime, users will have to take the extra step of reproducing the error in a browser if they weren't already using one in order to retrieve the full details.
