### ISSUE TITLE
Default Drawing Configuration is unexpectedly shared between worlds and users

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#11212]
### What happened?

Based on our current documentation, my understanding is that Default Drawing Configuration is stored on a per-user basis, but this doesn't seem to be the case in 11.315 or 12.327. Instead, a single, shared Default Drawing Configuration seems to be stored for every world and every user?

Either our docs need to be updated quickly to match, or the way that the Default Drawing Configuration settings needs to be changed. I'm not sure which is the correct path.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create two different worlds, each with a GM an a Trusted Player
2. Open Default Drawing Configuration dialog for each user in each world
- Note that the initial default Line Opacity configuration value is 1 for all of them
- Expected: the unchanged values are still 1 for the unchanged users / worlds
3. Set the Default Line Opacity configuration value to 0.8
4. Open Default Drawing Configuration dialog for each user in each world again
- Note that the initial default Line Opacity configuration value is 0.8 for all of them
- Expected: the unchanged values are still 1 for the unchanged users / worlds

### What core version are you reporting this for?

12.327

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
There are currently only two setting scopes:

1. Client-level settings which are stored in the browser and therefore shared across any games you play using that same browser.
2. World-level settings which are stored in the world database, but apply to all users within the world.

We do not currently support a database-stored world-level setting on a per-user basis. The issue for that is https://github.com/foundryvtt/foundryvtt/issues/4804

Default Drawing config works the way it does because it is important for each player to have a *different* default drawing configuration rather than having all players have the *same* default drawing configuration. This means that a client-setting is required here given the two options available. A consequence of that is that default drawing configuration would be shared across worlds.

This could be improved in the future if we implement #4804 but otherwise this is an intentional choice.
