### ISSUE TITLE
Make secret text GM Only unless revealed even in items!

### ISSUE THREAD

**Issue by jacksands** [foundryvtt/foundryvtt#11436]
### User Experience

The text Block Secret can be used on items, but as soon it is add to a sheet it became revealed... it fails its purpose... 

Please make this type of text controlled by GM only.

![image](https://github.com/foundryvtt/foundryvtt/assets/7229143/12658a47-1203-4a51-b467-39ee289028b7)

**Comment by aaclayton** [comment]
It's not practical to mix owner-visible and owner-managed content with gm-only and gm-managed content within the same HTMLField. The recommendation is for the game system to implement two separate description fields, one that is for the item owner and one that is GM only. That is how other game systems are approaching this problem because the logistical or feasibility issues of co-mingling this content in a single HTML description are intractable.
