### ISSUE TITLE
Cannot return to setup from world homepage if there is no administrator password

### ISSUE THREAD

**Issue by morgan613** [foundryvtt/foundryvtt#11433]
### What happened?

If you don't have an administrator password and you launch a world, you cannot return to set up page to update software and modules and such. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Have no administrator password.
2. Launch a world
3. Try to get back to set up

### What core version are you reporting this for?

Version 12 Build 328

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by thre-z** [comment]
This is intentional, otherwise any user including your players could return to setup shutting down the world at any time. They would then have the ability to delete worlds, add modules, etc. 

See: https://foundryvtt.com/article/reset-admin-password/

If you don't have an admin password set, you'll need to login to the world as GM and return to setup from there. If you'd like any more help for this kind of stuff please head over to the Discord server for troubleshooting.

**Comment by morgan613** [comment]
Ah I see, thank you for your quick answer and explanation.
