### ISSUE TITLE
Scene with large background image is black on Firefox MacOS

### ISSUE THREAD

**Issue by justinross** [foundryvtt/foundryvtt#11437]
### What happened?

I have a scene with a background image set of 9046x12050. This loads fine (albeit slow-ish, obviously) on Windows Firefox and Safari on MacOS, but Firefox MacOS (Apple Silicon, M3) just renders a black background.

I found #9957, but that didn't seem quite the same, and appears to be resolved/closed.

**_Screenshot in Firefox MacOS:_**
<img width="1512" alt="image" src="https://github.com/foundryvtt/foundryvtt/assets/1120106/7127da01-6d6b-4fcc-9186-f8c0dc5c1502">

**_Screenshot in Firefox Windows:_**
![image](https://github.com/foundryvtt/foundryvtt/assets/1120106/84e1a1ee-e943-414e-8cd0-dd494442be5d)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Set a large background image on a scene (not sure where the cutoff is)
2. Try to view the scene in Firefox on MacOS
3. See black background instead of selected image

### What core version are you reporting this for?

V12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by thre-z** [comment]
This can often be caused by using images that are larger than the Max Texture Size of the client, which may be different for each user based on hardware and browser. You can see what your Max Texture Size for the current client is by going into the Settings Tab and clicking the Support & Issues button. It will be a field listed there. 

This kind of issue is best troubleshooted in the official Discord where we can go take a look at things, or you can reach out via the Contact Us form on the foundryvtt.com website.

**Comment by justinross** [comment]
Ah, roger that. Yeah, looks like mine is 8192 on Mac Firefox, and 16384 on Windows Firefox (which is wild, considering how much more powerful my macbook is than my Windows PC). Guess I'll just stick with Safari on my MBP. Sounds like it's a hard-coded limit in Firefox MacOS due to upstream libraries in use, or something. 

Thanks!
