### ISSUE TITLE
Allow GMs to choose whether or not overhead tiles fade by hovering the cursor over them

### ISSUE THREAD

**Issue by TheMapGoblin** [foundryvtt/foundryvtt#11448]
### User Experience

This new feature would be great IF GMs could choose whether or not to turn it on. Forcing it on everyone makes people like me, who set up wall images as overhead tiles, unable to set up walls correctly because they keep disappearing.

**Comment by aaclayton** [comment]
You need to make sure the **Occlusion Mode** for your tile is set to **None (Always Visible)**, then it will not fade in this way. Please confirm whether this resolves your issue?

**Comment by Iankid** [comment]
If this was the intention, it's not what's happening, I made a similar feature request not too long essentially covering the same issue #11462

**Comment by aaclayton** [comment]
I resolved an unexpected UX here such Tiles with occlusion mode of "NONE" will not have hover-fade behavior.

**Comment by WBHarry** [comment]
Necroing this,

The way I do roofs has been worsened by the tile fading feature. I don't typically use vision blocking walls on maps in a city or village with a lot of roofed buildings, because I think it's much more important to give the players an actual view and understanding of what's around them instead of everything just being black with cut off sight lines. Instead I just use movement blocking walls.

I used to set my roofs to Fade when someone walked under them which worked great. If I do that now players hovering just see under them since the Hover-Fade is baked into the `Fade (Entire Tile)` option - forcing me to use None option and then manually hiding the roof when they walked under.

What would solve this for me would be having the Hover-Fade behavior optional like a checkbox. 🙏

**Comment by aaclayton** [comment]
Hey @WBHarry can you create a new issue with the same comment as what you just posted? We can consider it but I'd like to leave this closed issue where it was in the V12 milestone.

**Comment by WBHarry** [comment]
@aaclayton Done (https://github.com/foundryvtt/foundryvtt/issues/11633). Thanks for the consideration.
