### ISSUE TITLE
ApplicationV2 windows are not added to ui.windows

### ISSUE THREAD

**Issue by CodaBool** [foundryvtt/foundryvtt#11504]
### What happened?

It's possible there is a new location where V2 windows are stored. 

This happens for the Regions window but I'm also seeing this for my module when I create a new class
```js
class X extends HandlebarsApplicationMixin(ApplicationV2) {
}
```
It used to show in ui.windows but since using ApplicationV2 it no longer shows there. It only shows in ui.activeWindow but I don't currently have a way to interact with it if it's not active.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open Regions window
2. check value of `ui.windows`

### What core version are you reporting this for?

12.329

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Intentional, to differentiate between AppV1s and AppV2s. The go-forward location where appv2 instances are found is `foundry.applications.instances`. For the time being if you want dual support for both v1 and v2 you'll need to look in both `ui.windows` AND `foundry.applications.instances` for all possible apps. This is a temporary pain that will go away as eventually everything will be appv2
