### ISSUE TITLE
ActiveEffect._applyLegacy can set values to `undefined`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#11527]
### What happened?

It's common to have a property on an actor or item that is instantiated in `prepareBaseData` and then fully realised in `prepareDerivedData` and does not live in the data model. For example, a value of `defense = 0` in base, which then derives its total from items, effects, etc.

If such an active effect uses `CONST.ACTIVE_EFFECT_MODES.DOWNGRADE` with a value of 999 (or anything that is higher than what it would currently be), no change is performed, which is correct so far.

However, this means `_applyLegacy` merges an object with `{defense: undefined}`, which overrides the value entirely regardless.

![image](https://github.com/user-attachments/assets/4a5f75be-0710-4d25-ad2c-0903fda830aa)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

In the dnd5e system, create an actor with an effect with key `system.attributes.ac.cover`, mode `Downgrade`, and value `99999`. Log the `system.attributes.ac.cover` value (it will be `undefined` instead of `0`).

### What core version are you reporting this for?

12.330

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Comment from @tposney

### What happened?

If an active effect with mode upgrade/downgrade fails to upgrade/downgrade the target field (i.e. it is already bigger/less than the upgrade value) the field is then set to undefined

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create an active effect, e.g.
system.abilities.str.value upgrade 4 on an actor whose strength is already 10
Note that the value gets set to undefined.

This will occur on all upgrades that fail to apply

The culprit is
```js
  _applyUpgrade(actor, change, current, delta, changes) {
    let update;
    const ct = foundry.utils.getType(current);
    switch ( ct ) {
      case "boolean":
      case "number":
        if ( (change.mode === CONST.ACTIVE_EFFECT_MODES.UPGRADE) && (delta > current) ) update = delta;
        else if ( (change.mode === CONST.ACTIVE_EFFECT_MODES.DOWNGRADE) && (delta < current) ) update = delta;
        break;
    }
    changes[change.key] = update;
  }
```
If the field type is not boolean or number OR if current > delta (for upgrades) or current < delta for downgrades update will be undefined and the returned change will be changes[change.key] = undefined which is then applied by the effect application code.
I'd suggest either make no changes to changes[change.key] if update is undefined 
```js
if (update !== undefined) changes[change.key] = update;
```
or changing
```js 
let update
```
to
```js
let update = current;
```


### What core version are you reporting this for?

version 12 331

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled
