### ISSUE TITLE
Add support for 3D grid coordinates

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11588]
- 3D point coordinates: `{x, y, z}`
- 3D offset coordinates: `{i, j, k}`
- 3D hexagonal cube coordinates: `{q, r, s, k}`
- 3D grid spaces in hexagonal grids are hexagonal prisms.
- Working with 2D coordinates continues to work as before: no deprecation or breaking changes. Grid functions return 2D coordinates given 2D coordinates, and 3D coordinates given 3D coordinates (if they support 3D coordinates).
- Added `HexagonalGrid#diagonals`, which determines the rule for diagonal steps in the hexagonal grid. Diagonal steps can only occur while moving vertically up or down; so this property has no effect when working with 2D coordinates.
- Renamed the setting *"Square Grid Diagonals"* to *"Grid Diagonals"* and updated the hint accordingly, since this setting now also determines the diagonal rule in hexagonal grids.

**Comment by caewok** [comment]
In case it is useful, I have long used a projection to estimate movement in a 3d grid. That allows the square grid diagonal rules to work as expected. The advantage is that you can reuse your 2d movement functions (particularly for square grids with all the diagonal rules) instead of rewriting them for 3d.

The basic idea is to think of elevation movement as forming a right triangle. If you move horizontally 4 spaces and up two spaces, this forms a right triangle where the hypotenuse is the actual movement in 3d, with distance sqrt(4^2 + 2^2). Now "tip over" the triangle so it lays flat on the 2d canvas. (Project the 3d coordinates to the 2d canvas to make the 2d distance one axis and elevation the second axis.) The grid squares under the hypotenuse tell you how many grid squares are encountered and you can apply the 2d grid movement rules accordingly. 

A couple tricks help:
1. For square grids, align the tipped over triangle so the 2d distance axis aligns with the `x` axis. Elevation should then align with the `y` axis. This means that elevation-only moves will move vertically on the 2d canvas and be treated as not-diagonal. 
2. For hex grids, align the tipped over triangle either vertically or rotate it 90º (swap x and y) based on whether it is a row hex or column hex. Row hexes use elevation as the x axis; column hexes use elevation as the y axis. 

For a cost function when measuring movement, you will still need to get all the 3d grid points and pass each segment to the cost function. But using the projection trick it is possible to figure out what those would be.

**Comment by dev7355608** [comment]
The 3D distance functions are the extensions of the 2D distance functions.

3D square grid:
- Equidistant: `s + d1 + d2`
- Exact: `s + SQRT2 * d1 + SQRT3 * d2`
- Approximate: `s + 1.5 * d1 + 1.75 * d2`
- Rectilinear / Illegal: `s + 2 * d1 + 3 * d2`
- Alternating 1/2/1: `s + floor(1.5 * d1 + 1.75 * d2)`
- Alternating 2/1/2: `s + floor(1.5 * d1 + 1.75 * d2 + 0.5)`

where `s` is the number of straight moves, `d1` the number of "normal" diagonals, and `d2` is the number of "double" diagonals.

3D hexagonal grid:
- Equidistant: `s + d`
- Exact: `s + SQRT2 * d`
- Approximate: `s + 1.5 * d`
- Rectilinear / Illegal: `s + 2 * d`
- Alternating 1/2/1: `s + floor(1.5 * d1)`
- Alternating 2/1/2: `s + floor(1.5 * d1 + 0.5)`

where `s` is the number of straight moves and `d` the number of diagonals.
