### ISSUE TITLE
Allow Text from Chat to be copied

### ISSUE THREAD

**Issue by brunocalado** [foundryvtt/foundryvtt#11712]
### User Experience

After roll a table I can't select the text in the chat to copy. Please allow this to happen.
![image](https://github.com/user-attachments/assets/9d926e27-2560-49f9-891f-afad9a0149e2)

**Comment by aaclayton** [comment]
@Fyorl another one for you to take a look at here. For regular chat messages we explicitly set:
```css
.chat-message .message-content {
    user-select: text;
}
```
So that the message text can be selected. We probably need to handle this for certain things specifically like Roll Table descriptions and results. I understand that we don't want the entirety of chat messages being selectable, but we might need a targeted rule here.
