### ISSUE TITLE
Request: Allow BooleanField to be nullable

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11779]
### User Experience

Currently BooleanField can not be nullable, it simply fails validation.

It would allow the field to be used for a trinary state if it allowed nulling.

All this requires is adding null checks, something like the following:
```js
_cast(value) {
  if (this.nullable) {
    if (value === null || value === "null" || value === "") return null;
  }
  if (value === "true") return true;
  if (typeof value === "object") return false;
  return Boolean(value);
}

_validateType(value) {
  if (this.nullable && value === null) return;
  if (typeof value !== "boolean") throw new Error("must be a boolean or null");
}
```

I can trivially create my own datafield for this, but it'd be cool if it was in core.

I guess the bigger challenge is the apply change behaviour, and form input generation (checkboxes do support indeterminate state).

**Comment by mkahvi** [comment]
I was brought into attention of _validateSpecial() which supposedly would work for this, so not sure why it isn't in my case.

Part of the issue may be how FormDataExtended handles boolean typed fields with value set to something resembling a null (e.g. radio buttons).

**Comment by aaclayton** [comment]
I think the field itself already supports this behavior:
```js
const f = new foundry.data.fields.BooleanField({nullable: true});
f.clean(true) // true
f.clean(false) // false
f.clean(null) // null
```
Probably there are some downstream workflows which might not expect this. The UI of an `<input type="checkbox">` is inherently binary and would really only support a true/false. You would need some other sort of input in order to support three data states. Or you could put some post-processing in your app that re-casts `false` as `null` if that is the behavior you would want to assume.

**Comment by mkahvi** [comment]
I had radio buttons with the one representing null without dtype to avoid early casting, but it always ended up as false once it got committed to the datamodel.
