### ISSUE TITLE
Built-In Backup Functionality

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#2912]
Originally in GitLab by @irishbandit7

Since the launch announcement placed importance on backing up your data, an integrated backup function for Worlds would be nice. A button to just zip up the world folder and chuck it into a /backups directory seems like it'd do.

**Comment by cs96and** [comment]
Personally, I think Foundry should automatically create a backup before doing any sort of migration.  

There have already been a number of reports on Reddit about people upgrading to v10 without creating a backup, and are no unable to return to v9.  Although people should be doing their own backups, it would be nice to provide some sort of way to revert to a previous version due to user error.

**Comment by sladecraven** [comment]
I vote for this feature. At least a minimal **BOLD** window  asking users to backup their worlds before upgrading, with 2 buttons "Yes my data are backuped" and "No, abort this update, I will retry it when my worlds backup will be done".
Seems easy and will oblige people to validate their choice.

**Comment by Sasmira** [comment]
I vote for this feature.

**Comment by Cimeryl** [comment]
This would be great, i vote for this

**Comment by Qaw** [comment]
I vote also for it !
I see something like this :
- Having a path in core config to configure a save directory
- Having a button to click and copy all the data folder in this directory, and save info like a timestamp.
- When upgrading the version of Foundry, check the timestamp and display a Warning : 
"You have no backup, are you sure you want to upgrade ?"
or "Your backup is 1 month old, are you sure you want to upgrade ?"
Perhaps storing also information about the version of Foundry of the backup.
- And a button somewhere to restore a backup would be fine.

I agree that it's just some copy/paste of folders that everyone could do ... but you know that the problem is often between the chair and the keyboard ;)

**Comment by Kyllianm85** [comment]
A must have feature 👍

**Comment by DarKDinDoN** [comment]
Must have

**Comment by rlepennec** [comment]
A must have !

**Comment by ccjmk** [comment]
I would like an automatic backup on version updates, and if for some reason that backup fails a BIG FAT window asking the user to backup manually, with a "I already backed up my data manually" to override a disabled "Continue".

**Comment by aaclayton** [comment]
Comment from @bithir

### User Experience

In order to save sanity on people (module, system and foundry support staff) - I would like to suggest when installing a new version of Foundry, that if there exist data in the default data-path, to either automatically take a backup (preferred), or prompt the user to make a manual backup (people will not read such a prompt).

**Comment by PatrickBauer** [comment]
We've discussed this in the German Foundry discord too. Multiple users came to us with problems after updates, not having a backup (mainly because the don't even know they need one how to do it). Not everyone is using Discord and reads the warnings that are put there.


I agree with others. At least a dialog before updating with a big big warning and links to backup tutorials should be provided.

In terms of built in backups I propose a simple first step. Add export / backup buttons to worlds inside the setup window and on clicking those buttons, simply *stream* a zip version of the world (either without assets or with the option to include them) as a download. It's not even needed to cache this backup to the hard drive first.

**Comment by alexdiste** [comment]
I vote for this

**Comment by ian612** [comment]
I think this continues to be an issue for a large portion of users. It would be very nice if there was a function that, when migrating worlds to new Foundry versions, would just copy the world data to a zip folder automatically.

You could build in restore functionality into the next iteration of V11, something to automatically detect the presence of a backup zip folder and provide a mechanism to overwrite world data with what's in it. Then v12 could add the functionality to create the aforementioned backups before world data migration. If a user then finds their stuff is all broken they can downgrade their install back to v11 and restore from the backup files without any manual fiddling.

I know it's not particularly flashy but it would make a lot of more casual users' experience a lot better.

**Comment by ian612** [comment]
As an addendum, if whatever implements this could also be used by system developers to perform automatic backups it would probably be handy. Say if, for example, their system requires migration for changes to its data model.

**Comment by cs96and** [comment]
I'd like to see this in the list of things to vote for in v12.

**Comment by theripper93** [comment]
In my own server, i added archiver to the node_modules, then i have this backend modification in the `setup.mjs` `handlePost`

```js
                case "backupWorlds":
                    const folderPath = global.paths.data + "/worlds/";
                    const archive = archiver('zip', {zlib: {level: 9}});
                    a.set('Content-Disposition', 'attachment; filename=worlds.zip');
                    a.set('Content-Type', 'application/zip');
                    a.attachment('worlds.zip')
                    archive.pipe(a);
                    archive.directory(folderPath, false);
                    await archive.finalize();
                    break;
```

and i use this client side to perform quick backups

```js
fetch(foundry.utils.getRoute(game.view), {
    method: "POST",
    headers: {"Content-Type": "application/json"},
    body: JSON.stringify({action: "backupWorlds"})
  },)
.then(response => { response.blob()})
.then(blob => {
const link = document.createElement('a');
link.href = URL.createObjectURL(blob);
link.download = 'worlds.zip';
link.click();
})
```

while this is very much quick and dirty, and i do not endorse modifying the backend for anyone reading this, it gets the job done

**Comment by ian612** [comment]
I support the idea of adding it to the feature vote, but even if it doesn’t get voted for I think it’d be a good addition. It’d be a huge QoL improvement, especially for casual users who aren’t used to having to go and manipulate files in their AppData folder before updating software.

**Comment by ian612** [comment]
Thanks for implementing this in 11.5!
