### ISSUE TITLE
Provide a better tool for modeling sunlight in outdoor areas as a more targeted alternative to global illumination for mixed indoor/outdoor areas.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#3078]
## This Epic Will Be Solved By
- #10388 
- #10389 
- #10390

## Original Request Below

Originally in GitLab by @Adriannom

Currently, there are very poor workarounds for doing outside lighting when a scene has both inside areas and an outside area. Lighting only works correctly if the scene is either inside-only or outside-only.

The sunlight tool would allow you to draw an origin and a line. The origin would tell you which part of the scene to flood with sunlight (blocked by closed circuits of walls) while the line would indicate the direction and length of shadows (gentle shadows that exist even in bright vision, just to give an extra feel with the lighting).

Note that the sunlight origin isn't the origin in the same way that normal light sources are, it only indicates which areas count as outside. Perhaps there's a better word than origin?

Any sunlight sources are also turned off when the scene is changed to night time. A good counterpart to the sunlight tool would be a moonlight tool, which allows dim light to be designated in the same way, only at night.

Extra points for giving an API that @tposney can use in the About-time mod.

**Comment by Feu-Secret** [comment]
Currently, the darkness level is applied on the whole scene. We should allow at minimum region or texture masking to exclude some parts of the map. We should also explore non-uniform level masking (with a texture height method or other solutions => scene regions)

**Comment by caewok** [comment]
My [Elevated Vision module](https://github.com/caewok/fvtt-elevated-vision) allows the user to configure an ambient light as a "sun/moon." It treats the light as directional, and allows the user to assign it azimuth and elevation angle (above the horizon). Shadows are directional—meaning the shadows are parallel—as would be the case for an infinitely distant light source. Alternatively, my [Light Mask module](https://github.com/caewok/fvtt-light-mask) has long allowed the user to define a light without a bounding polygon, which can give a simliar effect to that of Elevated Vision's sun/moon without all the fancy shadows. 

I mention this so the Foundry devs and users can check out that user interface and see its benefits and limitations. I also mention it so you understand where I am coming from when I say I have thought about this issue of sunlight vs indoor lighting for awhile. 

Some observations:

1. I dislike the idea of using textures/drawings/tiles to mask light arbitrarily based on only the shape of the mask. It is disconnected from the physical reality of the scene, and so ultimately seems to me to be a stop-gap solution that stands in the way of a more elegant physical solution. From a user perspective, the user should be able to create a room, add a roof, and expect Foundry to understand whether light from outside can penetrate into the room. Drawings and tiles to define light areas is just an additional step that, because it has no physical basis, is ultimately confusing. 

2. It is possible to set lights in Foundry to represent the sun/moon/other large light sources. You can do it in base Foundry by giving a light a very large radius. Foundry could improve on this by allowing lights without boundaries (easy) or do something like Elevated Vision does for a more sophisticated physical light source at a distance. My claim, here, is that it would be better to physically model lights rather than try to arbitrarily set tokens to have "outdoor" and "indoor" vision.

3. Large outdoor lights (2) work well, except that they still create harsh shadows because there is no ambient light modeling. I recommend giving lights a defined ambient property, adjustable by users, that substitutes for more complex ray shading that we definitely don't want to do. If a pixel in the scene can be reached (indirectly) by the light, it gets at least ambient light even if shadowed. Modeling ambient light correctly would likely be too hard, but it should be possible to cheat a bit to guess whether a given pixel is inside/outside compared to a sun/moon light source. The trick is to figure out a simple way to determine if a given pixel is contained by walls such that it cannot reach the large light source. For example, Elevated Vision constructs a scene graph from the walls so it can know how to fill elevation in a given area bounded by walls. Something like that could tell you if a given point is within the light bounds of a sun light source. I am sure more clever people than me could come up with other tests. For pixels that "connect" to the light source, apply the ambient light; for those blocked from the light (e.g., contained within a room), do not. 

4. Indoors should be defined by walls and roof tiles, not drawings or other invisible polygons. Really, this means that lights (and roofs, and walls) must have an elevation. If the light is above the roof, then the roof blocks. Similarly, heights of walls should matter. You can keep them infinitely high for basic setup, but if you want a token to be lit by the sun when on a roof but not be lit by the sun when under the roof, then you need defined heights for walls. This may sound complicated, but it gets you a simple user interface. If you have a light at 10', and it is outside, you can easily see that it does not penetrate the building. Drag that light inside the building, and now the light is contained within the building. Move the light elevation up, and now you see it illuminates the roof instead of the inside of the building.

**Comment by LukasPrism** [comment]
From a game mechanics perspective it would be great to have some lights defined as uniquely sunlight/moonlight (and ideally custom labels) so that features that are affected by such things can be automated. Things like sunlight sensitivity, or the Morning Glory weapon from AHD.

**Comment by rapus95** [comment]
Hopefully this will also be implemented using tools that build onto #9772.
As it was always only refered to an outside map with many indoor areas like houses which would be fully surrounded by walls, I also want to propose the opposite. An underground map which is mostly indoors but has several light shafts through which outdoor light can flood the underground.
If using the regions of the linked issue, that would just be marking those light shafts as individual regions and setting the "is outdoor"-flag on all of them. If you then change the light color or darkness of the "outdoor light", this will carry on to all regions at the same time. Which is way better than having multiple light objects that need to be held in sync manually.

**Comment by aaclayton** [comment]
Closing this issue which is now encompassed by the #9772 epic.
