### ISSUE TITLE
Improve the rules for visibility detection of door icons to ensure that the light source polygon which illuminates the door is on the same side of the door as the vision polygon that has line-of-sight to it.

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/foundryvtt#4192]
Steps to reproduce:
1. Create a scene with vision, and without global illumination.
2. Create an enclosed space with with walls and a door, place a light behind the closed door.
3. Create an actor with vision and line of sight to the door, but not the light behind it. The actor's vision will reveal the presence of the door receiving light, even though they should not be able to see it in the dark.
4. Turn off the light inside the enclosed room. The door's icon should then vanish from the actor's vision.

Additional notes:
- If the actor does not have line-of-sight to the door (ex: due to walls blocking) they will not see the door icon, as expected.

**Comment by aaclayton** [comment]
Originally in GitLab by @dev7355608

The center point of a door control point lies, of course, directly on the wall segment and therefore on/near the edges of LOS/FOV polygons. Because of rounding the visibility test might return true even if the FOV and LOS polygon are on the other side of the door (the intersection of two polygons on different sides of a wall isn't necessarily empty). Only two points should tested: one in front and one behind the door. Maybe more points along the wall segment, but we don't want any sample points on the wall segment.
