### ISSUE TITLE
A setting for RollTables to roll blind.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#4316]
Originally in GitLab by @SalieriC

### Feature Summary
If RollTables are not animated (global settings) the option to not roll to the chat (RollTable setting) doesn't do anything. Results will still be displayed to everyone.

### User Experience

RollTables should always make a Blind Roll (only the GM Permission level can see it) regardless of the global setting (above the chat input) if they are neither animated nor set to "Display Roll to Chat?".

### Priority/Importance

The way it is currently handled is confusing, doesn't make any sense and the GM must be aware that he needs to adjust the roll method manually before rolling on a table if he does not wish to reveal the roll. This means that it is not breaking anything. Thus the importance isn't too high. Because of the confusing nature I'd say the importance is moderate.

**Comment by Fyorl** [comment]
This appears to be working correctly in v10 at least. Disabling 'display roll to chat?' correctly removes the roll from the result display, while having it enabled shows the roll. It's a bit difficult to understand what exactly is being asked for here though, and things have moved on a little since it was first reported, so it could do with a re-phrasing of the intended requirements/bug.

**Comment by silvative** [comment]
The results of a roll table do respect the user's chat settings in V11t3. I suspect this issue is more likely related to users misunderstanding the roll formula setting, which only changes visibility of the roll formula, and does not affect whether or not a chat card is created. It's possible that we could explore a different UX that makes this distinction more clear but the issue as reported does not exist.

https://github.com/foundryvtt/foundryvtt/assets/66365038/30f189d2-80e6-42e2-94ce-f51cf7b458a0
