### ISSUE TITLE
World login can fail in cases where a password manager is used due to Button `type` attribute

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#5560]
Somewhat of an edge case; the button type for the login button on a world's login page is `type="button"` until the user select menu is clicked. This can result in some password managers failing to detect it correctly as a submit button and prevent login for users (reporter of this bug was using BitWarden)

I believe a resolution to this would be to swap the logic used to disable the login button in this fashion to maintain the type as 'submit' and instead use the disabled property to handle cases where no user is selected.

**Comment by orangebutblue** [comment]
I have the exact same issue. Initially with v10 but I've since  upgraded to 11.315 and the issue still persists.

Filling in the credentials with the bitwarden browser extension will change the button type from 'submit' to 'button', which disables the button functionality. Clicking either the username drop-down menu (userid) or the password field, will change the button type back to 'submit'.
So, the way I currently login, is to load the page, auto-fill the credentials, then click the userid field to make the Join-button work, to be able to login

**Comment by thre-z** [comment]
Related: #10412

Maybe also: #10241

**Comment by aaclayton** [comment]
This should be resolved in V12 because with the conversion to Application V2 each form on the login page is a separate form with a `<button type="submit">` element and there is no swapping of the button type via JS.

Closing as duplicate.
