### ISSUE TITLE
Support buffering of socket updates that occur between the initial page load and game.ready in order to ensure that changes relative to the initially provided socket data are not lost.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5624]
Originally in GitLab by @fyorl

Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/848968607526551592/863822725847187476  
**ALL MODULES DISABLED?** false  
**OS, Hosting, Browser (if applicable):** Win10, Electron, Edge  
**Short Description of bug:** Creating combat during player loading in causes that player to have no info of the combat.
Simple steps to reproduce the bug: Add combatants and start combat while player is loading in (after login screen but before they reach ready event). Such as box select, add to combat, roll all, begin combat. The player will have no info about the combat, even if they swap scenes. Player refreshing their browser fixes this.

Presumably this affects more than just combat. If things happen during the loading, they will not be on the new player's side (no event/socket/whatever buffering until they can actually handle them and are instead lost into the void?)

**Comment by MrVauxs** [comment]
Updates on this?

**Comment by aaclayton** [comment]
No updates, was not prioritized for V10, maybe for V11.

**Comment by DanielTheBard** [comment]
Been having this become an issue again with players with particularly slow internet connections. I miss the catch up module :')

**Comment by ChristopherG84** [comment]
Still very much a issue. Still exponentially more frustrating the slower your internet connection:
- slower internet connection means more time for the race condition to occur
- slower internet connection means more time to try to fix the race condition. Which again, gives more time for the race condition to occur.

I would guess the biggest factor is probably asset loading down the whole loading process. And reloading the page will reload all assets again, so it never even gets better.

It does not need a perfect fix, just something that is better then the desynch/reload torture we have right now.
So a simple fix could be to just give us a "reload world state" option. Where it will just reload the world state, keeping already loaded assets cached. Might still have some loading times (because now the client realizes there was a missed map change, with the map asset not yet there), but that has to be orders of magnitude cheaper then a full load. And we can just keep repeating it until stuff starts being consistent.

**Comment by aaclayton** [comment]
I think this is a good strategic objective for us to look at in V12. No guarantees - prioritization can be tricky.

**Comment by ChristopherG84** [comment]
It does not need to be a perfect solution. Right now, I think we would even take a Auto-Pause when someone is loading. As long as it was a toggle.

**Comment by aaclayton** [comment]
Further example from @natis1:

### What happened?

If, while loading the game, any changes are made by any other players to actors (EG moving them around etc). These changes do not synchronize with your game.

On shotty internet or lowend computers such as mine I've often experienced desyncs from? I don't know exactly. they seem to happen over time. maybe it's alttabbing or maybe it's just the system freezing. In any case. To fix these I ideally want to reload the foundry game when it's not my turn.

However, doing this requires everyone else not do their turns and wait for me to reload as anything they do while foundry is loading will lead to a guaranteed desync. Because my computer is slow, this takes around a minute WITH all modules disabled. In organized play games where people are using bloated numbers of modules, this can take 3 minutes or more.

What I want is some system to automatically resolve desyncs without reloading. or to resync any changes that were made during the loading process.

An image showing the desync:
![image](https://github.com/foundryvtt/foundryvtt/assets/2016651/9772bc05-7e20-4495-8d9f-d3dbd5ae4d27)


### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Have a system with two players. Alice and Bob
Login to Alice in one browser window and Bob in a second (incognito) browser window
Reload Bob's window
While Bob is loading, in Alice's window add items to a token, or move a token around.
Notice Bob will not have these changes and the only way to resync is to wait for Bob to reload.
This happens even with no modules enabled.

### What core version are you reporting this for?

Version 10 Stable 291

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled
