### ISSUE TITLE
Feature Request - Add Macros to the Foundry VTT sidebar

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#5836]
Originally in GitLab by @p4535992

### Feature Summary

Add Macros to the Foundry VTT sidebar!

### User Experience

Interacting with macro the same way of all the others entity (Actor, Journal, Compendium).

Every time (and i mean every time), i are asked where the macros are because it is not easy for some people to understand that they have to click on the little folder below.

### Priority/Importance

I think the priority should be medium to high and the complexity shouldn't be particularly high

I never realized I wanted something that badly until I saw it this module 

https://github.com/arcanistzed/sidebar-macros

but it should not be in module, but in the core

**Comment by esheyw** [comment]
I feel compelled to bump this as I was just about to make exactly this request. Having Macros tucked into their own corner separate from all the other documents one might have in a world seems arbitrary, and I've seen it be confusing for new users. I personally have been using [this module](https://github.com/arcanistzed/sidebar-macros/) since about my first week or two of using foundry, and it feels much more intuitive.
