### ISSUE TITLE
Added a link to the Releases page on the update dialogue when updating the core software.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6473]
Originally in GitLab by @arbron

Currently, within the Foundry update screen, only the latest update notes are available when updating between multiple versions. This was very noticeable with the 9.241 hotfix where the update came so quickly after 9.240, never giving a chance within the software to see the 9.240 update notes. Displaying the updates notes for all versions updated would be nice (so if you upgrade from 9.238 to 9.241, it would also display the notes for 9.239 & 9.240).

**Comment by anathemamask** [comment]
I think the simple solution here is to provide a link to the releases page for users to quickly access those update notes.

**Comment by zeel01** [comment]
> I think the simple solution here is to provide a link to the releases page for users to quickly access those update notes.

That might be an okay short term improvement, but it doesn't actually solve the problem. I think the original suggestion is a better user experience over all. As it is, why display any change notes at all? Why not just a link? Because sending the user out of the app to read the changes isn't the best experience.

Additionally, this still doesn't *really* tell the user what changed since they last updated. It just sends them to a page of more or less meaningless version numbers to click on.

Ideally, the prompt should list the current version, the new available version, and all the change logs for each version in between enabling the user to see the entire scope of what they are updating without needing to leave the application or take note of the version numbers involved.

**Comment by aaclayton** [comment]
Keeping this issue small in scope to just provide a link to foundryvtt.com/releases, I made #7441 to track the more ambitious solution of providing links to all intermediary updates.
