### ISSUE TITLE
Add Setup page link to open up Package list if a given search is not found

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6494]
Originally in GitLab by @InkyThumb

As a new user with no systems or modules installed, the layout of the Game Systems and Add-on Modules tabs in the Configuration menu feels counter-intuitive. When using the search bar, it doesn't find anything, and it appears that there is no package available for you to install. The blank space below (presumably for packages you searched for to appear) implies that you are supposed to find the package you'd like to install, select it and then hit the install button at the bottom of the page.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/48b23209bae87851c93af958bf9540d9/image.png)

**Comment by cswendrowski** [comment]
This is helped by our new Setup tour that shows how to install a System if none are installed, but will review to see if we can do more

**Comment by cswendrowski** [comment]
When a search results in no installed packages, it will now result in a link to search for that package in the package directory

**Comment by BadIdeasBureau** [comment]
Small suggestion - change that text to "no _installed_ packages match your filter" for a bit of additional clarity for users who may not get the distinction that that window shows installed packages, and the package list is a different thing.

(Also possibly "modules" rather than "packages", since that's what's being displayed here and there's no harm in being more specific, but I think that's less important)
