### ISSUE TITLE
Integrate ActiveEffects with DataModel so that active effects can make more intelligent choices about how to cast data and apply changes.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6631]
## Related Issues 
-https://github.com/foundryvtt/foundryvtt/issues/8804
-https://github.com/foundryvtt/foundryvtt/issues/9468

### Issue Description
The recent changes to _applyOverride, _applyAdd, _applyUpgrade has caused a problem.

If an actor has data.data.attributes.hp.max === null (i.e. no value entered) an effect like
data.attributes.hp.max OVERRIDE 10 (although it can be almost any action) will result in hp.max being set to the string '10'.  
This breaks any subsequent active effects on that field since it becomes a string, rather than a number.  
This applies to any field that is ultimately meant to be numeric but is null by default.

Suggested fixes - default numeric fields to 0 if null in applyEffects rather than allowing null OR test the value being applied and if it is a number assume that the target should be a number instead of a string

**Comment by arbron** [comment]
Now that systems are adding `DataModel` for their system data, it would be great to use that configuration when applying active effects.

My proposal would be to move the actual methods for how changes are applied to the fields themselves. Then the active effects system could fetch the field for a target (`system.attributes.hp.max` would return the `NumberField`) and run the method on that field (so `NumberField#applyOverride` would ensure the value is first cast to a number before being applied).

The big advantage of moving this logic into the API of `DataField` is it would allow custom `DataField` types to declare their own logic. For example, an issue we have had in `dnd5e` is using active effects to modify formulas. The current recommendation is always to prefix your value with a `+` to ensure it isn't improperly concatenated because the core system just adds the two strings together. This approach would allow 5e's new `FormulaField` to contain its own logic for each of the application methods:

- `FormulaField#applyAdd`: `original + new` (`1d6` + `6` becomes `1d6 + 6` rather than `1d66`)
- `FormulaField#applyMultiply`: `(original) * new` (`1d6 + 5` x `2` becomes `(1d6 + 5) * 2`)
- `FormulaField#applyUpgrade`: `max(original, new)`
- `FormulaField#applyDowngrade`: `min(original, new)`

Override and custom would presumable be handled exactly how they are now, and the old methods would need to be kept around for any targets that do not have a `DataModel` (derived fields or flags for example).

**Comment by aaclayton** [comment]
Tagging as a desired candidate for V12.

**Comment by JPMeehan** [comment]
One special use case that might be more complicated here: Make it possible for systems & modules to have some control over their `flag` namespace. Active Effects are the usual way that users interact with setting & updating flags, but you end up totally bereft of the usual data validation that happens in the rest of Foundry. In the context of this ticket, that's some extra validation for an `ObjectField`.
