### ISSUE TITLE
Add CSS layers to provide more separation between core, system, and module styles

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6842]
Originally in GitLab by @arbron

### Feature Summary

With the release on Safari 15.4, all major browser engines support [CSS Cascade Layers](https://www.w3.org/TR/css-cascade-5/#layering). Foundry adding a series of default layers would help in separating the cascade between the different components and make it easier for system authors to override core styles, and module authors to override core and system styles.

### User Experience

Foundry core could define a series of layers such as this:

```css
@layer reset, core, system, module
```

And then it could spec all of its built-in stylesheets to the `reset` or `core` layers, letting system and module authors use the other two to use. This would reduce authors reliance on import order and specificity

Eventually, when the `layer` property within `<link>` tags is added, these could be automatically applied to stylesheet imports so module and system authors get the layering benefits with no additional work.

It might also be worth it to split the `module` layer into multiple nested layers:

```css
@layer reset, core, system, module.utility
```

This would allow utility modules to be applied using `@layer module.utility` and other modules with `@layer module`, making it easy for regular modules to override styles from utility modules.

### Priority/Importance

This support is fairly new in all browsers so it can certainly wait until these latest browser releases are more widely adopted.

**Comment by rsek** [comment]
speaking personally, i'd estimate that at least 10% of the man-hours i spend on Ironsworn system development involves negotiating around FVTT's CSS. it's no exaggeration to say that even the simplest possible implementation of this feature (in other words: all of FVTT's styles on a single `default` layer) would instantly save me many hours of labour.

it looks like [all major desktop browser releases](https://caniuse.com/css-cascade-layers) since April 19, 2022 have supported it... so i'd be very keen for this feature to be revisited! :)

**Comment by aaclayton** [comment]
We are likely to adopt layered styling in the future, but the time to do that will be the major version when we introduce a new CSS framework overall to consolidate the degree of disruption caused for modules who currently style the UI in a certain way. We are going to start this work in V11 but for the `/setup` screen only. These changes can expand to the full client-side experience in V12 or V13.

**Comment by phenomen** [comment]
Just make sure modules will still be able to override styles of other modules and systems. I use lots of hacks and tweaks to make Foundry and systems work with Cyrillic in the [localization module](https://github.com/phenomen/foundry-vtt-ru/tree/master/styles).

**Comment by zeel01** [comment]
@phenomen It should only make that easier. Using a layer doesn't mean "this is more important" it means the opposite: It means "it's okay to override me."

With CSS layers, the "no layer" layer (all code not written in a specific layer) has the highest priority. That means any styles written without layers in mind supersede all styles that use the feature.

This has some both unfortunate but also _exciting_ implications for Foundry. The disappointing part is that if Core doesn't utilize layers at all, the feature is entirely useless to everyone else. Unlayered Core styles would always supersede layered system and module styles, rendering them ineffective.

**But**, the upside of this is that the minimum useful implementation in Core could be accomplished by only adding three lines of CSS:

```css
@layer core, system, module;
@layer core {
 [... all existing Core styles ]
}
```

And this would have virtually no immediate effect on existing systems or modules at all. All this would do is move Core styles to the `core` layer, giving them a lower precedence than all unlayered styles. Since all existing module and systems styles are unlayered, they would all be higher precedence than Core... which they already do by being files included after the core stylesheets, and because authors have already written them to override core styles.

Defining layers doesn't force modules or systems to *use* those layers. But if Core defines a `system` layer after `core`, system devs can easily adopt it (with only two new lines of code). Those systems *also* won't break anything for modules, since unlayered modules will still have higher precedence than systems.

But the advantage is that now `system` layer styles beat `core` layer without playing specificity games, and unlayered or `module` layer styles beat `system` and `core` style - just the way we want it.

There could also be many *more* layers for really specific things. For instance, a `ui` layer that comes after `core` but before `system` so modules that override the UI can make themselves lower priority than the system, in case the system also overrides those styles, to avoid compatibility issues. Or a `theme` layer before `module` so a theme module will be overridden by the more specific styles of more specific modules without as much work.

Plus, if Core and Systems adopt layers, modules can start creating their own layers: For instance, the Monarch module could add a style layer so that it's possible for another module (or even the system!) to override its module-specific style for card hands more easily.

Layers also have an "opt out" capability I mentioned in the comment above, where a higher priority style can opt out of styles from some lower priority layer. Potentially, this could even allow a module to reset itself all the way back to user-agent defaults in a few lines of code, without negatively effecting any other modules.

Adding the baseline of CSS layers should be possible with virtually zero disruption. I can see one or two ways that systems moving to layers could cause a little downstream disruption for modules, but it would be a weird edge case. I don't think the same could happen with Core though. There's no reason anyone would write a style that was *supposed* to be overridden by Core, so moving Core to the lowest priority wouldn't effect any existing code.

**Comment by rsek** [comment]
> There's no reason anyone would write a style that was _supposed_ to be overridden by Core, so moving Core to the lowest priority wouldn't effect any existing code.

yeah, exactly! another way of framing it is: using CSS layers won't be causing CSS to fail -- that CSS is already broken (in the sense that code exists for it but has zero effect). it was just *failing silently* before rather than providing some perceivable (visual) feedback to the error.

**Comment by aaclayton** [comment]
This has been implemented for Phase 1 of our Setup UI redesign in V11P2.

There are multiple layers used in the new UI redesign, but for the legacy UI we have added a single layer, `core`.

**Comment by zeel01** [comment]
I'm not sure I understand the resolution on this. I take it that "Setup UI" means non-game screens, and that the "legacy UI" still applies to those? Given that setup screens aren't available for systems and modules to modify, it sounds like we only got one layer `core` that effects anything in-game?

If that's the case, is closing this ticket meant to indicate that `core` is the only layer that will be added? One of the primary benefits of this technology would come from Core pre-defining a layer order such as `@layer resets, core, ui, theme, system, application, ...` - enabling other packages to slot styles into these layers without creating any uncertainty as to the order in which they are applied. 

If the plan is to add more layers in the future, should this ticket remain open to track that?

**Comment by aaclayton** [comment]
"Setup UI" means the non-game screens, yes. The "legacy UI" does not apply to those because that's where we are starting our redesign efforts as implemented in https://github.com/foundryvtt/foundryvtt/issues/5832.

For the time being, yes, there is only one `core` layer for the game UI which allows you to reset all core styles or use all core styles.

**Comment by aaclayton** [comment]
An update on this. We have had to roll back this change for the current game CSS file because it turns out that adding layers here causes some major UI breakage for common systems and modules whose CSS rules are currently designed with a certain specificity required to overcome core styles. 

The consequence of wrapping core styles in a layer is that now package-defined styles that did not previously override a core style now do so, causing some occasionally dramatic negative consequences. 

We want to support CSS layers, but I think we need to make it part of our longer-term CSS overhaul which is starting with the setup areas of the software in V11 and will be opt-in for the game areas of the software starting in V12 or V13.

**Comment by Fyorl** [comment]
This has now been implemented in the Game view of the application and will be available in the Prototype 1 release of v13. The built-in layer structure is as follows:

```css
@layer reset,           /* 1. Browser reset styles */
       variables,       /* 2. Declare framework variables */
       elements,        /* 3. HTML elements and typography */
       blocks,          /* 4. Block styles which are used across applications */
       applications,    /* 5. Application-specific rules */
       compatibility,   /* 6. V1 compatibility layer */
       layouts,         /* 7. Page layouts */
       system,          /* 9. Default game system styles */
       modules,         /* 9. Default module styles */
       exceptions;      /* 10. Special exceptions */
```

The `compatibility` layer should ensure that V1 styles continue to look and function as before in this new layer structure, but if there are any discrepancies, please let us know.

By default, all system and module styles declared as part of the `styles` manifest property will be automatically wrapped in the `system` or `modules` layers respectively. Packages may declare a different layer that they wish their CSS file to be injected into by supplying the new `layer` property alongside their style declaration, e.g.:

```js
"styles": [
  "mymodule.css", // Automatically placed in the modules layer.
  { "src": "myvariables.css", "layer": "variables" } // Placed in the variables layer.
]
```

Packages wishing to opt-out of having their CSS wrapped in a layer (if they declare their own, complex layer structure, for example) may do so by explicitly supplying `null` as the `layer` value, e.g.:

```json
"styles": [{ "src": "mymodule.css", "layer": null }]
```
