### ISSUE TITLE
Attempt to improve the default resolution scaling setting by guessing whether the user has a retina display and, if so, reducing the resolution by half in order to improve performance.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6879]
Originally in GitLab by @unsoluble1

Suggest defaulting to `true` for `Disable Pixel Resolution Scaling`.

On even fairly high-end hardware, running at retina resolution is a significant performance hit -- I'm seeing an immediate global drop from 60fps to ~30fps on an M1 Max here. Poor experience for new users, or anyone unfamiliar with this setting.

**Comment by dev7355608** [comment]
So I discovered that `window.screen` behaves differently in Chrome compared to Firefox.

In Firefox we can calculate the physical width/height of the screen by multiplying the  `window.screen`'s dimensions with `devicePixelRatio`, which allows us to make a guess based on the physical resolution.

In Chrome however `window.screen` always returns the logical size of the monitor after Windows display scaling but not including the browser zoom. So we can't calculate the physical resolution of the screen, and we can only make a guess based on `devicePixelRatio`, which is much more flawed.

I also briefly checked Safari, which also behaves differently. Browser zoom doesn't seem to affect `devicePixelRatio` at all, which should allow to detect retina with 100% accuracy.

The current implementation will probably always return false (at 100% browser zoom), unless the logical size of monitor is larger than 4500 pixels (if this monitor was retina, then it would have more than a 9k physical resolution).

Also the numbers (3500/4500) should probably be halved. I think I got confused when I came up these and doubled the physical resolutions of retina displays. And it would probably make more sense to test the minimum instead of maximum dimension to avoid ultrawide screens being detected as retina.

**Comment by aaclayton** [comment]
@dev7355608 thank you for sharing your findings. I have interpreted your comments as follows, and made this change to the method. I don't know whether this is a good logic to use or not, if you or @unsoluble1 have any feedback please let me know:

```js
  /**
   * Guess whether the user's display is probably a retina screen.
   * Unfortunately there is not currently a reliable way to know this for sure.
   * https://en.wikipedia.org/wiki/Retina_display
   * @returns {boolean}
   */
  static isProbablyRetinaDisplay() {
    const screen = window.screen;
    const threshold = PIXI.utils.isMobile.any ? 1792 : 3024;

    // Safari
    if ( navigator.userAgent.match(/Safari/) ) {
      return Math.max(screen.width, screen.height) >= threshold;
    }

    // Firefox
    if ( navigator.userAgent.match(/Firefox/) ) {
      const trueWidth = screen.width * window.devicePixelRatio;
      const trueHeight = screen.height * window.devicePixelRatio;
      return Math.max(trueWidth, trueHeight) >= threshold;
    }

    // Chrome or Other
    else {
      if ( window.devicePixelRatio <= 1 ) return false;
      return Math.max(screen.width, screen.height) >= threshold;
    }
  }
```

**Comment by unsoluble** [comment]
Looks good, curious how you came up with those specific threshold values.

(aside: handle is just @unsoluble here; the 1 had to be added over at GitLab because oops I made two accounts)

**Comment by aaclayton** [comment]
I surveyed the wiki page <https://en.wikipedia.org/wiki/Retina_display> and picked some devices which seemed like they represented semi-modern cutpoints. It was a bit of a crapshoot.

**Comment by dev7355608** [comment]
From my very limited test in Safari this should be able to detect retina with 100% accuracy (because browser zoom doesn't seem to affect `devicePixelRatio`):
```js
    // Safari
    if ( navigator.userAgent.match(/Safari/) ) {
      return window.devicePixelRatio > 1;
    }
```

The Firefox test looks.

In the Chrome test you have to multiply width/height with `devicePixelRatio` just like with Firefox, but you have to pray the browser zoom is at 100%.

I also recommend to test the minimum of the width and height, otherwise any ultrawide monitor is detected as retina, I assume.

**Comment by aaclayton** [comment]
Good feedback, thanks. Modified to:
```js
  /**
   * Guess whether the user's display is probably a retina screen.
   * Unfortunately there is not currently a reliable way to know this for sure.
   * https://en.wikipedia.org/wiki/Retina_display
   * @returns {boolean}
   */
  static isProbablyRetinaDisplay() {
    const screen = window.screen;
    const threshold = PIXI.utils.isMobile.any ? 750 : 1600;

    // Safari does not put browser zoom into devicePixelRatio, so we know this means retina
    if ( navigator.userAgent.match(/Safari/) ) {
      return window.devicePixelRatio > 1;
    }

    // Firefox
    if ( navigator.userAgent.match(/Firefox/) ) {
      const trueWidth = screen.width * window.devicePixelRatio;
      const trueHeight = screen.height * window.devicePixelRatio;
      return Math.min(trueWidth, trueHeight) >= threshold;
    }

    // Chrome or Other
    else {
      if ( window.devicePixelRatio <= 1 ) return false;
      const estWidth = screen.width * window.devicePixelRatio;
      const estHeight = screen.height * window.devicePixelRatio;
      return Math.min(estWidth, estHeight) >= threshold;
    }
  }
  ```

**Comment by aaclayton** [comment]
@dev7355608 I double-checked on Firefox (on Windows) and browser zoom DOES affect devicePixelRatio, so this becomes no different from the Chrome case.

**Comment by aaclayton** [comment]
I don't think multiplying dpr in the chrome case is the right thing to do. Chrome does not adjust the screen dimenions for browser zoom. Browser zoom is more common than retina screen, so this would be counter-productive I think.

**Comment by dev7355608** [comment]
Browser zoom does affect `devicePixelRatio` in Chrome and Firefox, but `window.screen` remains unchanged in Chrome if the browser zoom is changed. In Firefox `window.screen` is scaled with the browser zoom such that it allows us to calculate the physical resolution accurately. In Chrome that's only possible if the browser zoom is at 100%. If you don't multiply with `devicePixelRatio`, you'll get only the logical resolution of the screen, which is probably always below your thresholds.

That said you can merge the the Chrome and Firefox tests. This extra check doesn't really improve anything: `if ( window.devicePixelRatio <= 1 ) return false;`.

**Comment by dev7355608** [comment]
Chrome on the iMac I tested on has *Safari* in `navigator.userAgent` for some reason. So it never tests the Chrome case, which would return false, because `width` and `height` are not multiplied by `devicePixelRatio` (`screen.width` is 2560, `screen.height` is 1440, `devicePixelRatio` is 2).

**Comment by aaclayton** [comment]
Perhaps its my frustration speaking, but I think I don't care anymore. If and when chromium or navigator provides some reliable core API for this, or if there becomes an established algorithm for us to detect this, or if PIXI provides a core helper that does the job for us I'll gladly use it - but I don't care to continue tweaking this for little-to-no practical gain.

**Comment by TemplarsKnight** [comment]
FWIW: I have an Odessey G9 with 5,120 x 1,440 pixels on a WIN 11 machine. Retina mode was active by default and everything was washed out. Since it seems that accurate detection is not possible, I suggest disabling it by default and including it in the FAQ for MAC users (since smaller community).

**Comment by unsoluble** [comment]
It sounds like it did actually detect your display properly — that's what it's meant to do.

The original impetus here was to prevent the negative experience of having poor framerate, which is typical of the _majority_ of machines that have retina screens. As in, almost every Mac shipped in the last seven years or so has one, and almost none of them are performant enough to run Foundry at that full resolution.

The fact that this heuristic will also sometimes hit people with hi-dpi screens _and_ machines performant enough to run like that just fine was a known trade-off. Maybe the wrong one? But that's how we got here.

**Comment by dev7355608** [comment]
If it's not possible to detect the browser reliable anymore, the Firefox case should be used for all browsers unless it's preferred to remove the automatic detection attempt entirely.

In the beginning of the thread I suggested to replace this setting by a Resolution Scaling slider. That is also an option. I think, if a user noticed bad performance, most user's are going to look for graphics settings to improve performance, and, if they find a Resolution Scaling slider with a good description regarding retina, they will be able to successfully improve the performance without any autodetection help. But I'd say the performance/graphics settings are somewhat hard to find, because they are mixed with other core settings that are unrelated to performance. If the performance/graphics settings (Resolution Scaling, Performance Mode, Maximum Framerate, Show FPS, Light Source Animation, Zoomed Texture Antialiasing) would be put in a separate tab, users would be more likely to successfully improve performance, I think.

**Comment by unsoluble** [comment]
I think the grouping idea is strong.

Alas one of the main reasons I brought this up in the first place is that it's _very_ common to be troubleshooting with people who have been running Foundry for months with shite framerates, assuming it's just that their machine can't handle anything better, and never having come across the resolution checkbox (or known what it does).

**Comment by thre-z** [comment]
Since FPS is known, there could be a dismissible little prompt (... clippy?) to start a tour of the performance settings upon detection of low FPS. 

Probably well out of scope of this issue, though.
