### ISSUE TITLE
Add uniforms for useful properties of light and vision source data

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7110]
Originally in GitLab by @dev7355608

Useful additions would probably be `rotation`, `angle`, and `luminosity`; also `x`/`y`/`z` (`origin`) as well as `radius`.

I also suggest merging background, illumination, and coloration uniforms, creating one common set of uniforms that all shaders have access to. Unused uniforms in a shader are optimized away, so there's no performance penalty. Each light shader could share the same uniforms object, which makes updating/animating uniforms simpler, because we just need to manage one uniforms object, not multiple. This would also force some better naming of the uniforms: `alpha` in the illumination shader is different from the `alpha` in the coloration shader, which can be confusing.

**Comment by dev7355608** [comment]
If `color` is not set, the default color is used ([1, 1, 1]):
```js
u.color = this.data.color ? this.colorRGB : d.color;
```

Could we upload the default `colorAlpha` if no `color` is set too?:
```js
u.colorAlpha = this.data.color ? this.data.alpha : d.colorAlpha; // d.colorAlpha === 0.5
```

Then there's no need to use a `hasColor` uniform when it comes to computing the `colorDim`/`colorBright` inside the illumination shader, because the illumination part of a light source with no color and a light source with the default color and default alpha have the exact same appearance.

It probably can't hurt to have a `hasColor` uniform too.
