### ISSUE TITLE
Allow passing arbitrary arguments to script macros and make it possible to use the return value of script macros

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7184]
Originally in GitLab by @ghost91-

### Feature Summary

At the moment, it's possible to pass `actor` and `token` as parameters when programmatically executing a macro. For many modules (in particular, automation modules, such as midi-qol), it would be very helpful if it was also possible to pass in other arbitrary arguments. Currently, these modules rely on this functionality being provided by the Advanced Macros module (it allows passing arbitrary `args`), but it is unmaintained and also contains a lot of other unnecessary functionality.

Similarly, it would be very useful if it was possible to use the return values of macros.

A simple implementation could look as follows:
```js
class Macro extends ClientDocumentMixin(foundry.documents.BaseMacro) {
  /* ... */
  execute({ actor, token, args } = {}) {
    if (!this.canExecute) {
      return ui.notifications.warn(`You do not have permission to execute Macro "${this.name}".`);
    }
    switch (this.type) {
      case "chat":
        return this._executeChat();
      case "script":
        return this._executeScript({ actor, token, args });
    }
  }

  /* ... */
  
  _executeScript({ actor, token, args } = {}) {
    // Add variables to the evaluation scope
    const speaker = ChatMessage.implementation.getSpeaker();
    const character = game.user.character;
    actor = actor || game.actors.get(speaker.actor);
    token = token || (canvas.ready ? canvas.tokens.get(speaker.token) : null);

    // Attempt script execution
    const async = this.command.includes("await") ? "async " : "";
    const body = `return (${async}() => {
      ${this.command}
    })()`;
    // eslint-disable-next-line no-new-func
    const fn = Function("speaker", "actor", "token", "character", "args", body);
    try {
      return fn.call(this, speaker, actor, token, character, args);
    } catch (err) {
      ui.notifications.error("There was an error in your macro syntax. See the console (F12) for details");
      console.error(err);
    }
  }
}
```

The `async` is only being added conditionally, so that the return value of synchronous macros can be used synchronously. Technically, just searching for `await` in the macro command might not be 100% accurate to detect if the macro needs to be async. If 100% correctness is needed, we could first try to create the Function without `async`, and if a `SyntaxError` is thrown, create it with `async` instead.

### User Experience

The user experience should be basically the same as what is provided by the Advanced Macros module, so that existing macros can continue to be used.

### Priority/Importance

Not very important, since there are workarounds using modules, but having this in core would be great for the module ecosystem.

**Comment by mclemente** [comment]
Hello, developer of Advanced Macros here.
Could you consider implementing this for V11? Despite the module not being in danger of being abandoned (if I were to abandon it, p4535992 could probably take over the project), it is bothersome that there's a lot of things depending on this workaround until it becomes Core.
Advanced Macros has been the go-to module for the workaround to this issue, but its original code is from V3 or V4, and rewriting it to conform with the "standards" of module development for modern FVTT (such as using libWrapper over monkey-patching or SocketLib over managing sockets) has shown some issues with the dependence on thiese workarounds.

Please, consider the following issues.

## There's premium modules that depend on Advanced Macros
If I release a update that breaks things, or a Foundry update breaks the module, users might have their premium module breaking on them and the premium module maintainer will either need to update their module or wait for a fix on Advanced Macros. And I can't test premium modules that I don't own, so it's [a hit or miss on the fixes](https://github.com/mclemente/fvtt-advanced-macros/issues/50).

## Other systems might break Advanced Macros
While this isn't a Foundry problem, system developers don't take modules into account when they're implement new features, and breaking support with Advanced Macros negatively impacts users, since they will miss out on macros with arguments. This would be avoided if the behavior was part of Core, since system developers would notice it on a "no modules" environment.
For example, the PF1 system added a change to `ChatLog.MESSAGE_PATTERNS` to check for `/heal` and `/damage` commands, and it broke Advanced Macros since it used a monkey-patch back from Foundry V6.
And PF2e system added its own Macro class, which broke Advanced Macros on the system and made other system-specific modules that depended on it to break until it was fixed.

## Macros enables blind people to play RPGs
During the fixes for the PF1 system, I've found out [my module is essential for blind players](https://github.com/mclemente/fvtt-advanced-macros/issues/30#issuecomment-1161736580) since back then there was no way to run macros through the chat. Since then, the `/macro` chat command was added, but there's still no way to send arguments through chat commands without the module, so it limits Core's usability.

**Comment by aaclayton** [comment]
Will add it to our "V11 Nice to Have" tracker.

**Comment by ThunderousLeft** [comment]
🍴 🍴

**Comment by MrVauxs** [comment]
> Will add it to our "V11 Nice to Have" tracker.

Should this be added to the [V11 Project](https://github.com/orgs/foundryvtt/projects/32/views/1)?

**Comment by aaclayton** [comment]
This was kept in the "Nice to Have" bucket since it's not mission-critical for V11, but I'll add it to the dev2 milestone since it would represent an API change and should be done in this current development phase.

**Comment by aaclayton** [comment]
Implemented for V11 using a parameters object destructuring approach. 

## Example Script Macro
```js
const a = game.actors.get("FHXBprekfww93EWz");
return a.update({name: params.name || "NO PARAM"});
```

## Example Programmatic Execution
```js
const m = game.macros.get("kIuGflzokbwdwla5"); // the above macro
const a = await m.execute({name: "New Actor Name"});
console.log(a.id); // "FHXBprekfww93EWz"
console.log(a.name); // "New Actor Name"
```

**Comment by tposney** [comment]
I love that it is possible to pass arguments to macros now.

As a module writer who has based my macro calling off Advanced Macros where args is an array of values there is a compatibility issue for me with args being an object, i.e. lots of macros reference args[0], args[1] etc and there is quite a body of macros that expect that.

I prefer foundry's implementation, but if possible (before it is too late) can the foundry args be called anything else beside args (i.e. arguments or anything)?
That way I can insert something like
```js
const args = arguments.args
```
in the macro body and things will still work as before but using the foundry macro.execute while allowing code to migrate to the new scheme by referencing arguments.id.

With the foundry arguments being args this is not possible.

**Comment by aaclayton** [comment]
A fair point @tposney - I agree in light of your comment that we should choose a different name.

**Comment by tposney** [comment]
It has been pointed out that I can use args = {0: myargs[0], 1: myargs[1], ....named args...} when calling the macro which should provide both the backwards capability and allow migration at the same time. Other than the minisucle chance of a name collision on "0" or "1" that sounds like it should solve the problem and also mean no change is needed.

**Comment by mclemente** [comment]
Foundry's implementation is better in the long run. Writing code such as `{0: variablex, 1: variableY} = args` instead of just `[x, y} = args` isn't an improvement.
It becomes super messy if you intend to have optional arguments, see the [example on this discussion](https://github.com/foundryvtt/foundryvtt/issues/9201#issuecomment-1509948388) and compare with the object implementation in the comments below.
So, I don't see a good reason to keep using Arrays besides legacy support for the implementation on Advanced Macros.

>It would mean that all modules that do their own macro call would have to make the same sort of change, but that's not such a big issue, since they probably have to make a decision to do macro.execute in their code anyway - I'm thinking of advanced macros amongst others here.

Any wrap to macro._executeScript will stop working. If any module/system wrappped it, devs probably will need to update their code regardless, even if Foundry changes things back to Array.

>some sort of shim to provide backwards compatibility might be nice so that they can just turn off advanced macros. Perhaps core macro.execute can check if args is an array, do the mapping and issue a warning as well.

The idea of a shim is nice. Just add a deprecation warning for V12 and that should be enough time to update the macros.

**Comment by dmrickey** [comment]
Why are they being wrapped in an args argument? Why can't we just access them directly?

**Comment by aaclayton** [comment]
> Why are they being wrapped in an args argument? Why can't we just access them directly?

Because the enclosing macro function wrapper needs a contract about what arguments are passed in, and it doesn't know about arbitrary arguments defined by the user. There are two options only:

1. Add all such arguments as named keys and values in an object (the chosen route)
2. Add all such arguments as positional rest parameters (i.e. `...args`)

I felt that option 1 was better because it creates a more readable and ergonomic experience for the macro developer to write, for example, `args.actor` rather than `args[3]` and rely on silent assumptions about ordering.

**Comment by LebombJames** [comment]
From those two options, option 1 is clearly superior, I agree, but I think the point being made was why can't args be spread into the context object like
```js
_exectuteScript({actor, token, ...args})
```
where `args` is also an object. Not sure exactly how that would fit in, but I feel like that improves ergonomics further as most macro users will destructure `args` anyway.

**Comment by dmrickey** [comment]
Yeah, from those two choices I agree that the first choice is better. But I'm not sure why those two are the _only_ options.

E.g. pf1 has this in its own executor. I haven't dug through foundry's source to know if this is a viable alternative here or not, but it's definitely doable. 

```js

static AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;

  /**
   * Executes the script.
   *
   * @param {object} shared - An object passed between script calls, and which is passed back as a result of ItemPF.executeScriptCalls.
   * @param {Object<string, object>} extraParams - A dictionary containing extra parameters to pass on to the call.
   */
  async execute(shared, extraParams = {}) {
    // Add variables to the evaluation scope
    const item = this.parent;
    const actor = item.parentActor;
    const token =
      actor?.token?.object ?? (actor ? canvas.tokens.placeables.find((t) => t.actor?.id === actor.id) : null);

    // Attempt script execution
    const body = `await (async () => {
      ${await this.getScriptBody()} // fetches the text of the macro-like object or fetches the associated macro's data.command
    })()`;
    const fn = this.constructor.AsyncFunction("item", "actor", "token", "shared", ...Object.keys(extraParams), body);
    try {
      return await fn.call(this, item, actor, token, shared, ...Object.values(extraParams));
    } catch (err) {
      ui.notifications.error(`There was an error in your script/macro syntax. See the console (F12) for details`);
      console.error(err);
    }
```

**Comment by tposney** [comment]
Another option could be to do the function call via
```js
return await fn.call(extraParams, .......)
```
Since the existing use of "this" is not all that meaningful and then the macro code can do this.argName and there is no collision to worry about.

**Comment by krbz999** [comment]
Using `this` in a macro is often done to save flag data on the macro itself. Can we please not break core stuff just to accommodate the oddball function calls done by these older modules? `args.steve` is fine. So is `params.steve`. Heck, call it `steve.steve`.
