### ISSUE TITLE
Improve Token#getSightOrigin by generalizing its functionality into a new method: Token#getMovementAdjustedPoint which is used consistently for both vision polygon computation as well as movement collision testing.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#7218]
Imported from Gitlab

**Comment by caewok** [comment]
Here is a an example of when `getSightOrigin` fails:
https://user-images.githubusercontent.com/1267134/174667785-698e969a-22bc-441b-b88d-5e4e91cf8bb9.mov

I think I see the problem: The velocity measurement can be tricked because it doesn't update a measurement if it is zero. For example, assume a wall is 45º from nw to se, as in the linked screengrab. Token is to the ne of the wall. Token moves east 1 square, then south 1 square. Token velocity is now:
`{dx: 0, sx: 0.448673605, dy: 100, sy: 0.89734721}`

Now `getSightOrigin` tries to move the origin "backwards" 1 pixel:
```js
const {sx, sy} = this._velocity;
return {x: x - Math.sign(sx), y: y - Math.sign(sy)};
```
The result will be the origin moves diagonally nw---in exactly the direction of the wall! So no matter how many steps you take, token origin will still align with the wall. This is because `sx` and `sy` are both positive due to (I think) the directional memory embedded in the velocity. 

My proposed solution would be to use dx and dy instead, because they more accurately reflect the very last move the token made. In ``getSightOrigin`:
```js
        const {dx, dy} = this._velocity;
        return {x: x - Math.sign(dx), y: y - Math.sign(dy)};
```
I tested this in v10 and it appeared to work, but as I don't know exactly why `sx` and `sy` are used here, I am not sure if there are other edge cases that should be tested first.

**Comment by aaclayton** [comment]
Possibly related issue: <https://github.com/foundryvtt/foundryvtt/issues/6856>
