### ISSUE TITLE
It is now no longer possible for System and World required Modules to be inactive

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7254]
Unlike Modules, there is no time where a System nor World is "enabled", and so the current Dependencies workflow is never executed.

When a World is loaded, it and it's Systems required modules should always be active

![](https://media.discordapp.net/attachments/831269607343915018/1000103904836583594/unknown.png)

**Comment by ghost91-** [comment]
Wouldn’t this also require the option to manage which modules are active _before_ the world is loaded?

**Comment by aaclayton** [comment]
> Wouldn’t this also require the option to manage which modules are active _before_ the world is loaded?

"dependencies" in this case refers to requiring dependency modules to be *installed* not necessarily *active*

**Comment by ghost91-** [comment]
Are you sure? If that’s what this issue is really about, I think the description should be improved. It explicitly talks about _enabling_, which to me clearly means enabling it inside a game.

And in my opinion, then it wouldn’t really solve the issue, since the user would still have to activate those modules inside the world.

**Comment by aaclayton** [comment]
I believe what is meant by "check to verify that their [system] Dependencies are satisfied" is to verify that a system which has dependencies has those dependency modules installed so that they may be activated (as required).
