### ISSUE TITLE
A role that allows one player to help others, without being a GM or getting their token vision (character sheets, abilities, features, etc.)

### ISSUE THREAD

**Issue by TogaParty** [foundryvtt/foundryvtt#7331]
I am not the GM, but I am the Foundry "subject matter expert" for our group.  Trying to support other players that are learning about Foundry is nearly impossible in this situation.  Granting me owner permissions of other players tokens spoils the experience for me because I can see what they can see (vs. only what my own token can see).  Likewise, logging in as a GM or assistant GM spoils the experience.

The players in my group need support and assistance as they are new to Foundry, but I cannot help them because there is no role that allows me to view and edit their character sheets and still play the game myself.  This is causing a good deal of turmoil in my group, and other players are frustrated with things that I could easily fix for them if I could manipulate their character sheets.

### User Experience

> Please describe what you feel the ideal user experience would be for interacting with this new feature.

### Priority/Importance

> Please describe your assessment of feature priority. If you feel it is highly important, describe why you believe it to be more important than other enhancements.

**Comment by aaclayton** [comment]
I'm not sure I agree with this suggestion. I think we already offer lots of tools which can allow you to help others to control the VTT environment (namely you can be set as an owner of their actor). I know that this "spoils" certain things like allowing you to see from their vantage point on the canvas, but I think that is an acceptable tradeoff in order to have someone in the group who exerts more control over the experience of other party members than normal. 

For me this is a wontfix.
