### ISSUE TITLE
Changing the default page sheet to 'markdown' can cause pages to be uneditable

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7409]
Originally reported by zeel#4200 https://discord.com/channels/170995199584108546/956306859491471420/992224417931333702

**ALL MODULES DISABLED?** n/a  
**OS, Hosting, Browser (if applicable):** n/a  
**Short Description of bug:** If the default page sheet is changed to Markdown, any entries that are open at the time of the change will be put into a state that can no longer be edited until changing the default back, and reloading the application.  
**Simple steps to reproduce the bug:** 
1. Open multiple journals
2. Edit a page of one of them, and change the default sheet to Markdown.
3. All the open journals will close
4. Open one again, notice that the pages won't render correctly, and you can not edit any of them.
5. Close it, then open a JE that wasn't open before, change the default back.
6. Notice that the other entries still can not be edited.
7. Reload the application. 
8. Everything is back to normal.

**Screenshots and/or console errors:**

```
foundry.js:711 TypeError: Cannot read properties of undefined (reading 'length')
    at MarkdownJournalPageSheet._convertFormats (foundry.js:58115:99)
    at MarkdownJournalPageSheet.getData (foundry.js:58001:10)
    at MarkdownJournalPageSheet.getData (foundry.js:58329:30)
    at MarkdownJournalPageSheet._render (foundry.js:4556:29)
    at MarkdownJournalPageSheet._render (foundry.js:5282:17)
    at MarkdownJournalPageSheet.render (foundry.js:4515:10)
    at MarkdownJournalPageSheet.render (foundry.js:5779:18)
    at Object.callback (foundry.js:59046:42)
    at HTMLLIElement.<anonymous> (foundry.js:50709:14)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
```

**Comment by zeel01** [comment]
This is a weird issue. As far as I can tell, it happens because normally switching to Markdown not only changes the sheet, but also performs a conversion process. This doesn't happen when the default is changed.

This brings up an interesting issue. Since the MD sheet isn't compatible with HTML pages, and presumably the same is true the other way around, it isn't appropriate to set it as the default sheet to open all pages. Initially, issue #7401 seemed somewhat applicable, but on second thought the user absolutely may want to have all *new* pages set to MD by default - I probably would choose that myself.

When the idea of Markdown Journals came up, I assumed it would be a page *type*. It makes sense though to make the text type handle multiple formats, but editor sheets are probably not the ideal way to set the format of the document. This will only become a bigger issue with modules in play - a module that wants to add a new editor might only be appropriate for one of the formats, but the user won't necessarily know this.

It therefore may be useful to either use page type to handle this, or enhance sheet registration to add more nuance. This could be achieved through "subtypes" or even by having a sheet register some sort of format checking callback.

As for converting from one format to another... it might be better for this to be some explicit action the user takes, rather than a side-effect of changing sheets. An additional header button with another dialog for selecting format would seem appropriate.

**Comment by Fyorl** [comment]
>Since the MD sheet isn't compatible with HTML pages, and presumably the same is true the other way around, it isn't appropriate to set it as the default sheet to open all pages.

This is actually not the case. Both sheets save HTML content to `text.content`. There should be no issues with modules adding additional sheets since they should also be saving HTML to `text.content`.

The issue with markdown is that converting from markdown -> HTML -> markdown is not guaranteed to give you back the same markdown document you started with, so we do some extra work to try to preserve that original markdown content where possible. Any conversions are a result of that extra work, which is evidently still a bit buggy.

**Comment by zeel01** [comment]
By that I mean that the MD sheet is not compatible with an HTML page that hasn't been converted to an MD page in the first place. The `text.content` exists, but the MD sheet expects that `text.markdown` will also exist - but unless the conversion has taken place, it doesn't (it's `undefined`).

The MD sheet could do an extra check, and perform conversion on-render if this value isn't defined, but that could lead to a situation where the entry is converted to MD without the user really intending it to be. In this case, the worry is `HTML -> Markdown -> HTML` which is likewise not guaranteed to produce the same results after the conversion (it is in fact highly likely to discard data).

Thus, setting Markdown as the Default page sheet could lead to unexpected data loss, even if the error is patched over. I can see a user thinking "oh cool, I'll set it to always use Markdown" not expecting that if they edit any existing entries, those entries would then automatically be converted and some data potentially lost in the process.

**Comment by Fyorl** [comment]
If the concern is that a user accidentally opens a journal entry for editing with the markdown sheet when they didn't intend to, then it's easy enough to not save the content unless they made edits. If they do make edits then presumably they intend to edit the entry in markdown and will accept the limitations of the conversion.

I wouldn't really expect much in the way of data loss anyway since raw HTML is [valid markdown](https://spec.commonmark.org/0.30/#raw-html). But that might depend on our converter settings.
