### ISSUE TITLE
Option to disable Download and Print for embedded journal PDF

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#7416]
Most PDFs bought from DriveThruRPG, Paizo, Pinnacle, Free League, Pelgranne, etc. have visible or hidden watermarks. When playing online (especially with "random" people), it's not a good idea to share such watermarked files for privacy and possible legal issues. Google Drive has an option to disable Download/Print of shared PDFs so it's somewhat safe to use it with random online groups.

As it is now, Foundry V10 PDFs have both those buttons enabled by default so anyone can easily download your files.

![image](https://user-images.githubusercontent.com/138311/176950003-05f721ed-17fe-486e-ba30-690064c8df02.png)

### User Experience

An option to disable download/print of embedded PDFs similar to Google Drive sharing settings:

![image](https://user-images.githubusercontent.com/138311/176949035-49bf3fd5-5727-40f9-b5b0-125f3580e5a9.png)

![image](https://user-images.githubusercontent.com/138311/176950751-a20615f9-a86f-4a36-b9a3-c8eb088f5d59.png)

### Priority/Importance

A niche feature but necessary in some cases.

**Comment by aaclayton** [comment]
@Fyorl this probably needs a bit of scoping to see whether it's possible to control this functionality as part of the object frame or via an API that has some control over it.

**Comment by ghost91-** [comment]
Just a small note: From a legal perspective, it’s probably irrelevant whether the buttons are visible, or not. Even with them gone, it’s still trivial to download the files, since they are served via http. It is not even displayed inline for me, but downloaded directly, since i have deactivated the inline pdf viewer in my browser (I suppose, this also isn’t really ideal, since it kind of defeats the purpose of PDF journal pages altogether, if they aren’t even rendered inline…).

I assume google drive does some kind of server side rendering of the pdfs, which avoids this issue, since they don’t actually serve the PDF file itself to the client. But I don’t think that’s a feasible solution for foundry.
