### ISSUE TITLE
Enabling dependencies should now be blocked by the `compatibility` fields `minimum` and `maximum`, and indicate if it does not meet `verified`

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7472]
UI follow-up from https://github.com/foundryvtt/foundryvtt/issues/7314

`minimum` and `maximum` should not be enabled at world load and prevent enablement if they are not met.
`verified` should only prompt a warning.

Edgecases to verify:
* Multiple Packages declaring competing `compatibility` requirements that do not have an overlap - Resolution: Each package is blocked based on it's own dependencies, meaning a middle ground doesn't need to be found

### Disable Checkbox when Dependencies are not installed, or do not meet min / max

![image](https://user-images.githubusercontent.com/15639841/180571499-029344a0-5a8a-42d3-b7d7-abe4e67cf9a8.png)

### Display errors on dependencies blocking enablement

![image](https://user-images.githubusercontent.com/15639841/180571571-2f5a4e81-ef6c-4e2c-9197-0342594efb55.png)

![image](https://user-images.githubusercontent.com/15639841/180571710-4e896d8a-55bf-4aff-8a0c-403e0f6b97de.png)

### Display warnings on dependencies that do not meet `verified`

![image](https://user-images.githubusercontent.com/15639841/180571779-06b3a9ef-a755-4151-b047-b40058ef286c.png)

**Comment by aaclayton** [comment]
Looks good at a high level. Some comments:

1. I think we should use the new tooltip API here instead of titles.
2. I presume the color coding of dependencies indicates whether they are missing or have compatibility issues? I like that.
3. Perhaps the ability to test whether a package is capable of being enabled should be part of the commons library? We have a need of it in the client side for this UI, but we should also (and perhaps more importantly) be using this on the server side to deactivate modules which should not be enabled as part of the world launch procedure.

5.
