### ISSUE TITLE
In Hexagonal Columns scenes, scale tokens to fit inside the hexes

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#7477]
### Environment Details
9.269 / dnd5e

### Issue Description
When creating a token with dimensions 1x1 and scale 1.0 in a scene using Hexagonal Rows, the token is scaled correctly to fit within the bounds of the hex:
<img width="249" alt="CleanShot 2022-07-13 at 09 29 52@2x" src="https://user-images.githubusercontent.com/801582/178785617-a8be1fc6-63d6-4145-86f1-87a736680577.png">

But in scenes using Hexagonal Columns, it is not:
<img width="310" alt="CleanShot 2022-07-13 at 09 32 23@2x" src="https://user-images.githubusercontent.com/801582/178785663-853f5fe7-76e7-462c-aed8-8df9dfdda5d0.png">

These should be consistent (matching the Rows behaviour).

**Comment by Fyorl** [comment]
This is a little bit awkward because a regular hexagon's bounding box is not actually square, it is rectangular, so this is working as designed. When the token itself is exactly square we have to 'tie-break' and pick one of the hexagon's dimensions to scale by. We happen to choose the width, and since the width of a hexagon is different in each orientation, this screenshot is the result.

In order to address this, we've added some special-case logic for when the token is exactly square and the grid is a hex grid, in which case we scale by the grid size (which is either the hexagon's height, or its width, depending on the orientation).
