### ISSUE TITLE
`ClockwiseSweepPolygon` bug

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7496]
### Environment Details

* Foundry VTT Version: 10.273

### Issue Description

It's somehow related to the roof.

![image](https://user-images.githubusercontent.com/31905376/179144120-3131d7cf-4909-4b01-976c-904724f54d4b.png)

Give the roof a texture and reload the scene.
[fvtt-Scene-polygon-bug-(roof).zip](https://github.com/foundryvtt/foundryvtt/files/9117556/fvtt-Scene-polygon-bug-.roof.zip)

**Comment by caewok** [comment]
This one is weird and appears to depend on whether the roof is a webp or a png. 

1. Start with the freshly imported scene. (Looks fine)
2. Set the roof to a png. (Looks fine)
3. Reload scene. (Looks fine)
4. Change to a webp. (Looks fine)
5. Reload scene. (Broken)
6. Change to a png. (Broken)
7. Reload scene. (Looks fine)

So it is not the sweep per se, but I cannot rule out that something about roofs is messing with the sweep. It appears that when the LOS is broken, the sweep keeps that collinear wall when it should have been dropped. In other words, in the correct version, the sweep has only 7 walls; the incorrect version has 8. That added collinear wall is why the sweep LOS is wrong, but I don't know why the test for collinearity would at all depend on the type of roof image. 

What it should look like:
<img width="1157" alt="Screen Shot 2022-07-16 at 6 57 48 AM" src="https://user-images.githubusercontent.com/1267134/179358190-dcb5ddf1-3eb0-4d5c-8e16-f22347bd9c27.png">

**Comment by caewok** [comment]
It looks like in the broken LOS version, `wall.hasActiveRoof` is returning true for that collinear wall, causing it to be included in the wall set from the `_testWallInclusion` method. Again, I don't know why that test would return different answers for different images, but it seems to have something to do with the occlusion test. 

A potential fix would be to test for collinear walls sooner and reject them regardless of the `hasActiveRoof` status. But that may have negative consequences for roof occlusion—I don't know enough about roof occlusion to speculate on the consequences of that change. And given that this does not occur with png images, it is probably better to first determine the root cause.
