### ISSUE TITLE
Tile selection does not respect the Elevation field

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7518]
While i'm not sure if this is intended for the current V10, setting a custom elevation property on tiles\drawings is not respected when selecting\hovering. In these situation only the z index will be considered. This is obviously because core assumes elevation to be a flat value which is shared across all tiles.

Would it be possible to take elevation into account as a higher priority than Z index or should i do my own overrides to handle that in Levels?

**Comment by aaclayton** [comment]
The secondary priority channel stored on each child of the PrimaryCanvasGroup is `sort`. To break ties between tiles at equal elevation, some tile should be given a higher or lower `sort` value. 

We separated it this way because `elevation` has mechanical significance while `sort` only has aesthetic signifiacance. Instead of assigning `zIndex` (which is not used by the `PrimaryCanvasGroup#sortChildren` method anyways) you should assign the Tile a higher or lower `sort` value.

If this doesn't work and you think there is still a bug here, please feel free to re-open the issue.

**Comment by theripper93** [comment]
Unless i'm misunderstanding, as suggested i'm overriding the `sort` value
```js
Object.defineProperty(TileDocument.prototype, "sort", {
  get: function () {
    if (this.overhead) {
      const e = this.elevation;
      return e*10000+this.z;
    }else{
      return this.z
    }
  }
});
```

What happens tho, is that when hovering a tile, the one with the lowest sort still takes priority
![image](https://user-images.githubusercontent.com/1346839/179366707-9a74eb13-fefe-468c-9429-be090d249aca.png)
![image](https://user-images.githubusercontent.com/1346839/179366732-807b1785-591c-46ba-9114-5ae49888d8c6.png)
![image](https://user-images.githubusercontent.com/1346839/179366755-7b710420-a3f7-460b-a605-73084df04323.png)

**Comment by theripper93** [comment]
I will add that the same behaviour persists even with all modules disabled
