### ISSUE TITLE
[Bug]: `ClockwiseSweepPolygon#defineBoundingBox` doesn't properly pad the bounding box

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7576]
### What happened?

The padding doesn't seem to quite correctly calculated. I'm not sure if this has any real consequence. But but there's an easy way to ceil/pad a rectangle: 

```js
  #defineBoundingBox() {
    let b = this.config.useInnerBounds ? canvas.dimensions.sceneRect : canvas.dimensions.rect;
    for ( const shape of this.config.boundaryShapes ) {
      b = b.intersection(shape.getBounds());
    }
    return new NormalizedRectangle(b.x, b.y, b.width, b.height).ceil().pad(1);
  }
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
b = new PIXI.Rectangle(-99.5, -99.5, 100, 100)
console.log(b.contains(0, 0)) // true
n = new NormalizedRectangle(Math.floor(b.x)-1, Math.floor(b.y)-1, Math.ceil(b.width)+1, Math.ceil(b.height)+1)
console.log(n.contains(0, 0)) // false
```

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by caewok** [comment]
Agree that `pad` may be the better approach. Originally, there were issues if you tried to construct a boundary around the sweep that included the origin point (mostly having to do with introducing collinear walls). I am not certain that remains a problem. Boundary shapes are intersected last ,so the collinear wall bit is not an issue. 

It is conceivable that intersecting a boundary shape with a sweep polygon could end up with a null intersect, or an intersect of only part of the sweep, if the origin were not included within the boundary, which is why that padding step is there. Might be worth checking, however, if that is a real issue or not given the current code. Maybe we can drop padding altogether.
