### ISSUE TITLE
Package updates should not suggest a user upgrade to a non-stable Version of Foundry

### ISSUE THREAD

**Issue by Geekswordsman** [foundryvtt/foundryvtt#7583]
### User Experience

When updating modules, if the module has a new version _but_ it is for a different version of Foundry than the person is running, Foundry will tell the user as such.

This message is the same even if the new version of Foundry is not yet stable.

Proposition:
Adjust the workflow such that _either:_
A) Foundry checks if the new version of the core software has a stable branch, and if not informs the user in the message.
_or_
B) Foundry will report "No Update Available" if there are no new versions of the module for the current version of the core Software.

Benefit:
Reduce the potential for users to look to upgrade to a development/test branch of FoundryVTT due to thinking it is stable as a result of these messages.

**Comment by aaclayton** [comment]
I don't see a clear path towards accomplishing this issue, not in the scope of the testing phase of development. Given a remote manifest that declares a minimum Foundry VTT version, the currently running version of Foundry has no idea whether that generation+build number is stable or not.

**Comment by Geekswordsman** [comment]
But it does know that there isn't an update available for *this* version of Foundry, so option B is possible and just report that there is no update available for the module

**Comment by Geekswordsman** [comment]
(sorry for close and reopen, fat finger on mobile)

**Comment by Geekswordsman** [comment]
Another alternative:

If the detected new version of a module is for a newer version of Foundry, a new option that could be given is to "lock all modules requiring a new version of Foundry."

This option would present a dialog pop-up explaining what that means and how to undo it, and offer a confirmation that the user wants to enable the locks on all affected modules.

This will properly "lock" the modules in and prevent them from seeing the (potentially very long) list of modules unable to be updated each time they go to update - particularly while a new version of Foundry isn't stable yet.

_Even better_ would be if said lock could be "limited" to the version of Foundry they're on - so if they update the core version of Foundry, foundry will check the version on that lock and remove it.

**Comment by plutoneld** [comment]
My 2c:
The problem seems to be that how the information is conveyed drive users to update to a testing release, likely prematurely.

Imo it doesn't make sense to display this as a warning. A warning is something the user likely want to fix. Instead it should be displayed as information to the user, simply: "There is a newer version of this module for core software version 10.“

The advise/warning regarding testing releases is shown if the user then decides to change channel, so it doesn't need to be put beside every module that might have an update for v10.

If this happens to a module requiring an updated core software released on the stable channel, ie minor version update, the notification for core software update should be more than enough to nudge them.
