### ISSUE TITLE
[Bug]: templateDocument.object.ray undefined in the createMeasuredTemplate hook

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7595]
### What happened?

templateDocument.object.ray undefined in the createMeasuredTemplate hook. I expect it to be defined as it was in v9

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a measure template

Try logging templateDocument.object.ray in the createMeasuredTemplate hook.

ray will be undefined.

After creation the ray object will then be availeble. This was not the case in v9 as the ray object was already defined in the createMeasuredTemplate hook.

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We intentionally changed some workflows of the measured template to do less work on initial document creation and to defer that work for when the object is drawn. This was an intentional change in V10. 

Depending on your use case, a better approach for V10 may be to use the `drawMeasuredTemplate` hook (which fires when objects are drawn to the canvas) instead of the `createMeasuredTemplate` (which applies to document creation)
