### ISSUE TITLE
Allow OS-provided fonts to be added to worlds via the FontConfig UI

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7610]
Originally reported by JDW#6422 https://discord.com/channels/170995199584108546/956306859491471420/1000203950965932172

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Chrome  
**Short Description of bug:** When adding a custom font without specifying a font file in order to add a system font, the font is not added to the list available font in the editor because the FontConfig.#available.add is done at the end of the FontConfig.loadFont function which return false the line before because it could not "load" the font file. The font is still added to the list of Custom Font, but can't be selected anywhere.  
**Simple steps to reproduce the bug:** Open the Custom Font window, add "Arial Black" or "Papyrus" and click 'Add Font'  
**Screenshots and/or console errors:** "Font family "Arial Black" failed to load:  DOMException: A network error occurred."

I'm not sure if system fonts should be able to get added here but one way or the other, there is a bug.

**Comment by aaclayton** [comment]
For some environment, a font may be a system font and might work without a file. For other clients though that font may not be a system font. Without an actual font file we couldn't guarantee that the font will work for all users. This might be okay, just need to decide what our intention is.

**Comment by Fyorl** [comment]
Yeah, the font config UI was only ever intended to allow a GM to select a font from their foundry assets and make it available to connected clients. We have an option via the programmatic API to enable certain system fonts, if that's what a package wants to do, but that's not something that the font config UI was designed for.

**Comment by JiDW** [comment]
One argument for system fonts is that some fonts for large Unicode text (Arabic/Chinese/etc) can be heavy to load as a font-face. They exist on everything but some Linux distro. For example, the default Chinese font on Windows is 20mb for a single weight.

Setting the URL as optional (and changing the loading behavior to accept an empty field) would be enough to fix this issue.

**Comment by Fyorl** [comment]
Still, the font config UI was not designed for declaring system fonts. It's not very obvious that you should leave the font file blank, and there should be no need to declare different weights and styles for a system font, for example. So, while we could consider enabling that functionality, it would require some further iteration. If there are indeed certain language fonts that are widely available, I think it would be better to include them in foundry's core font definitions since there is almost no overhead associated with such definitions (just a single `document.fonts.check`), rather than having each GM separately enable them in each world via the UI.

**Comment by JiDW** [comment]
Ok, understood, thanks for the feedback. 
May I suggest some extra system fonts then maybe?

Based on my own perceived usefulness and availability as reported on https://www.cssfontstack.com/

Verdana => Very high availability to give an alternative to Arial
Georgia => Very high availability, a good alternative to Times New Roman
Papyrus and Copperplate => Very good availability for these "fantasy" fonts. Can be used to create some cool looking Journal entries
Brush Script MT => Good availability to have at least one cursive font. Once again, very useful for creating "letter-like" journals

If you wish to provide some universal fonts however, there is no good multi-platform choice. 

The open sourced font created by Adobe and Google (Noto) is not available by default and is too heavy to be bundled in Foundry by default. The users will have to download a limited font family and use it as a font face. This is obviously not an amazing UX for these users but I guess it is good enough and a much better experience than in previous versions.

**Comment by Fyorl** [comment]
We can consider these for addition, but in an earlier comment you mentioned fonts with Unicode support for Arabic and Chinese that existed on 'everything but some Linux distros'. Those I think we would definitely want to register as system fonts if you happen to know which ones they are.

**Comment by JiDW** [comment]
Sorry for the misunderstanding, I mixed some elements there. I don't think you wish to register those fonts yourself.

1- These fonts are sometimes different depending on the OS
2- Those are not "universal" fonts, you will find fonts for chinese, fonts for russian, fonts for korean, etc. The only universal font I know of is "Noto" and it is not possible to load it as a font face (it's more than a hundred of megabytes)
3- For some language like chinese, you will have to register multiple variant. Like fonts for traditional chinese and simplified chinese, and to have some usefulness you would also need to register one font for serif and sans-serif. There is also cursive variants!

So just for chinese, you would need to register twelve fonts to match what you can do in 3 latin fonts.

That's why it was a cool feature/bug to be able to register system font yourself because you know who are your players and adapt your choice. However I agree that the UI was not meant for this and that most foreign players would have never guessed it was even possible.

If you wish to ever extend the number of available fonts for cyrilic/chinese/korean/etc, I think it will have to be either with a UI that is compatible with system fonts, or alternatively, it could be something done by the Core translation modules. They would know what system fonts are the best  for their language without filling the font list of every users with dozen of useless fonts.

**Comment by Fyorl** [comment]
OK, I think I understand a lot better now, thanks. That does sound like we should do the work to improve the font config UI so that it can be used to intuitively register system fonts.

The best solution, however, does seem to be to have core translation modules register those fonts in `CONFIG.fontDefinitions` though. That way, the GM does not have to register them themselves on every world they create.
