### ISSUE TITLE
Add a strict requirement that Actor, Item, and Adventure compendium pack types declare the system which they are compatible with, either directly or indirectly via package relationships.

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#7636]
## Implemented Change

Packages which include compendium packs with the "Actor", "Item", or "Adventure" type must designate the `"system"` field which clarifies the ID of the game system that those packs are designed for.

This can be done in one of two ways, indirectly via package relationships which is **preferred if possible** or directly via the compendium pack definition itself.

### Indirect Declaration via Relationships
A package which only works for a single game system can declare that singular system dependency in the `"relationships"` field thusly:
```js
"relationships": {
  "systems": [
    {"id": "pf2e"}
  ]
}
```
For packages which only support a single game system (i.e. the length of the "systems" array is 1) that game system will be automatically inferred for any compendium packs of the "Actor", "Item", or "Adventure" type.

### Directly via Compendium Pack Data
In addition to or instead of the above method a system can be declared explicitly on the compendium pack itself. This is necessary in cases where a module supports multiple game systems.
```js
"packs": [
   {
      "name": "adventure",
      "label": "Pathfinder Beginner Box",
      "path": "packs/adventure.db",
      "type": "Adventure",
      "system": "pf2e"
  }
],
```
Packages which include a compendium of type "Actor", "Item", or "Adventure" and do not clarify the system that pack is intended for will fail validation and that compendium pack will be unavailable to be loaded inside Foundry VTT.

-----------------------------

## Original Comment Below

Reported by `@Toasty#8538` 

Adventures that support multiple systems can run into issues where the import will attempt to import documents for both systems when importing. Having the adventure import check `game.system.id`  and filtering the list of importable Documents to match the game system by `DOCUMENT._stats.systemId` would resolve this (based on conversation with Toasty and Arcanist, i think i agree).

**Comment by aaclayton** [comment]
Comment by @toastygm

### What happened?

When an Adventure document is Imported, if there are Actors or Items in the Adventure that were made for a different system than the current world, those Actors or Items will be unusable (and may cause problems).

Any Actors or Items built for any other system than the current world system should be ignored and not imported.

USE CASE: I create an adventure, such as a Dwarven ruin; Journals, Scenes, and Rolltables are usable by any system.  But my Actors are for the HM3 system.  People using DND5E should be able to import the adventure, just ignore the Actors.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

Create an Adventure containing Actors and Items in DND5E.
Create a new world using any system other than DND5E, and Import the Adventure.


### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by toastygm** [comment]
I think only Actors and Items should be affected, because those are the only documents that are system-specific.  All other documents are system-agnostic.

**Comment by aaclayton** [comment]
I tentatively disagree with this request. An adventure document must exist within a compendium pack. A compendium pack should target one (and only one) system. That's why compendium packs support designating a `system` (singular) and not `systems` (plural).

To ship a module which provides an adventure for multiple game systems, the package manifest should be configured thusly:

```json
{
  "id": "my-adventure-module",
  "title": "My Adventure Module",
  "description": "Supports both dnd5e and HM3!",
  "packs": [
    {
      "name": "adventure-dnd5e",
      "type": "Adventure",
      "path": "./packs/adventure-dnd5e.db",
      "system": "dnd5e"
    },
    {
      "name": "adventure-hm3",
      "type": "Adventure",
      "path": "./packs/adventure-hm3.db",
      "system": "hm3"
    },
  ],
  "relationships": {
    "systems": [
      {"id": "dnd5e"},
      {"id": "hm3"}
    ]
  }
}
```
This is the proper way to support shipping an adventure for multiple systems. You may have other opinions and wish it worked different, but this is the correct way to go and trying to have cross-system support within a single compendium pack is going to lead down the path of pain.

**Comment by toastygm** [comment]
So then an Adventure may only target a single system.  You may not have an Adventure that is usable by multiple systems.

Your logic is that every Adventure compendium has a single "system" designation.

Given the simplicity this issue suggests, I would ask you to reconsider.  This would allow a single adventure to be used by multiple systems, and would simply ensure that such adventures do not import incorrect items or actors into a particular world.

Note that this will occur if a user creates an Adventure, but doesn't specifically mark its system as "DND5E", and it is subsequently imported into a world running another system.  Since there is no system designation on the compendium pack, it will try to be imported, with resulting errors because the Actors and/or Items are incompatible.  This would protect against that situation.

Unless EVERYONE uses the system designation with Adventure packs, this case will occur.

**Comment by toastygm** [comment]
Another comment: There is no reason why a Journal, Scene, or Rolltable compendium pack should specify a system.  Those are not system-specific.  Only Actors and Items are system-specific.

Adventures need not be system-specific either, so long as we can manage the logic of not importing any Actors or Items that are not compatible with the world system.

**Comment by theripper93** [comment]
You should make you system specific compendiums, specific to the system, i don't see where the problem is. Then make your scene\rolltable etch, not require a system

**Comment by toastygm** [comment]
Now I have to have two or more compendiums: one Adventure compendium for the Journals, Scenes, etc.  And another set of Adventure compendiums for the Actors and Items.  To load an adventure, now I have to load TWO adventures, one with the system-specific stuff, and another with the system-agnostic stuff.

Or, I have to create "n" separate Adventure compendiums, each with mostly duplicate Journals, Scenes, and Rolltables in them, but with different Actors and Items.

This does not seem friendly to people using my system (case 1) or very friendly to the adventure developer (case 2).

**Comment by toastygm** [comment]
To be clear, I can work around this using the "preImportAdventure" hook, but I was hoping for a more base product support than that.  But I understand if you feel this is against your philosophy on how Adventures should be used.

**Comment by mattexdee** [comment]
I would note that while roll tables and journal entries are not system specific their content often times are like document links to actors and items. To support those most adventures will need system specific versions of the journals and roll tables anyway. As a result I would recommend a compendium pack per system with everything included in the adventure.

**Comment by dhorkin** [comment]
This is wild - I have a roll table that is 100% system agnostic. All the results are just text. There is 0 reason why this should have to be set to a single system.

**Comment by mattexdee** [comment]
@dhorkin There is no requirement for a compendium pack (adventure or otherwise) containing roll tables to be set to a single system. Only packs which contain system-specific content (Actors or Items) require a game system to be listed.

**Comment by dhorkin** [comment]
This is wild - I have a roll table that is 100% system agnostic, and a corresponding Item compendium that is strictly PDFs, nothing system specifc. There is 0 reason why this should have to be set to a single system.

I have worked around this by making an incredibly boilerplate module.json that references the same .db file multiple times with different system specifiers.

**Comment by mattexdee** [comment]
> a corresponding Item compendium that is strictly PDFs, nothing system specifc

Due to how Foundry VTT works, items are inherently system specific as the game system defines what constitutes an item. An item created in DnD5E can not be used (without issues) in PF2E for example. If you would like to include a number of PDFs representing items I would recommend creating them as journal entries which are system agnostic and could be included in a compendium pack without assigning a system.

**Comment by toastygm** [comment]
@aaclayton specifically rejected my original request (see above).  He specifically indicates that all Compendiums must be assigned to a specific system.  When I pointed out that only Items and Actors need to be system specific, the idea was rejected.  In fact, @aaclayton specifically changed the code in v10 to require that Compendiums must belong to a single system.  His terms were:
> A compendium pack should target one (and only one) system...This is the proper way to support shipping an adventure for multiple systems. You may have other opinions and wish it worked different, but this is the correct way to go...
I'm not sure why there is still discussion when @aaclayton made his decision so very clear.

**Comment by mattexdee** [comment]
> I'm not sure why there is still discussion when @aaclayton made his decision so very clear.

@toastygm I responded because that was not the route that was ultimately followed after community and internal discussion and the issue title was updated to reflect that more closely. Only Actor and Item compendium packs must define a system. Adventure compendium packs must define a system *only* if they include content that is system-specific like Actors or Items.

You may feel free to load up V10 and create a compendium pack without a system to see for yourself.

**Comment by toastygm** [comment]
@mattexdee My original intent behind this issue was to allow for "Adventure" documents that could be used in multiple systems.  I currently have modules that include Scenes and Journal Entries (which are system-agnostic), as well as Actors.  I provide Actors for D&D5e, SWADE, and HârnMaster systems.

The idea would be that for a person using DnD5e, when they import my adventure it would import the Scene and Journal Entry items, and it would import the D&D5e Actors (but not the SWADE or HârnMaster Actors).  This allows me to have a single Adventure which can be used across multiple systems; it is simply that those parts that are not relevant to the system would not be imported.

The alternative, which I currently use, is to use a third-party module (ScenePacker).  Using ScenePacker, I can have my module contain one Scene compendium and one Journal compendium (with no system specified), and have three Actor compendiums, one for each system I support, and each with the "system" set appropriately for the compendium.  This works.  The main issue is, _this is not an Adventure document._ It is a module controlled by Scene Packer.

It would be much nicer if the Adventure document supported this mechanism natively.

**Comment by mattexdee** [comment]
@toastygm, I'm not questioning your original intention, just trying to let you know how things wound up in the end to prevent confusion because the statement that all compendium packs require a system was not accurate. While I can understand what you're asking for and why you would want it (and I empathize with the frustration that it's not doable currently), it's unfortunately not something that was able to be included in the first iteration of the Adventure document but may be something that can be included in a future version. Very few Foundry features do everything all of our users want in their first version but we do try to improve them as time goes on and hopefully we'll be able to fully capture your use case at some point. I appreciate the feedback in the meantime as it's always good to know how users want our features to expand.

**Comment by aaclayton** [comment]
Hey folks, just FYI. We did end up reconsidering that requirement, see https://github.com/foundryvtt/foundryvtt/issues/8262.

Adventure compendium packs are not *required* to declare a specific `system` that they are designed for. If the Adventure does not declare a specific system, it will not be able to package `Actor` or `Item` documents, but you can create a system-agnostic Adventure containing other document types like Scenes, Journal Entries, Roll Tables, Audio Playlists, etc...

Sorry that this got lost in the history of this issue, we should have posted a comment here linking to #8262 and clarifying that change was made.
