### ISSUE TITLE
`ControlLeft` and `ControlRight` not firing keybinds in some situations

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7661]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/872553750877835264/1002451248055853167

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux Mint Chrome  
**Short Description of bug:** Ctrl keybindings aren't firing  
**Simple steps to reproduce the bug:** Register a keybinding with this code:  

```js
Hooks.on("init", () => {
    game.keybindings.register("ctg", "test", {
        uneditable: [{ key: "ShiftLeft" }, { key: "ShiftRight" }, { key: "ControlLeft" }, { key: "ControlRight" }],
        onDown: () => console.log(true),
        onUp: () => console.log(false),
    });
});
```

Notice that pressing Shift prints to the console, but not Ctrl.

**Comment by aaclayton** [comment]
@cswendrowski could you suggest a set of debugging steps that Arcanist could follow in order to collect some data that would help us understand what is happening here?

**Comment by cswendrowski** [comment]
> @cswendrowski could you suggest a set of debugging steps that Arcanist could follow in order to collect some data that would help us understand what is happening here?

The general flow for debugging keybindings:
`CONFIG.debug.keybindings = true`, type your keyboard command, dump the logs

For this specific bug report, a Modifier key is trying to be set as a `key`, which is not valid for our system. The bug here is that we allow Modifiers to be used as Keys in any context

**Comment by arcanistzed** [comment]
@cswendrowski The code snippet I am using (see above) doesn't print any logs for me even with `CONFIG.debug.keybindings = true` enabled.
 I'm using this to create a click & keybinding combination as recommended during the v9 migration. i.e. I'm toggling the value of a Boolean variable in `onDown`/`onUp` which is checked whenever the user clicks on certain buttons. Is there a different approach you can recommend?
 I think it would be unfortunate to have to tell all of my users to use a different keybinding for this because using a modifier key is more intuitive and what they're used to.

**Comment by cswendrowski** [comment]
Upon review, my memory was incorrect - we did add support for setting `key` to things such as `ControlLeft`, and this is the correct workflow for things like "Was control held during this action?"

Upon testing, however, this functionality and example registration are working correctly. More info needed to reproduce - @arcanistzed can you verify this is still occurring in the latest, and if so, what browser & OS you are using?

**Comment by arcanistzed** [comment]
I can't reproduce it anymore actually. Even on previous versions of FVTT where I definitely had the issue. I think it's probably because I updated my OS recently.
