### ISSUE TITLE
Relax the `ToursManagement` signature to inherit from the base `Application` instead of `FormApplication` which provides unnecessary functionality.

### ISSUE THREAD

**Issue by kmoschcau** [foundryvtt/foundryvtt#7696]
### What happened?

The `ToursManagement` class can throw when `_updateObject` is called on it, because it does not override the default implementation in `FormApplication`, which just throws.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Type `ToursManagement` and type check.
See the checks in this PR: https://github.com/League-of-Foundry-Developers/foundry-vtt-types/pull/2096

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Relevant log output

```shell
Error: src/foundry/client/apps/sidebar/apps/tours-management.d.ts(4,15): error TS2515: Non-abstract class 'ToursManagement' does not implement inherited abstract member '_updateObject' from class 'FormApplication<FormApplicationOptions, Data<{}, FormApplicationOptions>, {}>'.
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I'll try to get this fixed - but please understand Foundry VTT is *not* a TypeScript project, and while it is best practice for subclasses to implement all abstract methods - it isn't strictly required. For cases where an app behaves like a form, but does not have an object update workflow this doesn't represent a core Foundry VTT bug, but rather a problem with trying to force TypeScript into this space.

Either way, I'll plan for us to make a change to either subclass `Application` instead of `FormApplication` or to implement a noop `_updateObject` method.

**Comment by kmoschcau** [comment]
I completely understand your point. The only reason we have this as abstract is because the FormApplication implementation explicitly throws with an error saying so. And since this method can also be called as a side effect from other methods, my first hunch would also be to override it with a no-op.

**Comment by aaclayton** [comment]
Outcome here is changing it to inherit from `Application` instead of `FormApplication` (which was unnecessary).

**Comment by kmoschcau** [comment]
Hi, with `ToursManagement` (and others) now extending `PackageConfiguration` in 278, this is now happening again.
