### ISSUE TITLE
Add a user permission for deleting tokens

### ISSUE THREAD

**Issue by itamarcu** [foundryvtt/foundryvtt#7765]
### What happened?

Repeating [conversation from discord](https://discord.com/channels/170995199584108546/956307084931112960/990301108993925180):

> does V10 suddenly allow players to delete their owned tokens from the scene, unlike previous versions?  I don't see this in any release note, but it apparently works with no modules enabled.

> might have been a side effect of some other changes

> it either needs to be rolled back, or needs a confirmation dialog
otherwise too easy to mistakenly hit the delete key

> Looks like it was something between V10.262 and V10.270, because 262 doesn't allow that while 270 seems to

I've replicated this without modules in multiple systems.

---

FYI, I'd much prefer to add a confirmation prompt than to just remove this feature.  It's something a lot of people have asked for, and I've even [created a module to allow it](https://github.com/itamarcu/allow-players-to-delete-their-tokens).

### What ways of accessing Foundry can you encounter this issue in?

At least Chrome

### Reproduction Steps

1. Put a player-owned token on the map
2. Log in as a player
3. Select the token
4. Press the Delete key

### What core version are you reporting this for?

Version 10 Testing 1 (build 277)

### Bug Checklist

- The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We will make a change here, but we can consider keeping the behavior to allow players to do this with a confirmation prompt. I personally am not sure what the use cases are for players deleting tokens, but I'm certain there are reasonable ones for many games.

**Comment by itamarcu** [comment]
The use cases are generally:
- Player has a summon/companion/familiar, who isn't around the party all the time
- Player accidentally dragged an extra token, leaving 2 on the scene, and now wants to remove the extra one
- Player wants to fix a problem with an old token that has been fixed with a prototype token update, and easiest fix is to delete and re-add the token

I searched the discord for "player delete token" and found lots of results - at least 12 different users in the past 8 months asking how to enable player token deletion.

**Comment by unsoluble** [comment]
If the behaviour is going to stay available, I think it makes the most sense to add it to the Permission Config screen.

**Comment by Fyorl** [comment]
After spending some time reviewing the difference in behaviour between v9 and v10, the v10 behaviour appears to be somewhat as designed. In v9, the `testUserPermission(user, "OWNER")` check as part of `canUserModify(user, "delete")` would always return `false` because `TokenDocument`s did not have a `permission` field at all. In v10, `BaseToken/TokenDocument`s inherit their ownership from the actor they represent. So if the user owns the actor, they are allowed to perform any operation on the token, per the logic in `canUserModify`.

It's possible that there was just an error in v9 that happened to preserve the intended behaviour so it was not spotted at the time, but I didn't go any further back than v9.

For now, I will tentatively reframe this issue as adding an extra user permission for deleting tokens, and remove the bug tag.

**Comment by itamarcu** [comment]
@Fyorl could you also add a confirmation message, perhaps only for non-GMs?
