### ISSUE TITLE
Constructing a `DataModel` mutates property descriptors on passed source

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#7796]
### What happened?

When a source object is passed to a `DataModel` constructor, the same source is operated on rather than a copy, making for undesirable side effect of (at the very least) mutated property descriptors.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

In Foundry V10.277, dnd5e alpha:
```js
source = game.items.getName("My Spell").toObject()
new Item.implementation(source)
Object.getOwnPropertyDescriptor(source, "_id")
```

![Screenshot from 2022-08-09 11-57-39](https://user-images.githubusercontent.com/106829671/183712197-f8d72656-3661-4b1e-b815-965745f85f27.png)

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Mutation of the source object provided to a `DataModel` constructor is expected behavior. When you provide source data to a `DataModel` instance, the data model now fundamentally *owns* that source and is free to do with it whatever is required including things like applying migrations, etc... 

If you want to construct a data model instance from source data that should not belong to the resulting instance you must clone it yourself first.
