### ISSUE TITLE
SquareGrid#getGridPositionFromPixels Parameters and Return Inconsistency

### ISSUE THREAD

**Issue by EndlesNights** [foundryvtt/foundryvtt#7825]
### What happened?

getGridPositionFromPixels takes in the parameters of `x, y` or `width, height` and returns an array with the conversions from canvas pixels coordinates to the relative grid. However the array returns in a reversed order to the parameters so we end up with an array that is `[y,x]` or `[height, width]` which is just a strange way to return grid coordinates, and can lead to unassay confusion while while interacting with this method.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

This is the current code
```JS
  /** @override */
  getGridPositionFromPixels(x, y) {
    let gs = canvas.dimensions.size;
    return [Math.floor(y / gs), Math.floor(x / gs)];
  }
  ```

I would have expected it to be this
```JS
  /** @override */
  getGridPositionFromPixels(x, y) {
    let gs = canvas.dimensions.size;
    return [Math.floor(x / gs), Math.floor(y / gs)];
  }
  ```

### What core version are you reporting this for?

Version 10 Testing 1 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
I realize this is a bit confusing, it's something I perhaps want to change in the future - but it's not a bug. "Grid Positions" are expressed as `(row, col)`. Since rows are on the `y` axis and columns are along the `x` axis this creates the behavior you are seeing.

The reason for this is that typically "row" and "column" are expressed in that semantic order rather than "column,row". A redesign or next generation of our grid system for a future major release might change this.

One comment based on your initial issue report, the parameters for grid units are **NOT** `width` and `height`, but rather `row` and `column` - an important distinction.
