### ISSUE TITLE
Cannot view journal PDF pages hosted on S3

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7843]
Originally reported by Phi#4271 https://discord.com/channels/170995199584108546/956306859491471420/1009251406378704926

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows11 / Any  
**Short Description of bug:** Cannot view a journal PDF page that points to an absolute URL for a PDF hosted online on S3.  '/' is getting prepended to the URL, causing a 404 since it is looking in local data. If manually removing the '/' so that the route points online, then getting 'file origin does not match viewer's'.  
**Simple steps to reproduce the bug:** Reproduced in v10.277. Add a new PDF page to a journal and point it to an external URL.  
**Screenshots and/or console errors:** 

![image](https://user-images.githubusercontent.com/207433/185138655-9e8cdbba-4c58-4218-8c1e-e81e85204698.png)

![image](https://user-images.githubusercontent.com/207433/185138753-303261ed-febf-4013-8175-0034e77683d4.png)

![image](https://user-images.githubusercontent.com/207433/185138842-128c1c11-c122-4f44-886e-d087e5b579ea.png)

![image](https://user-images.githubusercontent.com/207433/185138930-f7514f17-05ba-405b-8d93-f8b5a7b9d7bb.png)

**Comment by kakaroto** [comment]
Note: As mentioned by @rikmarais, by removing the `/` prefix from the url and using `https://gameurl.forge-vtt.com/scripts/pdfjs/web/viewer.html?file=https://assets.forge-vtt.com/userid/DnDBeyond/lmop/dwarf-cleric.pdf` that also fails with a different error due to the origin not matching.
![image](https://user-images.githubusercontent.com/27990/185199655-0641d2a0-8e8f-475e-a5ea-b70be081c35f.png)

This is the code in the viewer that causes it : 
![image](https://user-images.githubusercontent.com/27990/185199702-f125dcfc-8951-4f8e-8255-86d198ab18a7.png)

That `HOSTED_VIEWER_ORIGINS` variable that checks for allowed origins is a const inside an inaccessible scope and hardcoded to just `mozilla.github.io` so this doesn't look like it's even customizable.
The issue isn't so much with the pdf.js library but with the viewer's explicit deny of cross origin requests, with the funny comment "it is not guaranteed to work" (so they make it guaranteed to fail)

That `throw` should be removed from that function (https://stackoverflow.com/questions/39373329/pdf-js-cors-issue) and something worth noting from the stackoverflow above, is that if it's an S3 url which includes authentication arguments, you'd need to make sure those get properly urlencoded so they become part of the file url, rather than arguments to the viewer itself.
I hope this helps.
