### ISSUE TITLE
Change verbiage of "Safe Configuration" to "Safe Mode"

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7876]

**Comment by mxzf** [comment]
I'm pretty sure it was named "Safe Mode" at some point in the past (the game-worlds KB page still has that in a screen shot).  I suspect it was changed for a reason, likely because "Safe Mode" implies a mode that can be toggled back off, which does not accurately reflect what that setting does and is prone to confusing users.

**Comment by unsoluble** [comment]
It would sure be a major win for the feature to actually retain/restore module loadout (I know, not the original scope here).

**Comment by unsoluble** [comment]
Back within scope: If you're just tweaking text and _not_ adding retain/restore, I think it would be reasonable to add a description to the setting, describing what it does in brief and being clear that it's a one-way alteration.

**Comment by aaclayton** [comment]
This is intentionally called safe "Configuration" rather than safe "Mode" because of the way the feature works. It enacts some one-time configuration changes to the world. It is specifically *not* a "mode" which actively works in a different way than normal "mode". The term "Configuration" here was intentionally chosen.
