### ISSUE TITLE
Lighting/Vision Features on an Token should render below the Token

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/foundryvtt#7967]
### User Experience

Currently, when a lighting or vision feature is applied to a token, any rendering overlays the token art which can cause the token to be hard to see. It would be preferable for the lighting or vision feature to apply under the token, even if this is a user-specific option in the world.

**Comment by aaclayton** [comment]
I'm sorry to hear that our approach of rendering lighting/vision above the Token (so that it affects that token's artwork) is not what you would prefer. Unfortunately we have no plans to make changes to this behavior. It would be possible for a module to make an alteration to this - although it is not an easy module to write. 

Sorry this is not the answer you were hoping for.
