### ISSUE TITLE
Headings in ToC are duplicated

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8024]
Originally reported by arcanist#4317 https://discord.com/channels/170995199584108546/956306859491471420/1014390758880583770

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Linux Mint Chrome  
**Short Description of bug:** Headings in ToC are duplicated  
**Simple steps to reproduce the bug:** Updating the document fixes the issue until the page is reloaded  
**Screenshots and/or console errors:** (there should only be `0. Introduction` and a single pair of `Introduction` and `Scaling` headings)

![Image](https://user-images.githubusercontent.com/207433/187977813-3c1b61ae-8c0f-4535-b624-ffa406759b4c.png)

**Comment by Fyorl** [comment]
Closed as nonrepro

**Comment by zeel01** [comment]
This may be related to an issue I was having, where I would:
- Create a Journal with multiple pages with headings in them, all in one create event
- Open the Journal
- Update it with similar data (mostly all the same, but with minor changes)
- In some cases, the ToC would then contain duplicated entries.

Refreshing (F5) the application would correct the ToC, presumably because this deletes the cached apps.

**Comment by arcanistzed** [comment]
I can reproduce in 10.284 with this world script (which I use as a stop-gap for #8009):
```js
const JOURNAL_OPTIONS = { 
     mode: JournalSheet.VIEW_MODES.MULTIPLE, 
     collapsed: true 
 }; 
  
 const rendered = new Set(); 
 Hooks.on("renderJournalSheet", app => { 
     if (rendered.has(app.id) || !app.document.getFlag("world", ID)) return; 
     rendered.add(app.id); 
     app.render(true, JOURNAL_OPTIONS); 
 }); 
  
 Hooks.on("closeJournalSheet", app => { 
     rendered.delete(app.id); 
 });
```
