### ISSUE TITLE
Chat message rendering failures can prevent the entire chat log from rendering.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8051]
### What happened?

reported from https://discord.com/channels/170995199584108546/956306859491471420/1014918886631690401

Honestly I don't know, it's like the chat has been disabled ONLY on this campaign (this is the strange thing; I have another campaign on Foundry where the chat works)

![image](https://user-images.githubusercontent.com/66535080/188095570-eafc7535-6f78-49d8-bab3-9c2d1c880a47.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

reported from https://discord.com/channels/170995199584108546/956306859491471420/1014918886631690401

### What core version are you reporting this for?

Version 10 Stable

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
There's definitely some error which is breaking the user's chat log rendering, but we probably can't do anything about it unless we get them to give us the error messages from their dev console.

**Comment by Akexis** [comment]
I'm having the same problem, found this:

`foundry.js:711 TypeError: Failed to render Sidebar tab chat. Cannot read properties of null (reading 'isSelf')
    at get isAuthor [as isAuthor] (foundry.js:17683:22)
    at get visible [as visible] (foundry.js:17723:19)
    at ChatLog._renderBatch (foundry.js:73042:16)
    at ChatLog._renderInner (foundry.js:73014:16)
    at async ChatLog._render (foundry.js:4965:19)
    at async ChatLog._render (foundry.js:59441:5)
    at async ChatLog._render (foundry.js:73005:5)
    at async Promise.all (index 2)
onError @ foundry.js:711`

This is the error I'm getting, but I'm also getting A LOT of data errors, dozens of them.

`commons.js:1250 Error: You are accessing ItemT2K#data which has been migrated to ItemT2K#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1239:19)
    at ItemT2K._logDataFieldMigration (commons.js:6132:14)
    at Object.get (commons.js:6096:18)
    at ItemT2K.prepareData (item.js:110:27)
    at ItemT2K._safePrepareData (foundry.js:13153:12)
    at Game.initializeDocuments (foundry.js:7819:18)
    at Game.setupGame (foundry.js:7732:10)
    at async Game._initializeGameView (foundry.js:8820:5)
logCompatibilityWarning @ commons.js:1250`

**Comment by Oshcakes** [comment]
Just want to point out that we have seen 2 users report this issue today on the forge as well.  
![image](https://user-images.githubusercontent.com/61471647/188256230-71f422c8-724c-43aa-a2d7-5ef07400affa.png)

**Comment by Fyorl** [comment]
Seems to be caused by `ChatMessage#user` being `null`. We can smooth over that check so that it doesn't crash and prevent the sidebar from rendering, but there are a number of places in `ChatMessage` where `user` is assumed to exist. It's a required field in the schema with `nullable: false` so it might bear some further investigation as to how these messages are ending up initialised to `null`.

**Comment by aaclayton** [comment]
My expectation of what *should* happen is that an author-less document would be invalid and end up in the `game.chat.invalidDocuments` set and - because its invalid - would not be in the `game.messages` collection at all and wouldn't be attempted for rendering in the log. 

The interesting bug here is why we attempt to render a message which is (or should be) reported as invalid.

**Comment by arirawr** [comment]
I am also experiencing this issue - happened right after deleting 2 users who had previously been in a game and thus had chat messages that would have been attributed to them.

Is there any workaround or do I need to wait for a patch?

**Comment by Fyorl** [comment]
@arirawr The workaround at the moment is to clear your chat log. Otherwise this should be patched in the next release either today or tomorrow.

**Comment by Akexis** [comment]
How do you close the chat log if you can't see the chat window?

**Comment by Fyorl** [comment]
You have to do it via the console:

```js
game.messages.flush();
```

**Comment by Akexis** [comment]
THANK YOU. Saved me!
