### ISSUE TITLE
The vision and lighting polygons are sometimes wrong.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8052]
### What happened?

reported from https://discord.com/channels/170995199584108546/956306859491471420/1014939043500396676

Vision and lighting sometimes goes through walls, sometimes interacts with walls that aren't there.
Hosted on a Raspberry pi 3b Linux 5.10.60-v7+ armv71

![image](https://user-images.githubusercontent.com/66535080/188097498-9498370a-a5c5-4e7a-9f80-f74e55ae21ae.png)
![image](https://user-images.githubusercontent.com/66535080/188097525-114e6b53-b20a-4f25-975c-7dfed0484b4d.png)
![image](https://user-images.githubusercontent.com/66535080/188097541-d66a7c48-bac2-4fd5-9a49-7d7ab1837b33.png)

[fvtt-Scene-caverns-of-ooze-copy.zip](https://github.com/foundryvtt/foundryvtt/files/9476265/fvtt-Scene-caverns-of-ooze-copy.zip)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

See attached zipped file.
`fvtt-Scene-caverns-of-ooze-copy.json`

### What core version are you reporting this for?

Version 10 Stable

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We'll have to check the attached .json to see for sure but I suspect that there are actually gaps in the walls.

**Comment by Feu-Secret** [comment]
Reproduced the creation of an incorrect polygon with the help of a user and Unsoluble (see attached json file with the reproduced use case).

![image](https://user-images.githubusercontent.com/66535080/195447699-71820d11-afbc-4905-9be8-e588c93f8d99.png)
[fvtt-Scene-ambushed-reinforcements-(copy-broken).zip](https://github.com/foundryvtt/foundryvtt/files/9768671/fvtt-Scene-ambushed-reinforcements-.copy-broken.zip)

**Comment by caewok** [comment]
At first glance, that looks like an active edge is present when it should have been dropped. Probably edge 34|38 is still in the active edges set when at somewhere around vertex 68-74. 

Edge 78|83 is also not displaying the correct LOS, but they may resolve itself if the active edge issue is fixed. 

My guess is that the edge 34|38 does not quite touch the vertical line at 38. This is causing the algorithm to place a collision 39 very near 38 and may be causing problems. We have seen such bugs in the past but thought we fixed that issue. It is annoyingly difficult to resolve because basically the underlying algorithm is correct; it is just getting bad info on where the endpoints and collisions are, usually related to rounding.

**Comment by dev7355608** [comment]
The test case `fvtt-Scene-ambushed-reinforcements-.copy-broken.zip` shows no error anymore in the current V11 build. It's not entirely clear what caused it exactly. It seems to be fixed.
