### ISSUE TITLE
Provide a migration for worlds with invalid characters in their `id`

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8068]
### User Experience

If v10 is going to reject apostrophes (and I presume other invalid characters) in world `id`s, it ought to provide an auto-migration to a new `id` (along with changes to any paths referencing the old name/id).

**Comment by aaclayton** [comment]
I find it hard to believe that such worlds were tolerated by V9, but I suppose there is evidence that they were. Certainly the software would not create such worlds. I'll have to think about the best way to handle this - migrating a world `id` is easy to get started with but could have some nasty side effects because of all the (potential) asset file path references that might exist and break.

Better to break those URLs than to have an entirely broken world though.

**Comment by unsoluble** [comment]
I couldn't believe it either, so popped into v9 to test — sure enough, it'll happily create a world with an `id` and folder with an apostrophe in it.
