### ISSUE TITLE
Placing walls around the scene causes vision to render incorrectly

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8097]
Originally reported by alaustin#0963 https://discord.com/channels/170995199584108546/956306859491471420/1016020535735504907

**ALL MODULES DISABLED?** TRUE  
**OS, Hosting, Browser (if applicable):** Win10, Electron  
**Short Description of bug:** Vision calculates incorrectly until walls surrounding the canvas are removed.  
**Simple steps to reproduce the bug:**
1) Import provided scene JSON
2) Place token anywhere on the map. Global Illumination, lights, or vision radius make no difference.
3) Select the four walls surrounding the canvas at the edge of the padding and delete them.
4) Vision now calculates perfectly.

![image](https://user-images.githubusercontent.com/207433/188446990-4b9a8d22-f3b2-4d82-8189-1d215004df34.png)

![image](https://user-images.githubusercontent.com/207433/188447007-c5307c2f-2191-41cd-9ef0-90bd8f749642.png)

![image](https://user-images.githubusercontent.com/207433/188447050-493290f2-8d67-4d03-84cb-7889d200d845.png)

[fvtt-Scene-dwarven-excavation.zip](https://github.com/foundryvtt/foundryvtt/files/9489680/fvtt-Scene-dwarven-excavation.zip)

**Comment by caewok** [comment]
Foundry sweep should probably ignore walls in line with canvas or scene edges. Such walls add zero information to the scene and are probably throwing off the algorithm somewhere because it is not anticipated that walls would entirely overlap other walls. 

Might be also worth testing where walls in a scene overlap and are collinear. Wouldn't be surprised to see bugs with that setup.

**Comment by Fyorl** [comment]
Some additional information in a separate report:

Originally reported by Wockawocka#3961 https://discord.com/channels/170995199584108546/956306859491471420/1016729291410649230

> I was easily able to reproduce similar behavior by simply extending a solid wall beyond the canvas of the background image.  As soon as you do that, vision breaks.

**Comment by aaclayton** [comment]
I was able to narrow this down quite a lot. The root cause of the issue is a wall to the WEST of the origin where both endpoints of the wall are outside of the canvas bounds.

![image](https://user-images.githubusercontent.com/2468703/189175547-8bb6943e-9855-4e9d-aef7-be3a6b2bd9cd.png)

This has simplified the repro case considerably, but I have not yet solved why this happens or how to best fix it.

**Comment by aaclayton** [comment]
Have a solution which I believe will address this and other related issues.

**Comment by unsoluble** [comment]
This issue does not appear to be completely resolved as of 10.291.

Repro steps for the attached Scene:

1. Control the `Zephyr` token (in the middle-right of the scene).
2. Use Control-mousewheel to rotate its vision, note that it blanks out entirely when facing West.
3. Delete the one wall segment that runs across the North bounds of the scene, note that the vision cone now works as expected.

[fvtt-Scene-bm_-swamp-no-hut-berez.json.zip](https://github.com/foundryvtt/foundryvtt/files/10198221/fvtt-Scene-bm_-swamp-no-hut-berez.json.zip)

**Comment by aaclayton** [comment]
@unsoluble would you mind opening this as a new issue which references this one?
