### ISSUE TITLE
Once a button is clicked, disable Tour button controls until next Step is rendered to prevent double-clicks

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8208]
Originally reported by ghost#2000 https://discord.com/channels/170995199584108546/956306859491471420/1020096297077837876

**ALL MODULES DISABLED?** false (creating a custom Tour via a module...)  
**OS, Hosting, Browser (if applicable):** irrelevant  
**Short Description of bug:** While an asynchronous `_preStep` or `_postStep` of a `Tour` is executed , the user can still interact with the tour tooltip (like closing it, or moving a step forward/back). This can result in very weird and unexpected behavior, for example when closing the tour while an asynchronous `_postStep` is running, the tour will first wait for it to finish, then close the tooltip, then briefly open it for the next step, and then close it again. A similar behavior  can be seen when closing the tour during an asynchronous `_preStep`.  
**Simple steps to reproduce the bug:**
* Create a tour with an asynchronous `_preStep` or `_postStep` (e.g. waiting for a `setTimeout`)
* Start that tour
* Progress a step, triggering the `_preStep` / `_postStep`.
* While that is still running, click the close button in the tour tooltip.
* Observe the weird behavior.

**Comment by aaclayton** [comment]
Probably makes sense to disable pointer events before pre or post step workflows and re-enable them after.

**Comment by ghost91-** [comment]
I would recommend to do that at the beginning/end of `progress`, since it does a bit more async stuff, I believe. And IMO it makes sense to not be able to progress, while already progressing.

For now, as a workaround, I simply keep track of whether a `progress` is currently in progress (the wording here sucks… 😅), via a property, and just return at the start of `exit` and `progress`, if that property is set to true, and also show a notification to avoid user confusion. But the UX would definitely better if it was more obvious to the user that they can’t interact during that time, e.g., by marking the buttons in the tooltip as inactive.

You can see my workaround here: https://github.com/ghost-fvtt/fxmaster/blob/tours/src/tours/mixins/actions.js#L42
