### ISSUE TITLE
The ProseMirror editor toolbar drop-downs can cause the editor content to overflow

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8212]
Originally reported by stwlam#3718 https://discord.com/channels/170995199584108546/956306859491471420/1020214196379590666

**ALL MODULES DISABLED?** for sure  
**OS, Hosting, Browser (if applicable):** Debian 11, Electron application  
**Short Description of bug:** The ProseMirror editor's toolbar has undesirable overflow behavior  
**Simple steps to reproduce the bug:** Open a long menu  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/190634934-ca260a41-5b1d-4019-a5c5-878c748f9fb8.png)

**Comment by Fyorl** [comment]
A result of using a CSS-only drop-down implementation, so currently 'working as designed', but can be improved if we instead use javascript to position these elements.

**Comment by aaclayton** [comment]
Boosting the priority on this issue because it sounds like from #10801 that this is the top reason blocking Pathfinder 2 from switching to ProseMirror.

**Comment by CarlosFdez** [comment]
Looking forward to it! Yeah unfortunately our habit of adding things to menus and also using editors in areas with less space like character biographies and hazards and kingdom settlements made this one a dealbreaker.

I'll start seeing about pre-emptively getting prosemirror ready to go so that we can flip the switch later.
