### ISSUE TITLE
 Token opacity modified by "Toggle Visibility State" resets when moved

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8228]
From https://discord.com/channels/170995199584108546/956306859491471420/1020310312022454273

Simple steps to reproduce the bug: 
 - Create a token
 - Enter token configuration
 - Set token opacity to zero
 - Exit token configuration
 - Click Toggle Visibility State
 - Move Token

**Comment by Fyorl** [comment]
This is what I can observe when following the reproduction steps:

1. Create a token.
2. Open token configuration, set opacity to 0, save settings.
3. Token fades out to full transparency.
4. Click toggle visibility state.
5. Token fades back in to semi-transparency.
6. Move the token.
7. Token moves and fades back out to full transparency.

It seems like the bug is not that the token returns to full transparency when moved in (7), but actually that it becomes semi-transparent in (5). If you subsequently toggle the hidden state off, the token becomes fully opaque, completely ignoring its opacity setting (and the token is fully visible on connected clients).
