### ISSUE TITLE
Server-side journal auto-save sometimes causes client to not update its state correctly

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8461]
Originally reported by Rvby#9420 https://discord.com/channels/170995199584108546/956306859491471420/1036098021781418005

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10 / Editing via Foundry App, V  
**Short Description of bug:** Journals do not save correctly.  
**Simple steps to reproduce the bug:**  
Open a journal and create a page, then edit that page.  
Enter some text.  
Leave the page alone for some time (not sure exactly how long. Maybe 10 minutes? I've had inconsistent results)  
Note that when you close the journal or click save, the changes are not saved. I've inconsistently had this issue continue (preventing me from saving changes) until I open another window or close and reopen the journal editor.

**Comment by rocketgarden** [comment]
Just came here to report this as well. I've been experiencing it since v10 dropped but only got around to diagnosing with modules disabled today. Notably the journal actually _does_ save (sometimes?), even if the client state doesn't update. 
i.e. If you open, make some edits, wait, click save, see journal not update, refreshing the Foundry UI at this point will actually reload with the previously invisible edits. (If you reopen and re-save before refreshing though I think it will then overwrite with the stale version)

But yeah this is *really* annoying when I'm sitting down to do session planning and the journal breaks every 10-30 minutes

**Comment by aaclayton** [comment]
Reported by @pesky-wobbit:

### What happened?

Sometimes journal pages do not save.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open a page for editing. 
Make changes.
Wait for a minute or two.
Hit Save.
**No save occurs.**

Workaround: open editable page and originating page side-by-side. When a save fails, add a space to the open page and immediately save it again. Save now works. It will be reflected in the originating page.

I'm sure others have lost a ton of work because of this bug!

Best guess: an attempt is made to autosave the edited page, flagging it as not having been edited. But the autosave doesn't actually work.

Note in the picture below that I've hit the save button and no changes are reflected in the original page. When I closed and re-opened the edited page, the changes were lost.

![Screenshot 2022-11-09 092513](https://user-images.githubusercontent.com/477446/200856849-9155f125-e1fa-4668-bf68-4ca87923ee7c.jpg)


### What core version are you reporting this for?

Version 10 - Build 288

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled
