### ISSUE TITLE
Add a property to `DetectionMode` that controls whether the mode is limited to the vision angle

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8482]
### User Experience

The name of `DetectionMode#walls` suggests that the LOS check performed by `_testLOS` is strictly wall-based. But the LOS polygon may be constrained either by the Vision Angle or by a module that wants to limit the maximum range of light-based perception. Those constraints are unrelated to walls but are applied regardless to all detection modes with `walls: true`, because `_testLOS` uses the LOS polygon. Detection modes with `walls: false` ignore the Vision Angle even though the angle is unrelated to walls.

There should be a separate property that controls whether the mode is limited to the vision angle. A sense may be directional (limited to the vision angle) but ignore walls (example: x-ray vision). A sense may be omnidirectional (not limited to the vision angle) but restricted by walls (example: smell, hearing).

**Comment by caewok** [comment]
I agree, but I think if you do this, you probably need to cache the different LOS polygons in some manner. Changing VisionAngle and/or maximum range would, of course, change the LOS polygon. Given the possibility of multiple detection modes, you would want to keep the default LOS polygon for a given VisionSource and then construct additional ones on-demand. Otherwise, testing multiple points with multiple detection modes will quickly become unworkable. 

You could set up caching in `VisionSource.prototype._createPolygon` and wipe the cache on `VisionSource.prototype.initialize`, for example. 

Related: #8484.

**Comment by Feu-Secret** [comment]
@dev7355608 @aaclayton I think we should requalify this issue as a bug. With `walls: false`, we should take into account the angle and direction to test visibility. We don't need an extra parameter (for the moment, maybe for a future version). Thoughts?
If we are going this way, we could add it to the v11 testing 2 milestone.

**Comment by aaclayton** [comment]
I'm okay with that if you think the scope and timing are appropriate to work on for V11.
