### ISSUE TITLE
Text drawings with long text labels cannot be resized via the drag handle

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8488]
Originally reported by MaxPat#7936 https://discord.com/channels/170995199584108546/956306859491471420/1038152763927953508

**ALL MODULES DISABLED?** true  
**Short Description of bug:** Text Drawings with long text labels cannot decrease the width via the drag handle, the Drawing config dialog must be used to reduce width and adjust the text wrapping.

Not sure if using the drag handle to reduce width is a feature request or a bug, or if reducing the width of a text drawing is not intended at all due to Atros comment on issue #6996 , but I think that reducing the width should be supported by both the drag handle and drawing config dialog  
**Simple steps to reproduce the bug:** Create a text drawing with a relatively small width, enter a Text Label that is long enough to wrap within that width, adjust the width via the drag handle, observe that you can increase the width but not decrease it, use the Drawing config dialog to reduce the width, observe the drawing box is resized and text wrapping is adjusted.  
**Screenshots and/or console errors:**

https://user-images.githubusercontent.com/207433/200316669-aa9df91e-0a19-425d-936a-ff6c3768c38c.mp4

**Comment by aaclayton** [comment]
This is currently an intentional design for both UX and performance reasons. Currently adjusting the width of the drawing in a drag workflow does not cause the text to be re-rendered, only to be repositioned within the drawing frame. 

Re-rendering PIXI text every frame of a drag workflow would be worse for performance and also creates a UX issue where you cannot minimize the drawing size conditional on a certain text without creating imprecise overflow.

Maybe this could be redesigned in the future, but I don't view it as a high priority given the current UX is intentional.
