### ISSUE TITLE
Add standard elevation and sort fields for Drawing documents so they can be perfectly organized relative to other objects in the Primary Canvas Group.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8498]
### What happened?

Pre 10.286 the z-index of drawings was merely a tiebreaker. 10.286 broke this behavior. Now the z-index is the elevation. Anyone who had drawings with negative z-index must have wondered where their drawings have gone, because those are now behind the background image; drawings with larger z-index than the foreground elevation suddenly appeared on top overhead tiles. This change also affected Perfect Vision; the effect it had is similar to what would happen to tiles if core suddenly made the z-index the elevation of tiles.

This breaking change should be reverted.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We made this change as a result of https://github.com/foundryvtt/foundryvtt/issues/8058. We are stuck in V10 between two bad behaviors.

1. We need users to have some control over the elevation of drawings so that those drawings can be rendered above foreground tiles when necessary.
2. We missed the boat to make data schema changes to accomplish this.

We need to - for V10 - repurpose the `z` field to control elevation of drawings. The true solution which we will make in V11 is to add `elevation` and `sort` fields to Drawings so they can be fully and perfectly ranked relative to Tokens, Tiles, and other inhabitants of the PrimaryCanvasGroup.

While I acknowledge this causes some disruption, it is not a change we will revert because users having control over the placement of their drawings is a lesser evil than always rendering drawings below the foreground.

**Comment by dev7355608** [comment]
This should be listed as a breaking change on the website then. It doesn't feel good that a breaking change was done in the third stable release. I'm forced to override this behavior with Perfect Vision. How are you going to migrate this to once the elevation field is added? Initialize the new elevation field with the old z value in order to not break it again? But this would break things for PV users, and I have to correct it by forcing all elevation fields to 0 in my migration. It's just a big mess.

**Comment by aaclayton** [comment]
Once we add explicit `elevation` and `sort` fields (likely in V11). The current value of the `z` field will become `elevation`.
