### ISSUE TITLE
Folders expanded during sidebar search are not restored to their original pre-search state when the search is cleared

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8518]
### What happened?

Clearing text from the Actor search box expands all folders.

Original post: https://discord.com/channels/170995199584108546/956306859491471420/1040309701944029365

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

![glitch](https://user-images.githubusercontent.com/66535080/201621598-4335df8e-449e-41f6-899b-9d735a87a302.gif)

### What core version are you reporting this for?

Version 10 Stable Build 290

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
I believe this is working as intended. I think what's happening is the initial search prefixes are matching several items inside folders, and the folders are being expanded to show this. When the search field is cleared, the sidebar returns to showing all folders, and those that were expanded remain expanded.

The same behaviour can be observed by searching for some document that you know exists inside a collapsed folder, then manually backspacing to delete the search term. The folder will remain expanded.

**Comment by Fyorl** [comment]
Removing bug tag and re-framing this as an improvement to retain expanded folder state and return to it when the search is cleared.

**Comment by tophatraptor** [comment]
@Fyorl Hi! I was also running into this and followed up from the Discord channel, wanted to maybe flag a few things for consideration:

- This behavior is new to at least this version of Foundry (V10). It's fairly disruptive for folks who have a lot of actors organized into folders.
- From testing with 0.8.9, the previous behavior was to save the initial actor folder state, display/expand folders as needed to show results, and restore the initial actor folder state.

**Comment by Fyorl** [comment]
Thank you for the additional context. If it's indeed a regression, we can take a look at addressing in v10.

**Comment by cswendrowski** [comment]
![Image](https://user-images.githubusercontent.com/15639841/204409310-54b74605-e239-41d9-a5da-01d435fa608d.gif)


This is working as intended - in the first search, collapsed folders stay collapsed. In the second, the expanded folder remains expanded after being opened - this is intended, as otherwise the document you just searched would disappear again.

**Comment by tophatraptor** [comment]
> This is working as intended - in the first search, collapsed folders stay collapsed. In the second, the expanded folder remains expanded after being opened - this is intended, as otherwise the document you just searched would disappear again.

@cswendrowski the example you provide above is a good one-off test case to check the behavior, but as I sort of noted above, this behavior is problematic when you have a more built-out actor library, because it expands _**every**_ folder with a result in it, even after you're done. 

Example video: https://drive.google.com/file/d/1kL-76jJgq9y3wXhE2qQEdD1jqJh5O2RW/view?usp=share_link

I have tokens imported from DDB which, to my understanding, is not a rare setup for folks running 5e, organized into folders by creature type (Aberration, Beast, Fey, Fiend, Dragon, etc). The importer I use (MrPrimate) has some ~9.7K users on the monthly patreon subscription.

If I search "Dragon", for instance, I get matches in Aberration ("Elder Brain Dragon"), Beast ("Dragonfly"), Humanoid, Monstrosity, and Undead. However, when I clear search, I'm left with all of these folders fully expanded and showing all their results, and I have to close them one by one to get back to the original list. If I start typing and pause for any reason, I'm likely to get most of my folders expanded.

The old behavior was much better in this situation, since you could already do everything you need to do with this token once it's been found it using search. I rarely need to go back to a token once I've already added it to the map or edited it.

The current behavior seems to be trading off a very minor bump in convenience for smaller libraries against making the experience much worse for people who, either manually or through automated tools, happen to have a lot of tokens on hand, which is when search is most useful.

**Comment by cswendrowski** [comment]
@tophatraptor thanks for advocating for this change - we have targeted a small tweak that should help your case. Observe new behavior here: 
![folder searching 2](https://user-images.githubusercontent.com/15639841/204583865-5c5cfa03-c7e9-4c27-b952-f0ee4e0acb6d.gif)
