### ISSUE TITLE
Add package persistent storage folder

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#8590]
@cswendrowski I want to discuss this with you for V11 scoping.

**Comment by cswendrowski** [comment]
# High Level Design

## package.json opt-in flag
Addition of new manifest field. Setting to true would indicate the package persistent folder should be managed 
`persistentStorage: true`

## /package.persistent/ folder

A secondary folder of form `<moduleID>.persistent` would be created if the opt-in flag is set, and deleted when the package is removed. This form uses characters not valid for module ids (`.`), and so there should not exist any collisions.

Since the name is of a consistent form, it should be fairly easy to create and delete the folder as needed. The folder would be created if the opt-in flag is true and it does not exist yet, and would be deleted when the package is uninstalled.

## API changes

`FilePicker.uploadPersistent(moduleId, path, file, body={}, {notify=true}={}`
A convenience method that writes to a relative path of the persistent folder. Throws an error if the module is not opted-in.
