### ISSUE TITLE
Roll Data is not preserved on toJSON method

### ISSUE THREAD

**Issue by elizeuangelo** [foundryvtt/foundryvtt#8671]
### What happened?

Roll Data is not preserved on toJSON method:
```
toJSON() {
    return {
      class: this.constructor.name,
      options: this.options,
      dice: this._dice,
      formula: this._formula,
      terms: this.terms.map(t => t.toJSON()),
      total: this._total,
      evaluated: this._evaluated
    };
```

There should be an additional property on the method: `data: this.data`.

This results in rolls being wrongly copied depending on the system implementation.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```
a = new Roll('1d6', {success: 6});
b = await a.toMessage();
b.data.success === a.data.success;
```

### What core version are you reporting this for?

Version 10 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
The documentation for `Roll`'s `data` parameter is:
> The data object against which to parse attributes within the formula

After invoking `new Roll`, the attributes should already be replaced, so it's not clear that the roll data should be serialised, since it's no longer needed for its intended purpose.

There are some issues with the reproduction steps listed here also:
```js
a = new Roll('1d6', {success: 6});
b = await a.toMessage();
b.data.success === a.data.success;
```

`a.toMessage()` returns a `ChatMessage` instance, so there should not be an expectation that `a.data` (`Roll#data`) is the same as `b.data` (`ChatMessage#data`). `ChatMessage#data` is also a deprecated property.

Providing an attribute in the formula does correctly produce the same results, post-serialisation:
```js
const a = new Roll('1d6 + @success', {success: 6});
const b = await a.toMessage();
b.rolls[0].total === a.total; // true
```

**Comment by elizeuangelo** [comment]
You are absolutely right. I confused the function of both options and data properties.
