### ISSUE TITLE
Active Effect remaining duration does not update outside of Combat encounters.

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8691]
### User Experience

In v9 `ae.duration.remaining` used to be a getter, which made it excellent for this.

But with v10 it was turned into derived data filled via _prepareDuration which is only(?) updated if combat is active, making it unusable for tracking remaining time outside of encounters, despite Foundry using time tracking outside of them. This was a sneaky breaking change that I do not believe was ever mentioned.

To deal with this, however, forces system devs to re-implement the old behaviour elsewhere, or call the _prepareDuration() function whenever they need it, which makes it more awkward than it used to be. System agnostic modules in turn need to simply re-implement the entire math on their side to deal with the issue.

It would be better if the v9 behaviour was restored, or additional getter or function on AEs was introduced to do such basic functionality in core once again.

**Comment by aaclayton** [comment]
It certainly was not our intention to make a "sneaky" change on this - but some re-orientation of the way that data models was definitely necessary with the V10 release.

Ideally what the core software needs to do is:

1. Maintain a record of all Active Effects which are currently active in the world.
2. When the game time changes (whether because of a combat round/turn or otherwise) re-prepare those active effects

This needs to be carefully handled, but is important work to do.

**Comment by mkahvi** [comment]
I honestly don't see why it can't be getter still. Either directly defined in the model, or via Object.defineProperty() in the constructor in case there's problems because of SchemaField usage.

**Comment by aaclayton** [comment]
> I honestly don't see why it can't be getter still. Either directly defined in the model, or via Object.defineProperty() in the constructor in case there's problems because of SchemaField usage.

This was largely an efficiency consideration. `effect.duration` can be called many times during the course of rendering an application or performing a workflow. If the duration is computed in a getter each time it's inefficient compared to storing the computed duration value when (and only when) effect document data is prepared.

A hybrid approach of using a cached getter where the duration cache is invalidated as part of document prep would be a "best of both worlds" but also would be special case code rather than simply a standard prepared document attribute.

I'll add this to our slate to take a final look at before locking down v11 functionality.

**Comment by mkahvi** [comment]
Currently any such code will instead get stale value or undefined instead, which may need special handling, costing resources elsewhere. Not sure why any rapid rendering code would check this, but I guess that's valid concern if there is such.
