### ISSUE TITLE
When exporting a Document, include the document id for uniqueness

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8703]
If you have scenes of the following setup:
/My Cool Adventure/
  /Floor 1/ 
      Bathroom
  /Floor 2/
      Bathroom
      
Both of the Bathroom scenes will export as `fvtt-Scene-Bathroom.json`, causing duplicates. Including at least the parent folder such as `fvtt-Scene-Floor1-Bathroom.json` or possibly all parents such as `fvtt-Scene-MyCoolAdventure-Floor1-Bathroom.json` would reduce duplicates and help find the relevant file

**Comment by aaclayton** [comment]
I do not like this suggestion for a few reasons:

1. The exported filename would change as content is reorganized within the world
2. Many documents do not have a folder name so the file naming convention would be inconsistent
3. The name of the containing folder still does not ensure uniqueness under certain organizational schemes

If we want to ensure uniqueness of the exported filenames I would suggest appending the document ID in addition to the slugified name rather than the name of the containing folder.
