### ISSUE TITLE
Allow Playlist documents to have configurable Ownership. Players who are owners of playlists can manage the playback of that playlist themselves. Add a PLAYLIST_CREATE permission level which controls which players have permission to create new Playlists.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8707]
# Create Playlist

Gates CRUD operations on Playlists. Defaulted to GM + Assistant.
Should also gate play / stop / loop functionality.

The control buttons should be disabled without permission

**Comment by aaclayton** [comment]
I think this needs to be expanded and generalized to support the ability for certain players to have the ability to manage audio. I feel that this is a much larger issue that we probably shouldn't try to tackle in V11.

**Comment by anathemamask** [comment]
Proud to declare that my PR for this was accepted with a few small changes. Under guidance from Atropos this was my first ever PR to the core software. 

It introduces Document-level permissions for playlists, allowing users to be granted control over playlists so that they can take the responsibility of maintaining the soundscape for the GM if they're familiar with it!
