### ISSUE TITLE
Active Effect documents failed to invoke the parent Actor#canUserModify method which allowed them to be incorrectly modified while inside a locked compendium pack.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8718]
Originally reported by Zhell#9201 https://discord.com/channels/170995199584108546/956306859491471420/1058411829359030342

**All modules disabled?** true  
**Short Description of bug:** A script can create embedded documents on a document in a locked compendium.  
**Simple steps to reproduce the bug:**  
Using the dnd5e system's SRD heroes compendium,

```js
const actorDoc = await fromUuid("Compendium.dnd5e.heroes.kfzBL0q1Y7LgGs2x");
await actorDoc.createEmbeddedDocuments("ActiveEffect", [{label: "Steve", icon: actor.img}]);
```

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/212116360-9d433498-6588-4f6d-a416-f1611942c644.png)

**Comment by aaclayton** [comment]
It tuns out that this issue was specific only to `ActiveEffect` - attempting to create Items inside an Actor in a locked compendium correctly prevents the change:

![Image](https://user-images.githubusercontent.com/2468703/234904798-a98727eb-58af-47e9-8f51-e1595d486531.png)

The issue for Active Effects in particular has to do with our lack of override to redirect the `canUserModify` check on the document to the parent when the AE is embedded.
