### ISSUE TITLE
Remaining light transition when scene Darkness Level is zero

### ISSUE THREAD

**Issue by paulohdsc** [foundryvtt/foundryvtt#8735]
### What happened?

It is possible to see a light transition between token's vision and scene's lighting when scene Global Illumination is enabled and Darkness Level is set to zero.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create a new scene with no background image
- Enable Token Vision and Global Illumination and set the Darkness Level to zero
- Place a token on the canvas with vision enabled, Vision Range 10 ft, and no light
- Select the token
- What happens: you can see a light transition between the token's vision and the scene's lighting
- Expected: no transition, as Global Illumination is enabled and the Darkness Level is set to zero

https://user-images.githubusercontent.com/75817094/212573628-f7e3cd83-b6b6-4cd2-a249-15031fe3807d.mp4

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is currently working as designed, but we understand that it is a somewhat controversial design choice. There are reasons we do it this way so that there is a very subtle but perceptible visual feedback when moving a token around a map. We may change our approach here in the future, but this isn't something we are currently considering making changes to.
