### ISSUE TITLE
Light has no effect on token vision

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8781]
Originally reported by n0qtrnL#2610 https://discord.com/channels/170995199584108546/1065764070680186930/1066040326701195335

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Arch Linux, Self Hosted. Tried Brave, Chrome, and Firefox  
**Short Description of bug:** Light has no effect on tokens seeing other tokens.  
**Simple steps to reproduce the bug:** Put two tokens into a scene with Token Vision enabled. Set one token with Vision Enabled, no vision range, and Basic Vision. Select this token and the other token will vanish.

**Comment by dev7355608** [comment]
Detection modes don't work either at the moment if the token's vision range is 0, because the vision source is disabled if the radius is 0. `RenderedPointSource#_isActive` and this is part in `CanvasVisibility#testVisibility` are the problem:
```js
// When global light is active, we need to test basic sight LOS, even if the vision source has a radius of 0
if ( !visionSource.active && !canvas.effects.illumination.globalLight ) continue;
```
Global light is just a light source like any other light. It shouldn't affect vision sources like that. Vision sources should be active unless disabled:
```js
class VisionSource extends RenderedPointSource {
  /* ... */

  /** @override */
  _isActive() {
    return !this.disabled;
  }

  /* ... */
}
```

**Comment by aaclayton** [comment]
Is this a V11 bug? Or a v10 bug? What do you mean by "at the moment"?

**Comment by dev7355608** [comment]
> Is this a V11 bug? Or a v10 bug? What do you mean by "at the moment"?

11.292

**Comment by Feu-Secret** [comment]
This is fair. Vision should not be disabled according to the radius.
