### ISSUE TITLE
Add new token conditions like Flying, Hovering, and Burrowing, to allow better interactions with detection modes and other system mechanics

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#8783]

**Comment by stwlam** [comment]
Would these be arbitrary annotations one could add to a token, or is the idea to add a particular set of them?

**Comment by aaclayton** [comment]
> Would these be arbitrary annotations one could add to a token, or is the idea to add a particular set of them?

We need to do some careful scoping and documentation of this issue before implementing anything. I suggest that @Feu-Secret start with a write-up of the problems we want to solve and our proposed path to doing so. We can then revisit questions you have.

**Comment by caewok** [comment]
In [Elevated Vision](https://github.com/caewok/fvtt-elevated-vision) v0.4, I added a “fly” button so when automatically changing token elevations based on terrain, the user could indicate if the token should fly or stick to the ground (i.e., fall). 

Having thought about this functionality a bit, I think fly and burrow are useful indicators. I would focus on indicators of a token’s physical location: burrow, ground (likely the default state), fly, hover, ethereal, crawl/crouch, swim. (You can see a tension here where “in the water” might be a better descriptor of location than “swim,” which suggests an ability.)

Some things to consider:
1.  Base Foundry currently has no real sense of terrain elevation, only token elevation. So it would be difficult to automatically set a token physical status without something like Levels or Elevated Vision, where terrain elevation is known. For example, a token 50’ high could be flying, could be on a 50’ hill, or could be burrowing under a 100’ hill. 
2. Because of (1), a more useful tool would be to allow the user to indicate whether their token is flying, burrowing, etc. This should also be easily settable by systems and modules. 
3. If the user is setting status, then things like hover vs fly are workable. Automatically distinguishing between the two, however, is difficult. 
4. It would be preferable to have a set of physical descriptors for tokens for which their physical meaning do not substantially change between systems. For example, fly status should always mean not in contact with ground. This is so various modules could expect similar information transfer when used in different systems. Perhaps systems could “skin” the descriptors with names, symbols, etc, but the underlying physicality would be expected to be comparable. 
5. As physical descriptors of token state, I would expect only one status to apply at a time. (Unlike effects.) While there are other ways to set this up, there is a certain power and simplicity to having only one state apply at a time. This suggests that invisibility is an active effect, not a physical descriptor, but ethereal might be a physical descriptor if you mean “not fully present in this plane.”
