### ISSUE TITLE
Update documentation for `PointSource#shape`. shape could be a `PointSourcePolygon` or a `PIXI.Polygon`.

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8820]
### What happened?

`PointSource#shape` must be a `PointSourcePolygon` according to the documentation.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
canvas.effects.globalLightSource.shape instanceof PointSourcePolygon // false
```

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
We don't want to force source shapes to be polygons, so I think the documentation needs to adapt here. Ideally `source.shape` should be any valid PIXI shape: circle, rect, polygon, etc... We may have some work to do in order to get there because of some existing assumptions that the shape has methods or attributes of a `PointSourcePolygon`.
