### ISSUE TITLE
Remove the `scalingFactor` parameter from `PIXI.Polygon#signedArea` and make the method a getter

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8854]
### User Experience

I don't think `scalingFactor` would be needed ever. The parameter would only be necessary if you wanted to know the area of the rounded polygon but didn't need the rounded points for some reason: I can't imagine a scenario where that would be the case. The current `signedArea` is also very inefficient because of all the objects it creates. I suggest to remove `scalingFactor` and make it a getter:
```js
/**
 * The signed area of the polygon (see `ClipperLib.Clipper.Area`).
 * The math behind this is based on the Shoelace formula. https://en.wikipedia.org/wiki/Shoelace_formula.
 * The area is positive if and only if the orientation of the polygon is positive.
 * @type {number}
 * @readonly
 */
Object.defineProperty(PIXI.Polygon.prototype, "signedArea", { get: function() {
  const points = this.points;
  const n = points.length;
  if (n < 6) return 0;
  let area = 0;
  let x1 = points[n - 2];
  let y1 = points[n - 1];
  for (let i = 0; i < n; i += 2) {
      const x2 = points[i];
      const y2 = points[i + 1];
      area += (x2 - x1) * (y2 + y1);
      x1 = x2;
      y1 = y2;
  }
  return -0.5 * area;
}});
```

**Comment by caewok** [comment]
Adopting the above for calculating signed area makes sense to me, but with a few caveats:

1. The reason for the scaling was because otherwise a polygon created using Clipper will return a different area than a polygon created here.  I actually ran into this problem with Alt Token Visibility, because I needed to compare the area of a token shape with one that was run through Clipper. If you want the areas to match, you have to use the same scaling for both. But to the extent that is needed, it might be worth just making a separate method if the above is much faster, or just ignoring it until you have a use case. (It is a bit surprising, however, when you compare two polygons that should be the same and find they have different areas due to scaling of one in Clipper.)

2. Iterating through the points of the polygon to calculate area is non-trivial for large polygons and will incur performance costs. Thus I still think `signedArea` or `isClockwise` should be cached. I discuss this in my comment to #8855. As the orientation test depends on `signedArea`, caching the area would be sufficient.
