### ISSUE TITLE
Unblock Web Components for usage in Foundry

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8889]
Currently, web components are somewhat usable in Foundry, but `input` elements largely don't work due to the Keybinding system not knowing when a shadow form element is focused.

Additionally, we should provide helpers to attach the Foundry styles:

```js
        // Create link to Foundry css
        const foundryStyle = document.createElement('link');
        foundryStyle.setAttribute('rel', 'stylesheet');
        foundryStyle.setAttribute('href', 'css/style.css');

        // Create link to Font Awesome
        const fontAwesomeStyle = document.createElement('link');
        fontAwesomeStyle.setAttribute('rel', 'stylesheet');
        fontAwesomeStyle.setAttribute('href', 'fonts/fontawesome/css/all.min.css');
        
         // Add to shadow dom
        shadow.appendChild(foundryStyle);
        shadow.appendChild(fontAwesomeStyle);
```

**Comment by wyrmisis** [comment]
Any chance this might make it into an upcoming major release? I've found Web Components to be a fantastic way to isolate functionality/styling in system work, and would love to see broader support for keyboard navigation and hooking them into the sheet update flow with less boilerplate.

**Comment by aaclayton** [comment]
This issue is tagged to the V12 project board, so there is certainly a chance we'll be doing some work here. We already added a little bit of use of WebComponents in V11 that pave the way for doing more here. 

It's already possible to integrate web components with sheet update flow as long as you register a `formdata` event for your component that adds whatever data it should include to the `FormData` object that is being processed for the sheet. Read https://www.dannymoerkerke.com/blog/web-components-can-now-be-native-form-elements/ for context and see the `multi-select` element in core for a working example to follow.

**Comment by aaclayton** [comment]
We feel that the current scope of support for webcomponents is working well with now a number of example elements to reference
