### ISSUE TITLE
`getUserLevel` doesn't return `OWNER` for GMs that didn't create the document

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8962]
### What happened?

I assume `getUserLevel` should always return `OWNER` level permission for GMs. But that is only the case for the GM that created the document. `document.ownership` contains `OWNER` permissions for creator GM, but there are no entries for other GMs. So `getUserLevel` returns the default permission level. If a user was upgraded to GM, it returns the old permission that the user had over the document.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create an actor.
2. Create another GM.

```js
actor.ownership // { default: 0, creatorGM: 3 }
actor.getUserLevel(otherGM) // returns 0; expected 3
actor.testUserPermission(otherGM, "OWNER", { exact: false }) // returns true as expected
actor.testUserPermission(otherGM, "OWNER", { exact: true }) // returns false; expected true
```

### What core version are you reporting this for?

Version 10 Stable 6 (build 291) / Version 11 Prototype 1 (build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by farling42** [comment]
Note that the ownership won't contain the correct ID for a GM if the document was imported from an Adventure compendium. Instead, the next time that the default ownership is changed, the old "gm" id is removed from the ownership record, leaving the ownership as only containing a single "default" property.

**Comment by aaclayton** [comment]
The `getUserLevel` method is specifically written and intended to return the *explicit* permission level that a User has for a certain Document, regardless of that user's role. I have updated the `getUserLevel` docstring as follows:

```
Get the explicit permission level that a User has over this Document, a value in CONST.DOCUMENT_OWNERSHIP_LEVELS.
This method returns the value recorded in Document ownership, regardless of the User's role.
To test whether a user has a certain capability over the document, testUserPermission should be used.
```

What you are encountering with the `{exact}` parameter of `.testUserPermission` is also expected. The use case for this is, for example, "does this user have LIMITED (and only LIMITED) permission to a certain Document". It's important that this *does not* return `true` for GM users. 

I have updated the logic of `testUserPermission` to change the order of testing so that GM users are interpreted as having the `OWNER` level therefore they will "exact match" against OWNER but not LIMITED.

The end result is that your expectations are met, but in a different way than your suggestion implied.
