### ISSUE TITLE
Make `BaseActor#type` and `BaseItem#type` `readonly`

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9030]
### User Experience

Currently the `type` fields of `BaseActor` and `BaseItem` are defined in their schemas as mutable, but it is difficult to imagine a sane use case for ever changing the fields' values on a given document--and unintentionally changing them is likely to cause unpredictable failures. Such failures can happen in V10 when importing an actor or item of one type over an existing one of a different type.

![image](https://user-images.githubusercontent.com/106829671/224184281-b7c5cfea-7422-44ca-8e59-34339c8120c2.png)

**Comment by aaclayton** [comment]
The landscape here has changed quite a bit in V11 due to https://github.com/foundryvtt/foundryvtt/issues/7521

V11 handles documents with an invalid `type` in a more specific way now (partly related to https://github.com/foundryvtt/foundryvtt/issues/8571). There is some requirement that this field be mutable because documents which become invalid due to their `type` can be relegated to the universal `base` type and later recovered or migrated to some other valid type (related to https://github.com/foundryvtt/foundryvtt/issues/8647).

I would encourage you to do a bit of testing in V11 around this issue and report back with further thoughts or findings.

**Comment by stwlam** [comment]
That's all different enough that my suggestion doesn't quite make the same sense it does for V10.
