### ISSUE TITLE
Map and everything on it disappears every hour or so

### ISSUE THREAD

**Issue by olilan1** [foundryvtt/foundryvtt#9176]
### What happened?

Roughly every hour or two during play, the map and everything on it disappears, leaving only a grey background. The rest of the UI, including the chat window and tools, remains in place.

In the console I see an error saying `THREE.WebGLRenderer: Context Lost` - full stack trace below.

I've seen this in two separate games, one running on Forge VTT, and one on a self-hosted Linux server. Both PF2e. Other players in the same gams don't have this issue. I've tried on two different PCs and seen the same issue occur - one Windows 11, the other Windows 10. Both using Chrome.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Log in to server and play normally.
Issue occurs every hour or two.

I have not been able to identify a particular action that triggers the issue.

### What core version are you reporting this for?

Version 10, 291

### Relevant log output

```shell
THREE.WebGLRenderer: Context Lost.
core.min.mjs:8 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'length')
[No packages detected]
    at e.setBlendMode (core.min.mjs:8:108253)
    at e.checkBlendMode (core.min.mjs:8:108884)
    at e.set (core.min.mjs:8:107352)
    at r._renderDirect (graphics.min.mjs:8:26254)
    at r._render (graphics.min.mjs:8:24956)
    at e.render (display.min.mjs:8:20282)
    at e.render (display.min.mjs:8:20353)
    at CanvasOcclusionMask.render (foundry.js:26362:11)
    at e.render (display.min.mjs:8:20353)
    at e.render (display.min.mjs:8:20353)
    at e.render (display.min.mjs:8:20353)
    at r.render (core.min.mjs:8:125375)
    at e.render (app.min.mjs:8:1453)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Foundry VTT does not use `three.js` - the module which is maintaining a separate canvas. The message here `THREE.WebGLRenderer: Context Lost.` does not originate from Foundry VTT but rather a separate module. Some possible modules you may have installed which do use three.js are:

- Dice So Nice
- Ripper 3d Canvas

I recommend testing with those modules disabled. In both cases, each module offers some performance optimization options which can perhaps resolve your problem. I wish you luck in tracking it down, but I'm going to close this issue since it's not a core Foundry VTT problem.
