### ISSUE TITLE
Deprecate `Combat#getCombatantByActor` and `Combat#getCombatantByToken` in favor of pluralized versions `Combat#getCombatantsByActor` and `Combat#getCombatantsByToken`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9241]
### User Experience

Currently, `Combat.prototype.getCombatantByActor` just finds the first available actor by id among all combatants:
```js
getCombatantByActor(actorId) {
    return this.combatants.find(c => c.actorId === actorId);
  }
```

This seems like an invitation for bugs. Combat Tracker can have multiple combatants with the same actor id. Just arbitrarily pulling the first one seems useless at best, and more likely, the cause for some confusion. I recommend instead deprecating this method and instead relying on one that returns a filtered array:
```js
getCombatantsByActor(actorId) {
    return this.combatants.filter(c => c.actorId === actorId);
  }
```

The proposed alternative would force systems or modules to actively decide how to deal with combatants that share an actor id, instead of just silently ignoring some of the combatants that could otherwise be returned by the original method.

**Comment by aaclayton** [comment]
Good suggestion, I was thinking about that myself recently and didn't write it up.

**Comment by stwlam** [comment]
Perhaps an `Actor#combatant` getter would be useful when one has the actor in hand--which is perhaps the case most of the time when one is calling `Combat#getCombatantByActor`. The getter could function the same as `TokenDocument#combatant`, looking for a combatant from the currently viewed `Combat`. Instead of finding by ID, it could find by reference.

**Comment by wake42** [comment]
Maybe the `Combatant#token` getter should be migrated to `Combatant#tokens` as well to follow this change then, since a combatant can have multiple tokens.

**Comment by wake42** [comment]
You are of course correct - it was a bit late when I wrote that... The connections are like this I believe:
```mermaid
flowchart LR
    C1[Combatant 1] ---T1[Token 1]
    C2[Combatant 2] --- T2[Token 2]
    T1---A1[Linked Actor]
    T2---A1
```
```mermaid
flowchart LR
    C1[Combatant 1] ---T1[Token 1]
    C2[Combatant 2] --- T2[Token 2]
    T1---A1[Unlinked Actor 1]
    T2---A2[Unlinked Actor 2]
```
I think I was thinking about the defeated status of a combatant and that should be linked to the Actor, so that `Combatant 1` should always have the same defeated status as `Combatant 2` in the `Linked Actor` graph above.
But I'm sure you're already have that in mind so disregard this comment 😊

**Comment by aaclayton** [comment]
Awesome use of embedded flowcharts. I'm going to have to learn that syntax! The `defeated` state is tracked on the `Combatant` directly, so each combatant can be individually marked as defeated or not-defeated. Of course, sometimes marking a combatant as defeated would give a status effect to the actor, in which case it would depend on whether the actor is linked or not.

**Comment by wake42** [comment]
I guess that in my mind a defeated actor (combatant linked to an actor) should get all the other combatants connected to that actor defeated as well. But maybe there are cases where you don't want that behavior.
