### ISSUE TITLE
Add function to get primary owning user for a document

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9273]
### User Experience

Kind of like the new `game.users.activeGM`, but something for actors and such to fetch primary active user (e.g. with `actor.activeOwner`).

This would help immensely with any logic where you want to perform an action with owning user, but don't want to run it on all owning users in case they share ownership.

For example, if I have some logic in updateCombat to act on current combatant and want to do it on owning user, this would trivialize the code. Since the triggering user has nothing to do with the _current_ combatant, the user parameter is not useful for deciding who to perform the code with.

This would also potentially encourage to have various code to run on normal user side instead of GM since you can make the owning user run updates easily, instead of always falling back to GM, when it can't be otherwise easily determined.

This would result in code something like the following:
```js
const owner = actor.activeOwner ?? game.users.activeGM;
if (owner.id !== game.user.id) return;
```
Instead of complex lookups and filtering to determine who should run the code that looks probably something like the following:
```js
const owner = Object.entries(actor.ownership)
      .filter(([_, level]) => level >= CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER)
      .map(([userId, _]) => game.users.get(userId))
      .filter(u => u?.active)
      .sort((a, b) => a.id.localeCompare(b.id))[0] ?? game.users.activeGM;

if (owner.id !== game.user.id) return;
```

**Comment by MrVauxs** [comment]
Gonna chime in to say I would love to see this, `primaryUpdater` always returns the GM which is not applicable for player-driven actions.

**Comment by dev7355608** [comment]
We added `Users#getDesignatedUser` and `User#isDesignated` (#11698). What the "primary/active owner" should be depends on what you want the user to be able to do with the document. Note that as a player owner you might not be able to delete the document, or you might not be able to update every field of the document because some are restricted to be GM-only. So if we added something like `activeOwner`, it would have to return the active GM in a lot of cases anyway, because a player owner is not powerful enough to modify the document in every regard. But you might not actually need a GM for your purposes and so it would fail unnecessarily if no GM is online, but with `Users#getDesignatedUser` it will succeed given that the condition is tailored exactly for your use case.

Examples:
```js
game.user.isDesignated(user => user.active && document.testUserPermission(user, "OWNER"));
```
```js
const changes = { /* ... */ };

game.users.getDesignatedUser(user => user.active && document.canUserModify(user, "update", changes));
```
