### ISSUE TITLE
KB Updates - Macros

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9308]
- [ ]  Review Article accuracy from a programming standpoint
- [ ]  Detail changes to 'actor' reference in script macros (it now uses the currently selected token's actor)

**Comment by paulohdsc** [comment]
A reminder to talk about this improvement: https://github.com/foundryvtt/foundryvtt/issues/7184

**Comment by mattexdee** [comment]
I've updated the Macro page, a changelog:
- Fixed some minor typos
- Added that macros can also be executed from the chat box with `/macro Macro Name Here`
- Added clarification about how `@Document["Document Name Here"]` will need `Document` changed to be the Type of the Document
- Removed the quotation marks as well since those shouldn't be included
- Added section on passing arguments programatically and through the chat box
- Included details about capturing return values
- Added an example macro for demonstrating passing arguments
- Updated the Scene Wall and Light Duplicator macro for V11
- Updated the Emergency Campaign Resolver macro for V11
- Updated it to include that both `actor` and `token` are populated with values from the currently selected Token and cleaned up a couple examples
