### ISSUE TITLE
Add a way to get UUID of a document inside a compendium without fetching the document itself

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9342]
### User Experience

Currently I need to do `(await pack.getDocument(documentId)).uuid` or manually construct the UUID to accomplish this.

It'd be better if there was a helper function for this purpose (e.g. `pack.getDescendantUUID(id)`) or the index included the UUID.

**Comment by aaclayton** [comment]
Good suggestion. I think there are a couple places where we manually compose a compendium UUID because we lack a centralized function that handles this for us.

![image](https://user-images.githubusercontent.com/2468703/236843912-ecda96fd-7aaf-40b8-9b24-ca02e98eee82.png)

We should prioritize adding a static method that, given the components of the UUID (pack name, document name, document ID) handles the formatting in the correct way.
