### ISSUE TITLE
`Roll#render` does not pass its own flavour to its template

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9347]
Originally reported by Mana#4176 https://discord.com/channels/170995199584108546/956306859491471420/1102268540008018000

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Any  
**Short Description of bug:** Roll rendering does not pass roll flavor to the template, causing it to always be ignored despite the template having flavor rendering built-in.  
**Simple steps to reproduce the bug:**
```js
const roll = await new Roll("3d6").evaluate();
roll.options.flavor = "AAA";
roll.toMessage();
ChatMessage.create({
   type: CONST.CHAT_MESSAGE_TYPES.ROLL,
   rolls: [roll, roll],
});
```

In neither case above does the flavor get included.

Roll.render() itself only takes the flavor from the parameters passed to the function instead of from the roll itself. But at least ChatMessage roll rendering explicitly does not do so.
It's trivial oneliner modification to the Roll.render() function to pass the flavor option in that fixes it.

**Comment by dev7355608** [comment]
@mkahvi Is that something that used to work? I don't think that `Roll.options.flavor` is documented anywhere.

**Comment by mkahvi** [comment]
Foundry didn't support chat messages with multiple rolls before v10 (IIRC), so I don't know if it was much of a thing, I guess the flavor was stored in the chat message itself.

Anyway, the point is:
- .render() itself accepts "flavor" parameter, but it is not actually given by anything in Foundry, so it's always undefined.
- The roll template used by .render() itself suggests that each Roll should be able to have flavor. You can see this if you apply the oneliner fix mentioned in the bug report and run the example.
  - That is, change flavor line in render()'s chatData to: `flavor: isPrivate ? null : flavor || this.options.flavor,`

At minimum this points that the render function nor the base template used by said render should not have flavor parameter since it's not actually used by core, if this isn't fixed to take the flavor from the roll instead for multi roll messages.

**Comment by aaclayton** [comment]
Delaying any work on this until V12 when we focus on dice rolling framework. Sorry if that was something folks hope would make V11.
