### ISSUE TITLE
Relaxed assorted methods to be protected instead of private

### ISSUE THREAD

**Issue by Muttley** [foundryvtt/foundryvtt#9471]
The following methods are now protected instead of private.
- `ActiveEffect#_displayScrollingStatus`
- `Combat#_playCombatSound`
- `Token#_canViewMode`
- `Token#_getBorderColor`
- `Token#_getTooltipText`
- `Wall#_getWallColor`
- `Wall#_playDoorSound`

**Comment by Fyorl** [comment]
That method was previously annotated as `@private`. We don't consider changes to the private API to be breaking, or offer deprecation paths for them, so this is not a bug. We should consider making this a `@protected` method instead though since it is indeed impossible to even call it from a subclass now.
