### ISSUE TITLE
Investigate potential NEDB -> LevelDB conversion crash

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#9507]
Report <https://discord.com/channels/170995199584108546/1065764070680186930/1112246564178645053>

**ALL MODULES DISABLED?** False, but only have content modules enabled
**OS, Hosting, Browser (if applicable)**: Windows, LocalHost, Chrome 
**Short Description of bug**: NEDB conversion crashed on initial attempt
**Simple steps to reproduce the bug**: Re-enabled a bunch of compendium pack modules that were disabled in the swap from v10 to v11 compatibility.  Migration crashed after migrating a bunch of the nedb files. I closed browser, re-opened world, and had no issues, but the console has stopped providing updated status
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/2468703/a4f2088c-0f4b-476f-b069-f946fdb83861)

**Comment by Fyorl** [comment]
Seems to have been caused by a single bad item in that one compendium pack, specifically the 'Quick Flex Supreme Confidence' item had an object for its `effects` field rather than an array. Not even an array-like object, so not sure what was going on there. Either way I've hardened this logic to raise a warning and skip over bad collections like this.
