### ISSUE TITLE
Foundry does not respect the order folders and packs appear in `packFolders` when manually sorting

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#9519]
### What happened?

The order for both folders and packs should match the structure of `packFolders` but instead it always sorts alphabetically. `"sorting": "m"` seems to be ignored.

Pack Folders in `manifest.json`:  
```json
  "packFolders": [
    {
      "name": "My Custom Compendium",
      "sorting": "m",
      "color": "#57534e",
      "packs": ["intro"],
      "folders": [
        {
          "name": "B",
          "sorting": "m",
          "color": "#44403c",        
          "packs": ["classes"] 
        },
        {
          "name": "A",
          "sorting": "m",
          "color": "#1e40af",
          "packs": ["items"]
        },
        {
          "name": "D",
          "sorting": "m",
          "color": "#5b21b6",
          "packs": ["spells"]
        },
        {
          "name": "C",
          "sorting": "m",
          "color": "#9f1239",
          "packs": ["monsters"]
        }
      ]
    }
]
```

How it looks in Foundry:

![image](https://github.com/foundryvtt/foundryvtt/assets/138311/871db62e-9944-4081-8579-0fce7b46e326)

### What core version are you reporting this for?

Version 11 Build 299

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by MaxPat931** [comment]
I think the order of the packs in the folders is determined by the order of the packs in the `packs` section of the manifest

**Comment by phenomen** [comment]
> I think the order of the packs in the folders is determined by the order of the packs in the `packs` section of the manifest, I only looked at this briefly with one module, does that order track for you?

I can confirm that's not the case. Reordering packs in `packs[]` does not affect the order in Foundry.

**Comment by MaxPat931** [comment]
Looks like it will reorder, even in the same world, as long as the user hasnt modified the order of the packs themselves, then the order is defined in that world by the user. Which makes sense because then if a module owner adjusts the folder structure later a user's personal config gets overridden without warning and that would cause a lot of confusion.
But I agree it would be more intuitive for module authors to have the order defined in `packFolders`

https://github.com/foundryvtt/foundryvtt/assets/86370342/162f911e-7991-45dc-b681-2492379bdb7f
