### ISSUE TITLE
Consider relaxing the uniqueness constraint on compendium packs if they have a different `system` property

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9560]
It should be impossible for two compendium packs that share a `name` but have different `system`s to appear in the same world. With that in mind, we could relax the uniqueness constraint on `name`, if the `system`s are different. This would avoid some pain for existing packages that will have to change the `name` of their (previously working) compendium packs, breaking any cross-references they may have or existing content links in worlds that use them.

This may cause issues elsewhere, though, where a unique ID to reference the packs is needed. Unpacking via the CLI is one I can think of immediately. But also internally, if the pack metadata is ever placed in a `Map`, for example, this will cause issues.

**Comment by aaclayton** [comment]
I would be uncomfortable with this, I think. I think each compendium pack should be uniquely identified within the module that provides it, there are circumstances where we inspect which compendium packs are available and non-unique names would break certain data structures like objects/maps. Also we need the path for each compendium to be unique so it would feel better to me to have:

* name `actors-pf2e` points to `packs/actors-pf2e`
* name `actors-dnd5e` points to `packs-actors-dnd5e`

Rather than having both named `actors` but with different paths. I understand that this would be adding a layer of developer-friendliness but my own initial opinion is that it's not worth the potential trouble.

**Comment by Fyorl** [comment]
There is some recourse here: The `path` can always be used to uniquely identify the pack, as the filesystem forces it to be unique. So it's (I think) impossible for there to be packages already out there that have duplicate pack paths. There are, however, definitely packages out there that have duplicate pack names (because we never enforced this previously).

These packages worked fine in earlier versions (presumably because they didn't have duplicate pack paths), but now they are forced to change the `name`s of some of their packs, which is a very poor experience for everyone involved:
1. Any content in the package must locate and update all UUID references (wherever they are) to those affected packs.
2. Any worlds that have used the package, imported the content, or created new content that contains UUID references to those packs must also be updated. Most likely this is content links in journals, but there could be other system-specific UUID references too. In `dnd5e`, Advancements contain UUID references to compendium content, so renaming the pack would break Advancements in any custom classes, for example.

(1) is unfortunate churn, but is certainly within the power of the package author to resolve. For (2), however, I don't see any clear migration path at all unfortunately.
