### ISSUE TITLE
Fix compendium pack labels not being localised in the sidebar

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9561]
### User Experience

Simple improved support for translations would be to run pack and pack folder labels through localize.

This is trivial to implement, too, simply replacing `{{label}}` with `{{localize label}}` in the HBS files will accomplish it.

Packages should not be negatively affected by this, so it should be fairly safe improvement.

For developers all this would change is that they'd have the _option_ of adding some "MyPackage.Packs.Junk" as the label instead of plain "Junk" or similar, while leaving the old working as it did (with obvious caveats).

**Comment by aaclayton** [comment]
I'm not sure the best way to handle this. Our assumptions is that the world database stores localized data. If we wanted to localize the names of package-defined compendium packs that localization should occur before those folders are created. This operation happens server-side though and we don't currently have the localization functionality available on the server to apply. 

Implementing this feature would require mirroring our `Localization` module to be shared by both client and server so that the server can apply localization strings before creating the folder hierarchy.

This change would be out of scope for V11 but we can consider it for future versions.

**Comment by Fyorl** [comment]
It seems the compendium label in the actual compendium app itself is already localised, but the compendium label in the sidebar is not. So this seems like it's actually a bug, and I will reframe it as such.
