### ISSUE TITLE
Dragging and dropping an image inside the Tile Browser file picker incorrectly re-uploads the image data when it is dropped.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#9676]
### What happened?

If you start dragging a file in the FilePicker in a module/system folder and then change your mind and release, a warning is displayed that you uploaded a file to this directory.

Seems to me like the drop event should just get aborted since the file already exists.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/3856f130-ff30-4336-a042-4b74c621bad0)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

* Open FilePicker.
* Open a folder with assets from a module or system, such as jb2a.
* Start dragging a file but then let go almost immediately without leaving the filepicker window.

### What core version are you reporting this for?

11.302

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
How would we distinguish between a file that was intentionally dropped in order to replace an existing file, vs. a file that has been accidentally dropped because the user changed their mind? I think we would have to record the origin of the drag operation so that we know it came from the FilePicker itself? Either way I don't think this can be considered a bug.

**Comment by aaclayton** [comment]
I'm confused about what is described in this bug. 

> If you start dragging a file in the FilePicker in a module/system folder and then change your mind and release, a warning is displayed that you uploaded a file to this directory.

This sounds like it's describing a drag+drop UX within the FilePicker itself, which the core software does not support. Otherwise, if we are talking about dragging and dropping a file from the system OS into the filepicker, we correctly display the warning that a file has been uploaded to a location the user doesn't have control over. 

It sounds like the OP is suggesting something different though. @krbz999 can you clarify exactly what you mean by "If you start dragging a file in the FilePicker in a module/system folder and then change your mind and release"?

**Comment by krbz999** [comment]
https://github.com/foundryvtt/foundryvtt/assets/50169243/a3a43902-dbc7-4662-984c-139a9a896172
