### ISSUE TITLE
Export from Item Folder to Com Pack Folder puts Items in target root instead of target Folder

### ISSUE THREAD

**Issue by jstSonota** [foundryvtt/foundryvtt#9702]
### What happened?

Reproducible steps:

1. Folder with items (my test is ten ancestry feats)
2. State: I already exported these to an Ancestry Feats compendium pack. So it has the target folder with 10 feats. Original export also dumped the feats in the root.
3. I updated Feat3, now I want to export. Right click Items folder with my 10 feats. Here's my selection, popup:
![image](https://github.com/foundryvtt/pf2e/assets/137226870/07431d6c-e2cb-4dea-b4fd-51318e85e409)
4. End result: It's also in the above screenshot. My feats were deleted from the target pack's folder and moved/created into the root of the compendium pack instead of staying in the target folder and being updated.

If you don't uncheck "Keep Folder Structure?" the Folder dropdown is greyed out. If you export like that, same problem.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Reproducible steps:

1. Folder with items (my test is ten ancestry feats)
2. State: I already exported these to an Ancestry Feats compendium pack. So it has the target folder with 10 feats. Original export also dumped the feats in the root.
3. I updated Feat3, now I want to export. Right click Items folder with my 10 feats. Here's my selection, popup:
![image](https://github.com/foundryvtt/pf2e/assets/137226870/07431d6c-e2cb-4dea-b4fd-51318e85e409)
4. End result: It's also in the above screenshot. My feats were deleted from the target pack's folder and moved/created into the root of the compendium pack instead of staying in the target folder and being updated.

If you don't uncheck "Keep Folder Structure?" the Folder dropdown is greyed out. If you export like that, same problem.

### What core version are you reporting this for?

11 302

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Not a bug; this is working as designed: The 'export to compendium' operation is the opposite of the 'import all content' operation. 'Import all content' places all content inside a top-level folder, 'export to compendium' places all content of a folder inside a compendium.

**Comment by jstSonota** [comment]
It looks like they're opposites in that "Export to com" exports from your Items tab and puts those folders into a compendium.
"Import all content" is a compendium pack feature that takes all the content of the compendium and brings it into your Items folder.

Respecting the folder structure that exists in V11 now seems like a common objective for both functions. Why would you ever just want to dump items organized by folders into root?

**Comment by Fyorl** [comment]
The two functions are the reverse of each other. If I take a compendium that looks like this:
```
A
┕ A1
┕ A2
┕ A3
B
┕ B1
┕ B2
┕ B3
```
And do 'import all content', I am prompted to pick a folder name to import it to, so I pick 'Items', I then end up with a folder in the sidebar called 'Items', that looks like this:
```
Items
┕ A
  ┕ A1
  ┕ A2
  ┕ A3
┕ B
  ┕ B1
  ┕ B2
  ┕ B3
```
If I then take that new folder and do 'export to compendium', I get back the same structure that I started with. The folder is being exported as a compendium, not placed into a compendium. For placing folders into a compendium, you can drag-and-drop them from the sidebar.

**Comment by jstSonota** [comment]
When you say the items are "being exported as a compendium, not placed into  compendium" I don't understand. You have to select an existing compendium. You have Folder options in the export window. Then the folder options are ignored, and your export is dumped into the root of the compendium. What's the benefit of ignoring the folder structure? You mention "I get back the same structure that I started with." I'm reporting that is not true. The folder structure is not being respected on export.

**Comment by Fyorl** [comment]
> The folder structure is not being respected on export.

Sorry, it's possible I was too focused on the 'original export also dumped feats in the root' part of your report. You can see here the the folder structure is being respected on export, with the exception of the top-level folder, which is by design.

https://github.com/foundryvtt/foundryvtt/assets/207433/b72ca935-7a02-458b-aea2-3c3c2b9375ed

With regards to the target folder dropdown being ignored, I can reproduce that, which may be a bug, but I'm less familiar with the original intentions here. If 'keep folder structure' is checked it works as expected. You mentioned in your original report that the folder dropdown was disabled unless 'keep folder structure' was unchecked. That might be the cause of mismatched expectations, as you can see that I'm not able to reproduce that issue here.

https://github.com/foundryvtt/foundryvtt/assets/207433/d88890d7-d869-4229-b3f5-f6a077471acc

It's also entirely possible that there have been some fixes on the version I am testing with that aren't present in the 302 build. Are you able to re-test with the 304 build (released yesterday) and verify whether you're still experiencing the same issue?

**Comment by Fyorl** [comment]
I was able to verify that there is a bug here: The target folder is ignored if 'keep folder structure' is unchecked.

**Comment by jstSonota** [comment]
That's great news. Thanks for checking it out!
