### ISSUE TITLE
Pressing Escape closes all open windows

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9752]
Originally reported by forien https://discord.com/channels/170995199584108546/1065764070680186930/1125457900907798560

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser:** *Foundry 11.304*, *Windows 11 64-bit*, but also *Chrome 114.0.5735.199* (tested both native client and hosted accessed by browser)
**Short Description of bug:** Pressing `Escape` or any other keybind set as `Toggle menu / Dismiss window` closes all windows, even minimized ones. I assume it's a bug since keybind is singular, not plural. While I agree that sometimes closing all windows is nice and I would love to keep it as another keybind, more often than not, I press `Escape` by either by accident or by wanting to close a single window, deselect token, get out of input or do something else. My (new to Foundry) players also intuitively press `Escape` when they want to close a single window and keep losing all opened journals, character sheets etc. So my suggestion is to make `Escape` as `close focused window`, but allow for something like `Shift+Escape` to `close all opened windows`
**Simple steps to reproduce the bug:** 
- Open bunch of windows (actors, journals, items, menus),
- focus on one of the opened windows,
- press any keybind set to `Dismiss window`.
**Screenshots and/or console errors:** n/a

EDIT: I made my own temporary solution as shown here: https://discord.com/channels/170995199584108546/1065764029278212230/1125745829974638606
Regardless, I think it should be core as expressed by these people: https://discord.com/channels/170995199584108546/1065764029278212230/1125815087400243250, https://discord.com/channels/170995199584108546/697845559435853865/1064624790998098031, https://discord.com/channels/170995199584108546/517504137403826177/905563317307867176, https://discord.com/channels/170995199584108546/517504137403826177/1116541281661886525, https://discord.com/channels/170995199584108546/517504137403826177/905563317307867176, https://discord.com/channels/170995199584108546/517504137403826177/839266454721265694, https://discord.com/channels/170995199584108546/517504137403826177/651643745275478026
There are probably more, but I think I made my point 🙂

**Comment by Fyorl** [comment]
Not clear if the bug is with the behaviour of the keybind, or the labelling of the keybind.

**Comment by aaclayton** [comment]
> Not clear if the bug is with the behaviour of the keybind, or the labelling of the keybind.

Current intended design is that ESC closes all open window apps. Design could be changed, but the "short term" issue here is probably one of keybind labeling or hint text.

**Comment by Forien** [comment]
Hello, I will clarify :) 

The bug report was mostly about discrepancy between labelling and behaviour, so I guess labeling is _the bug_ here. Because if keybind label said "close all windows", I would know it's intended and instead of reporting a bug I would post a "feature change suggestion".

That said however, I do believe (and from what I found so do other people) that the intended behaviour of the ESC keybind is not always in line with intuition most users have. And inability to change/disable that keybind sometimes leads to frustration.  

So yes, I would suggest considering expanding the feature with the UX in mind, maybe adding optional other keybind and ability to freely rebind ESC if possible. Or a client-side setting toggle so that every user can decide if they want to close all windows or one by one.
