### ISSUE TITLE
Actor's prepareDerivedData & prepareData not correctly executed in unlinked tokens

### ISSUE THREAD

**Issue by LinkedFluuuush** [foundryvtt/foundryvtt#9805]
### What happened?

In my system I compute many things in the `prepareDerivedData` function of the actor, and re-use this data in the sheet and other parts of the system.

When creating an unlinked token from an actor, when opening the token's sheet by double-clicking on the token, the prepared data is absent from the actor in the token.

Debugging shows the functions are called correctly, but the actor linked to the token is not the correct one.

Weirdly, when reloading my page, the token is correctly set up, with the derived data present.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

Create a system with this sample code : 

Actor document : 
```
export class CustomActor extends Actor {
    _prepared = null;
    
    constructor(...args) {
        super(...args);
    }

    prepareBaseData() {
        super.prepareBaseData();
        this._prepared = 'PREPARED';
    }

    prepareDerivedData() {
        this._prepared = 'DERIVED';
    }
}

```

Actor sheet document : 
```
export class CustomActorSheet extends ActorSheet {
    async getData() {
        // Retrieve the data structure from the base sheet. You can inspect or log
        // the context variable to see the structure, but some key properties for
        // sheets are the actor object, the data object, whether or not it's
        // editable, the items array, and the effects array.
        let context = super.getData();

        console.log(context.actor._prepared);

        return context;
    }
}

```

Create an actor and create a token from this actor.
On first opening of the token sheet, console logs "null".

### What core version are you reporting this for?

Version 11 Build 305

### Relevant log output

```shell
No log output
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
What's happening here is that data preparation is occurring in the constructor (`DataModel#_initialize` is called at the end of the `DataModel` constructor), and then the class' instance field initializers are being called and setting the value of `_prepared` to `null`. Since this is a subclass of `DataModel`, the initializers are called right before `super()` returns (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#evaluation_order))

> The initializer is evaluated during instance creation, at the start of the constructor (for base classes) or immediately before the `super()` call returns (for derived classes).

You can see this by first commenting-out the `_prepared = null` and then you should start seeing 'PREPARED' in the console whenever you create a new Actor and open its sheet.

It's very appreciated putting together these small examples to help us reproduce issues. It's not clear whether the issues in your system with unlinked token actor data in sheets are related to the class field initializers. I'm assuming probably not, so if you're still having trouble, please reach out to us in the [#dev-support](https://discord.com/channels/170995199584108546/811676497965613117) channel on discord, or continue replying here, and we'll try to get to the bottom of your issue.

**Comment by LinkedFluuuush** [comment]
Hello ! Thank you for your answer. I learned something about Javascript today, we'll say :)
Actor initialization must be done in another way, after construction, in linked actors. But the issue resolves itself if I don't declare the property in the class, so I guess I'll use a getter to get around this :)

Thanks for your help !
