### ISSUE TITLE
Call the `refreshPlaceable` hook before `_applyRenderFlags`

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#9855]
### User Experience

Currently, `PlaceableObject.prototype.applyRenderFlags` calls the placeable's `_applyRenderFlags` method, then calls the hook:
```js
// Incremental refresh
this._applyRenderFlags(flags);
Hooks.callAll(`refresh${this.document.documentName}`, this, flags);
```
Consider reversing this, so that the Hook is called, followed by `this._applyRenderFlags.` This would permit modules to change the flags that are passed to `_applyRenderFlags`. Why? Because if a flag should be set to true/false conditionally based on some condition, it would be preferable to set the flag first, then do the actual refresh. Otherwise, the module is forced to either re-run the flags (possibly introducing circularity errors) or find another means to accomplish the refresh.

This is really only a problem if the flag is conditional on some event. Otherwise, the module could change the flags through the propagation mechanism.

**Comment by aaclayton** [comment]
The design that we use with render flags is, instead of at render-time checking whether a condition has been satisfied, handle the assignment of render flags at the point when the event initially occurs. 

The goal is to remove logic in the render loop of "should we do X? or should we do Y?" and instead to already know which operations need to be performed for a given frame. The purpose of the `refresh{Placeable}` hook should not be (in my opinion) to decide what rendering operations to perform but rather simply to respond to the prescribed operations. 

I understand that this is an imperfect system for some ostensibly legitimate module use cases though, but I wonder if there is a better way to accommodate those.

@Feu-Secret and @dev7355608 for thoughts.

**Comment by dev7355608** [comment]
We need the `refreshPlaceable` hook to be called after the render flags are applied to allow modules to react to changes to the placeable. If the additional flag is conditional on some event, it should be set when the event occurs.

**Comment by caewok** [comment]
Fair enough. I will investigate alternative approaches.
