### ISSUE TITLE
Versioning for modules is wrong

### ISSUE THREAD

**Issue by mawburn** [foundryvtt/foundryvtt#9862]
### What happened?

A user raised this issue a few weeks ago, saying that Foundry was trying to downgrade my module. I added a newer version to try and bump that when the issue was raised, but did it again today and am seeing the same thing.

https://github.com/mawburn/foundry-user-latency/issues/11 

The Forge actually gets it correct, for some reason.

This is what I'm seeing as the latest release, after releasing the second version bump to try and fix it:
![Screenshot 2023-07-30 at 5 06 45 PM](https://github.com/foundryvtt/foundryvtt/assets/2829924/63747bc7-b3f9-4407-9a23-1128165f81b7)

This is the version history:
![Screenshot 2023-07-30 at 4 56 53 PM](https://github.com/foundryvtt/foundryvtt/assets/2829924/cea88aa8-e2ca-4c94-aa71-5d49138edf6e)

This is what The Forge shows, before the latest 2.0.3 version bump: 
(edit: I didn't notice the v isn't in the 2.0.3 but the problem existed in 2.0.2)
![Screenshot 2023-07-30 at 4 46 02 PM (1)](https://github.com/foundryvtt/foundryvtt/assets/2829924/469eef58-587f-47e5-91fd-a0c0929db0f8)

I can't personally recreate it locally either, at least on v11:
![Screenshot 2023-07-30 at 7 18 55 PM](https://github.com/foundryvtt/foundryvtt/assets/2829924/8cbc864d-0614-4c17-bd78-04838d94fb54)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

I'm honestly not sure, I can not reproduce the issue myself. But the web client for the releases on Foundryvtt.com is showing the wrong version.

### What core version are you reporting this for?

10

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by mawburn** [comment]
There was some discussion in the developer Discord about using a v in my semver name. This is a common pattern and something I've always used. 

- https://github.com/microsoft/TypeScript/tags
- https://github.com/facebook/react/tags
- https://github.com/electron/electron/tags
- etc

**Comment by Fyorl** [comment]
The version input into the admin panel of the package repository must *exactly* match the version string in the package's manifest. Checking this package I can see that all its entries in the package repository are prefixed with a 'v', while only one of the manifests ('v2.0.4' I think) is prefixed with a 'v'. If these version strings do not match exactly, the update behaviour will be unexpected because '2.0.5' and 'v2.0.5', for example, are considered to be completely different versions.

**Comment by Fyorl** [comment]
> What is this not true?
> 
> `isNewerVersion('v2.0.1', 'v1.3.9')`

This is true. But `isNewerVersion('2.0.1', 'v1.3.9')` is `false`, and this sort of check can happen when the software checks the website package repository for sidegrades or track changes. It will compare the version in the installed manifest with the version on the package repository. If the version strings in the package repository were correct, then this check would be `isNewerVersion('2.0.1', '1.3.9')`, which is `true`, which I suspect would resolve this problem.

> Additionally, why does that `isNewerVersion` function simply not ignore the v to add consistentcy?

There is nothing special about the letter 'v' as far as `isNewerVersion` is concerned. It allows for totally alphabetical version strings if that is what you want. The issue is that by including a non-digit in any component of a version string, it is treated as a lexical comparison rather than a numerical one, leading to unexpected results, e.g. `isNewerVersion('v10', 'v9'); // false`.

> I am following a common standard in the JS ecosystem. I offered 3 major libraries that use this standard above, one being the engine Foundry itself runs on.

In those examples you are conflating the git *tag* to the package's *version*. If you download one of the electron `v26.0.0-beta.9` releases and check the `version` file in that archive, you will see `26.0.0-beta.9` (note the lack of a prefixed 'v'). Foundry is not sensitive to the git tags that you use. You may prefix a 'v' in git tags if you prefer.

**Comment by mawburn** [comment]
Yeah that's fine. There was never a `2.0.1` though and there was never a `1.3.9` either.

**Comment by Fyorl** [comment]
> Yeah that's fine. There was never a `2.0.1` though and there was never a `1.3.9` either.

If I go to your project page and download the `v1.3.9` release, and open the `module.json` inside the `module.zip`, I can see `"version": "1.3.9"`. Please note the lack of a prefixed 'v' in that version string. Your manifest version strings did not match the version strings on the package repository, which is what I mentioned in my first comment, and later repeated:

> The version input into the admin panel of the package repository must *exactly* match the version string in the package's manifest.
