### ISSUE TITLE
Light sources don't update in real time when not on the light layer

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9911]
Originally reported by gambettv https://discord.com/channels/170995199584108546/1065764070680186930/1135680011903439011

**ALL MODULES DISABLED?** True
**OS, Hosting, Browser (if applicable)**: Windows 10, Foundry App v11.306
**Short Description of bug**: Light sources placed on the map (as opposed to ones built in tokens) only update in real time if you are on the Lights button. However, light source icons can very easily block details I need to see, so I like to switch away from the Lights button so that the icons go away and I can see what I'm doing, but now I can't because it doesn't update in real time.

**Comment by Fyorl** [comment]
I might not be understanding this one correctly. It sounds like the reporter is opening a light source edit dialog, then switching away from the light layer to continue editing the light source. I'm not sure if that's a workflow we particularly support, and it might have only been working incidentally before.

I might have misunderstood, though, or there might actually be a bug here and we do allow for editing lights when not on the light layer, so I will tentatively mark this as a bug for investigation.

**Comment by unsoluble** [comment]
Could address the UX issue (not being able to see what you’re doing with small lights due to the control icon obscuring) more directly, by maybe doing something like toggling the icons off with Alt while in the config window?

Or perhaps when you edit a light, the control icon for that light simply hides until you either cancel or save the edit?
