### ISSUE TITLE
Implement winston-daily-rotate-file to reduce file size impact of error and debug logs

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9972]
On longer running Foundry VTT servers (or in occasions where an error sequence ends up repeatedly looping), error.log and debug.log can grow to an inordinate amount of size, generally greater than 2GB. 

On discussion with Fyorl, WinstonJS appears to support a daily rotate call which allows for setting a max filesize or rotating on a specific time period which would help keep impact of logging filesizes low.

Theoretically this could be done during v11.5 as it should have 0 impact on general use and is only a tech debt change.

**Comment by Fyorl** [comment]
From @apoapostolov

### What happened?

I encountered the error "timeout in /setup in 30s" causing the following issues:
- mods can no longer be updated (update all, or individual updates)
- mod directory list can no longer be loaded
- systems may sometimes update (I only had 3) and sometimes will not update

I tried the following solutions suggested on Discord
- installed/reinstalled the system
- restarted server machine and router
- tested via VPN

None of these solutions worked until on #troubleshooting I was suggested to send the debug.log file. I found that the file had grown to 1.9GB and was unable to send it, so I renamed it and restarted the FoundryVTT server and this solved the issue immediately.

Pruning the size of debug.log may be needed to avoid this issue happening to other users. 

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- get "timeout in /setup in 30 seconds" error persistently
- delete debug.log
- the problem is fixed

### What core version are you reporting this for?

Version 11 Build 314/315

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
High priority. Probably isnt weight 5 but just in case. Doesn't necessarily have to be done during the dev2 phase.
